### ISSUE TITLE
Input type=range

### ISSUE THREAD

**Issue by lukasgarcya** [viewflow/django-material#102]
I can not use the input range type according to http://materializecss.com/forms.html#range. Not working.

**Comment by kmmbvnr** [comment]
Do you mean html5 range inputs?

```
<input type="range" id="test5" min="0" max="100" /
```

Is there any errors in js console?

**Comment by lukasgarcya** [comment]
I have custom widget in python code more specific 
intervalo = IntegerField(widget=NumberInput(attrs={'type':'range', 'min':'0', 'max':'100'}), required=False)

**Comment by lukasgarcya** [comment]
I haven't error in js console.

**Comment by lukasgarcya** [comment]
I tested materializecss pure and work fine.

**Comment by kmmbvnr** [comment]
So, it seems label on top for range input prevents clicks on a range 

http://forms.viewflow.io/demo/widget/integer/

**Comment by kmmbvnr** [comment]
So, the solution could be in creating a custom widget 

    class  RangeInput(NumberInput)
       ....

And add custom `material/fields/toppackage_rangeinput.html` template with proper layout

Django already pass max/min params to the widget from input filed - https://github.com/django/django/blob/master/django/forms/fields.py#L280 so the widget use-case would be following:

     intervalo = IntegerField(widget=RangeInput, max_value=0, min_value=100)
