### ISSUE TITLE
missing features in admin change_list

### ISSUE THREAD

**Issue by olivierdalang** [viewflow/django-material#106]
Hi !

The admin looks absolutely great ! I'd love to use it in my project, but I miss some key features :
- ability to order the records by clicking on the column headers
- model actions by selecting the records

And there could be some improvements :
- the filters section takes a lot of space, could we have it displayed exactly like the models list, but on the right ?

Are you working on it, or should I work on it and make a PR ?

Thanks !

Olivier

**Comment by kmmbvnr** [comment]
Pull requests are welcome

**Comment by kmmbvnr** [comment]
What do you mean by showing filters section like the models list, but on the right?

**Comment by olivierdalang** [comment]
##### filters/search/dates section

I would suggest to lay them out horizontally at the top of the list. In case there's a lot of filters, they could be folded into a button on smaller screens.
I find the current display on the right a bit annoying even of large screens in case the table has a lot of columns.

My initial suggestion was for a SideBar on the right for the filters, but I think it was a bad idea.

##### model actions (checkboxes)

I had a look at how we could add the checkboxes, but it seems not doable easily since Django hardcodes the <td><input..></td>, making it hard to add the label required by material to display the checkboxes without dirty hacks... I don't think it's possible to access to row's object's PK from the template.
I think we'd need https://code.djangoproject.com/ticket/6396 merged before doing anything

**Comment by kmmbvnr** [comment]
**filters/search/dates section**

Generally django app could have a lot of filters, ex - http://forms.viewflow.io/admin/zinnia/entry/

So i think, the ideal solution could be a right sidebar, hidden by default and opens on a filter icon click, may be it could be achieved with http://materializecss.com/side-nav.html

**model actions (checkboxes)**

Mm, may be we could just made some custom templatetags.  `filters/material/admin/templatetags` already have some code pasted from django admin

**Comment by yarnball** [comment]
I've got the latest clone of this repo- and I don't see model actions.

Did you have success with it?
