### ISSUE TITLE
inlines style in the admin

### ISSUE THREAD

**Issue by olivierdalang** [viewflow/django-material#111]
Hi !

Currently, the inlines sections in the admin forms look very much like regular formsets (a title with a thick underline).

I think it would make sense to make inlines objects look more "physical", so that it's clear to the user he's actually creating/deleting objects, and not only properties. I think the UI of choice for this would be a popout collapsible ( http://materializecss.com/collapsible.html#popout ).

What do you think ?

Olivier

**Comment by kmmbvnr** [comment]
Thank you for the idea, that's interesting question. But anyway, we need to handle both stacked and tabular inclines somehow, and current approach seems can do this mo consistently.
 
But anyway, till the admin have major functionality misses, the redesign is not top priority.
