### ISSUE TITLE
List_editable (check boxes) and Admin actions- when will they be implemented?

### ISSUE THREAD

**Issue by yarnball** [viewflow/django-material#112]
Hi,

This is an incredible project! Honestly- I've tried them all, and this wins. Well done.

The list_editable for a boolean field shows no ability to change the field (ie no changeable 'tickbox').

Also- the admin actions are not available.

Will these features every be added?

**Comment by kmmbvnr** [comment]
Duplicate #106

**Comment by yarnball** [comment]
I'm confused- it looks like the project already supports tick-boxes and actions?

The demo here has it- http://forms.viewflow.io/admin/integration/city/

But when I pip install django-material, actions aren't available. Is it from a different repo?
