### ISSUE TITLE
Wrong login/password pair message duplication in admin login

### ISSUE THREAD

**Issue by Lookyan** [viewflow/django-material#115]
After entering wrong login/pass pair I get duplication of error message (admin auth):
![screenshot from 2016-05-07 16 21 03](https://cloud.githubusercontent.com/assets/1040646/15092494/4dd5f44a-1474-11e6-8359-dc20d256ffc0.png)

The first is `<p class="errornote>"` and second is `<small class="error">`

Page template: [https://github.com/viewflow/django-material/blob/master/material/admin/templates/admin/login.html](https://github.com/viewflow/django-material/blob/master/material/admin/templates/admin/login.html)

Is it a bug?

**Comment by kmmbvnr** [comment]
Thank you for report!
