### ISSUE TITLE
Validation error for ChoiceField

### ISSUE THREAD

**Issue by inoks** [viewflow/django-material#118]
Validation error for ChoiceField shows actual value instead of human-readable name for language other than `EN`.

```
CONDITION_CHOICES = (
        (1.1, u'Perfect'),
        (1, u'Good'),
        (0.8, u'Bad'),
    )

condition = forms.ChoiceField(label=u'Condition', choices=CONDITION_CHOICES)
```

**Comment by kmmbvnr** [comment]
Could you provide more details? How validation error happens? What is django native behavior in this case?

**Comment by inoks** [comment]
Ok, here sample of `views.py`:

```
from django.shortcuts import render
from django import forms


class ConditionForm(forms.Form):
    CONDITION_CHOICES = (
        (1.1, 'Perfect'),
        (1, 'Good'),
        (0.8, 'Bad'),
    )

    condition = forms.ChoiceField(label='Condition', choices=CONDITION_CHOICES)


def form_view(request):

    form = ConditionForm(request.POST or None)
    form.is_valid()

    return render(request, 'test_form.html', {'form': form})
```

and here  `test_form.html`:

```
{% load staticfiles material_form %}

<!DOCTYPE html>
<html lang="en">
<body>
<form method="post">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <input type="submit" value="send">
</form>
{% include 'material/includes/material_css.html' %}
<script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
{% include 'material/includes/material_js.html' %}
</body>
</html>
```

if you have `LANGUAGE_CODE = 'en-US'` in your `settings.py` - form works fine, but if you switch to russian `LANGUAGE_CODE = 'ru-RU'` - you can't select values `Perfect` or `Bad` anymore:

![2016-06-05_22-19-30](https://cloud.githubusercontent.com/assets/370774/15808019/defcf64e-2b6c-11e6-9482-0d1dc969e4ca.png)

Seems problem is in number formatting for russian localization (comma instead of point).

**Comment by inoks** [comment]
Thanks!
