### ISSUE TITLE
All form fields rendered with `readonly="true"` if used with latest `bootstrap.min.js`

### ISSUE THREAD

**Issue by inoks** [viewflow/django-material#119]
`<input type="text" class="select-dropdown" readonly="true" data-activates="select-options-c752001c-b63f-1bd1-6c17-6c65c7591a53" value="Bad">`

Form works fine, untill i put latest `bootstrap.min.js` to my page:
`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
`

**Comment by inoks** [comment]
I use  latest version from `git+https://github.com/viewflow/django-material.git@master`

**Comment by kmmbvnr** [comment]
You should not use bootstrap and material on the same page.

**Comment by tufelkinder** [comment]
As I'm having the same issue on a form that is otherwise working very nicely side-by-side with bootstrap, this is a very unhelpful response.
