### ISSUE TITLE
404 error when trying to add a related (FK) object 

### ISSUE THREAD

**Issue by edvm** [viewflow/django-material#12]
In my model form i have some FK to another models, and when trying to add them in the admin, i got a 404 error. The problem seems to be at:

    (firefighters-hq) [edvm@laptop material]$ grep -R '%s%s' ./*
.    /admin/templates/material/fields/django_relatedfieldwidgetwrapper.html:        <a href="%s%s" class="add-another" id="add_id_{{ bound_field.html_name }}" onclick="return showAddAnotherPopup(this);">

I have attached a screenshot, when i click '+' i got the 404 error. Unfortunatly i dont know how to fix this issue to send a pr :-\

![screenshot from 2015-05-05 08 34 09](https://cloud.githubusercontent.com/assets/689275/7471835/25009c62-f302-11e4-9d12-24c1f252fce1.png)

**Comment by edvm** [comment]
Same bug seems to happen on demo page (when clicking the '+'), screenshot attached:
![screenshot from 2015-05-05 08 48 39](https://cloud.githubusercontent.com/assets/689275/7471963/b22133c6-f303-11e4-8f22-e97d7d159063.png)

**Comment by kmmbvnr** [comment]
Yep, it's require a custom template tag to create a valid link. But seems it's not the last issue with new items creation.

**Comment by edvm** [comment]
@kmmbvnr can i help you with this problem? Maybe if you can point me to some file, code or doc?

**Comment by kmmbvnr** [comment]
Here is how the url created in admin widget - https://github.com/django/django/blob/master/django/contrib/admin/widgets.py#L286

Basically, this should be recreated somehow in . /admin/templates/material/fields/django_relatedfieldwidgetwrapper.htm

Unfortunatelly django does not provide convinient methods on widget to get proper url in template, so i suppose it could be implemented as new tempate tag for material_admin template tags library

**Comment by kmmbvnr** [comment]
Another option is to make material/fields/django_relatedfieldwidgetwrapper.htm very simple, leave only {{ bound_field }} as content and do everything in admin/related_widget_wrapper.html

It have propery context with all required urls.

**Comment by kmmbvnr** [comment]
Actually i like the second option. If all django widgets was implemented as RelatedFieldWidgetWrapper most of django-material forms handing code will go away.

Unfortunately only RelatedFieldWidgetWrapper have rendered using django template

**Comment by diegocmsantos** [comment]
I have tested now and it's working.
The foreign model is saving but the select is not updated with the new model just saved.

**Comment by kmmbvnr** [comment]
Should be fixed now
