### ISSUE TITLE
Custom user models not properly supported?

### ISSUE THREAD

**Issue by khvn26** [viewflow/django-material#120]
Installed material-admin, getting VariableDoesNotExist at /admin/
Failed lookup for key [username] in %email here%

My project has a custom user model implemented without usernames, with USERNAME_FIELD set.
Looks like you explicitly reference AUTH_USER_MODEL.username in your code, but you rather should use AUTH_USER_MODEL.USERNAME_FIELD instead.

**Comment by kmmbvnr** [comment]
Guplicate #96
