### ISSUE TITLE
Usual save options in Django admin are not available

### ISSUE THREAD

**Issue by porksmash** [viewflow/django-material#122]
I noticed a couple issues when saving/adding models in the admin:

1. "Save and Continue Editing" and "Save and add Another" buttons are not displayed
2. A 'Save As New' button is not displayed for ModelAdmins where the [save_as parameter](https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.save_as) is set to True

**Comment by kmmbvnr** [comment]
Yep, here is the list of unsupported options https://raw.githubusercontent.com/viewflow/django-material/master/docs/admin.rst

Generally, it's too wide to have this buttons on the same line. So i think it could be implemented as a small dropdown tick on the right of the save button.
