### ISSUE TITLE
Show spinners in number fields

### ISSUE THREAD

**Issue by Kurtoid** [viewflow/django-material#123]
In the forms.css this exists
`input[type=number] {
    -moz-appearance: textfield;
}`

How can I disable this? I need number fields to show as number fields.

**Comment by kmmbvnr** [comment]
Yep, unfortunately spin buttons looks ugly in the material interfaceon various platforms under FF.

And this trick to emulate chrome behavior cause bugs with labels in FF
```
input[type=number] {
    -moz-appearance: textfield;
}

input[type=number]:focus {
    -moz-appearance: initial;
}

```

So the spinners was disabled,

But anyway, you can have your own forms.css in the one of STATIC_DIRS folder.
