### ISSUE TITLE
Actions branch- does it have working actions? "dictionary update sequence element" Error

### ISSUE THREAD

**Issue by yarnball** [viewflow/django-material#124]
I have noticed in one of your demo's- that actions and tick boxes are in fact working (yaay!). So I presume that's part of the "actions" branch in this repo? Please confirm

The demo here has it- http://forms.viewflow.io/admin/integration/city/

I have done a pip 
```
pip install git+https://github.com/viewflow/django-material.git@actions
```

It works, but when I enter a model I get the following error- 
"dictionary update sequence element #0 has length 3; 2 is required"

The full error (http://dpaste.com/3DTSYM5).

I've tried with a virtual env in both Python 2.7 & 3.4. Same error in both.

**Comment by kmmbvnr** [comment]
check the latest pip release

**Comment by yarnball** [comment]
The latest pip does not have the admin actions or check boxes? Please confirm whether it is supposed to
