### ISSUE TITLE
replace instances of user.username with user.get_username in templates

### ISSUE THREAD

**Issue by askvictor** [viewflow/django-material#125]
For custom user models (based off AbstractBaseUser), a user name might not have a username attribute. However, all user models must have a get_username() method. So
    
    user.get_full_name|default:user.username

should be replaced with 

    user.get_full_name|default:user.get_username

in material/frontend/templates/material/frontend/base.html  and material/admin/templates/admin/base.html

**Comment by kmmbvnr** [comment]
pull requests are welcome

**Comment by kmmbvnr** [comment]
thanks!
