### ISSUE TITLE
Multple Inlines in Admin  page

### ISSUE THREAD

**Issue by TheSundar** [viewflow/django-material#128]
Can we have multiple Tablur,Stacked inlines in single admin page

**Comment by kmmbvnr** [comment]
Did you try that? It should works

**Comment by kmmbvnr** [comment]
I'm closing thia since it's not a bug. Feel free to  reopen if you found issues with multiple inlines on the same page.

**Comment by TheSundar** [comment]
Thanks for reply,
Yesterday it showed me InlineFormfeildset does not have model object

but today it worked like a charm ! 

Excellent Work ..
