### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by kunambi** [viewflow/django-material#131]
Regarding `Admin - added app and model icons support` there is no (obvious) location where we can read about which icons can be used.

**Comment by kmmbvnr** [comment]
Documentation updated with the 0.9 release.

The admin options documented at  http://docs.viewflow.io/admin_customization.html

**Comment by aidan2129** [comment]
The docs show nothing about a simple way to change the admin theme colours yet most the images show it with different colours is is it just a case of overriding the admin styles.

**Comment by pysysops** [comment]
Themes are documented here in case you didn't find the docs. http://docs.viewflow.io/forms_themes.html

**Comment by aidan2129** [comment]
@pysysops Nice thank you :)
