### ISSUE TITLE
django production - no load material

### ISSUE THREAD

**Issue by lypef** [viewflow/django-material#132]
hola, pase django a produccion pero no me cargan los estilos y los url en mi terminal aparecen en color amarillo. alguien puede ayudarme ?

**Comment by kmmbvnr** [comment]
If you performed all instructions from the documentation page http://docs.viewflow.io/material_forms.html probably you just forget to run `collectstatic` - https://docs.djangoproject.com/en/1.9/howto/static-files/#deployment
