### ISSUE TITLE
drop-down fields from generic.UpdateView not working.

### ISSUE THREAD

**Issue by piyushmaurya23** [viewflow/django-material#134]
have a ForiegnKey field in generic.UpdateView which works as dropdown in template in bootstrap but in django-material, no option came in template.

**Comment by kmmbvnr** [comment]
Did you include material js files? But default materializecss makes selects hiddent, till it reinitialized by js code.

**Comment by piyushmaurya23** [comment]
thankyou, its working now, i have added js file in body. now i corrected it.
