### ISSUE TITLE
Why LOGIN_REDIRECT_URL is overrided from frontend app?

### ISSUE THREAD

**Issue by AliLozano** [viewflow/django-material#135]
I'm using material in a project and my LOGIN_REDIRECT_URL is overrided with '/' in material/frontend/__init__.py when MATERIAL_FRONTEND_AUTOREGISTER = True

Is this behaviour correct, It is necesary?

Thanks a lot.

**Comment by kmmbvnr** [comment]
yep, this probably should be changed
