### ISSUE TITLE
[Documentation] theme color change

### ISSUE THREAD

**Issue by shubham7saxena** [viewflow/django-material#137]
I recently saw a commit enabling the feature to change the theme color. Could you please describe the process to do it asap. better update the documentation. You could also let me know the steps and I'll leave a pull request with the updated documentation.

**Comment by kmmbvnr** [comment]
please take a look to the code,

documentation would be updated at 1.0 release.

Duplicate #131

**Comment by pysysops** [comment]
Themes are documented here in case you didn't find the docs. http://docs.viewflow.io/forms_themes.html
