### ISSUE TITLE
Issue with formwizard rendering.

### ISSUE THREAD

**Issue by wakwanza** [viewflow/django-material#14]
My attempt at integrating with form-wizard for multistep forms is as below
```
{% extends "base.html" %}
{% load material_form %}
{% block content %}
<form  action="" method="post">
    {% csrf_token %}
    {{ wizard.management_form }}
    {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
            {% for form in wizard.form.forms %}
                {% form form=form %}{% endform %}
            {% endfor %}
    {% else %}
        {{ wizard.form }}
    {% endif %}
    <input type="submit" value="Proceed" />
</form>
{% endblock %}
```

with  the base.html as here http://pastebin.com/uUZT40ge . with simple forms such as the one below it works ok : 
```
{% extends "base.html" %}
{% load i18n material_form %}
{% block content %}
<form  action="" method="post">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <input type="submit" value="Proceed" />
</form>
{% endblock %}
```
however with the multiple step displays the first form only and on submit does not proceed to the next step.Without the styling it works as expecting moving step->step through the forms to the final one.

**Comment by kmmbvnr** [comment]
I added the sample, and for me formwizard works well. See the 4607b8e

Could you change  `{{ wizard.form }}` to `{% form form=wizard.form %}{% endform %}`?

Is it fixed your issue?

**Comment by wakwanza** [comment]
thanks that sorted it :+1:  the forms are working as expected now.
