### ISSUE TITLE
Menu.html not working

### ISSUE THREAD

**Issue by alvarosaavedra** [viewflow/django-material#141]
Hi again xD, the module is not detecting the menu.html, any way I could debug this??

**Comment by kmmbvnr** [comment]
You can set breakpoint on appconfig.menu

https://github.com/viewflow/django-material/blob/master/material/frontend/apps.py#L88

https://github.com/viewflow/django-material/blob/master/material/frontend/templates/material/frontend/base.html#L73

When you solved it, can you please list here, what was the problem root.

**Comment by alvarosaavedra** [comment]
@kmmbvnr  so the current_module is not been defined anywhere so the menu is never rendered
