### ISSUE TITLE
Help needed with Inlines in Admin Site using LayoutMixins

### ISSUE THREAD

**Issue by JacoBezuidenhout** [viewflow/django-material#142]
Hi all,

Please help:

Here is my code:

```
from django.contrib import admin
from .models import *
from employments.admin import EmploymentInline, Employee
from exemptions.admin import EmployerExemptionInline
from ownerships.admin import OwnershipInline
from material.base import Layout, Span, Column, Row, Fieldset, LayoutMixin
from material.admin import base
from material.admin.base import Inline


@admin.register(Employer)
class EmployerAdmin(LayoutMixin, admin.ModelAdmin):
    search_fields = ['name']
    layout = Layout(
        Row('name', 'registered_name'),
        Row('type', 'provident_fund'),
        Row('address_work', 'address_post'),
        Row('contact_name', 'telephone_work'),
        Row('telephone_home', 'telephone_cell', 'fax'),
        Row('email', 'commence_date', 'status'),
        Row('employer_organization', 'union'),
        Row('number_of_employees'),
        Row('notes'),
        Inline(EmploymentInline)
    )
    inlines = (EmploymentInline, EmployerExemptionInline, OwnershipInline)
    
    fields = [
        'name',
        'registered_name',
        'type',
        'provident_fund',
        'address_work',
        'address_post',
        'contact_name',
        'telephone_work',
        'telephone_home',
        'telephone_cell',
        'fax',
        'email',
        'employer_organization',
        'commence_date',
        'number_of_employees',
        'union',
        'status',
        'notes'
    ]


@admin.register(EmployerOrganization)
class EmployerOrganizationAdmin(admin.ModelAdmin):
    search_fields = ['name']


@admin.register(Union)
class UnionAdmin(admin.ModelAdmin):
    search_fields = ['name']
```

And then I get this error:

> AttributeError at /employers/employer/add/
'InlineAdminFormSet' object has no attribute 'model'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/employers/employer/add/
Django Version:	1.8
Exception Type:	AttributeError
Exception Value:	
'InlineAdminFormSet' object has no attribute 'model'
Exception Location:	C:\Users\jaco\Envs\bcfood\lib\site-packages\material\admin\templatetags\material_admin.py in fieldset_layout, line 121
Python Executable:	C:\Users\jaco\Envs\bcfood\Scripts\python.exe
Python Version:	2.7.10
Python Path:	
['C:\\code\\BCFoodAdmin',
 'C:\\Users\\jaco\\Envs\\bcfood\\Scripts\\python27.zip',
 'C:\\Users\\jaco\\Envs\\bcfood\\DLLs',
 'C:\\Users\\jaco\\Envs\\bcfood\\lib',
 'C:\\Users\\jaco\\Envs\\bcfood\\lib\\plat-win',
 'C:\\Users\\jaco\\Envs\\bcfood\\lib\\lib-tk',
 'C:\\Users\\jaco\\Envs\\bcfood\\Scripts',
 'C:\\Users\\jaco\\Anaconda\\Lib',
 'C:\\Users\\jaco\\Anaconda\\DLLs',
 'C:\\Users\\jaco\\Anaconda\\Lib\\lib-tk',
 'C:\\Users\\jaco\\Envs\\bcfood',
 'C:\\Users\\jaco\\Envs\\bcfood\\lib\\site-packages']
Server time:	Fri, 1 Jul 2016 15:16:51 +0200

**Comment by kmmbvnr** [comment]
Layout support in the admin is not implemented, and probably will never be.

You can use standard django admin fieldset option https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets

**Comment by JacoBezuidenhout** [comment]
Thank you :)
