### ISSUE TITLE
 Django 1.10 support

### ISSUE THREAD

**Issue by hamotoJohn** [viewflow/django-material#143]
Using the 1.10 beta 1, I get an error while rendering the admin site:
```
Error during template rendering

In template [ ... ]/material/admin/templates/admin/base.html, error at line 1
'future' is not a registered tag library. Must be one of: admin_list admin_modify admin_static admin_urls cache i18n l10n log material_admin material_form material_form_internal pjax_tags static staticfiles tz
1	{% load admin_static material_admin i18n %}{% load firstof from future %}<!DOCTYPE html>
```

Django 1.10 officially deprecates `firstof` in the future tags library.

**Comment by casserlyprogramming** [comment]
Any idea when this commit will become part of the pip package?

**Comment by kmmbvnr** [comment]
I'm quite busy right now on another project. I'm going to release a new version of django-material in a month or two.

**Comment by spiralni** [comment]
I am using django 1.10, any news about it ❓
