### ISSUE TITLE
django admin custom usermodel not accepted

### ISSUE THREAD

**Issue by rajexp** [viewflow/django-material#144]
I have custom user model registered in django settings with username fields replace with mobile_number on using material.admin can't login the login form is looking in mobile_number in username field and throwing key lookup error [traceback](http://dpaste.com/3F5DETA) link for traceback

**Comment by kmmbvnr** [comment]
Duplicate #96

**Comment by rajexp** [comment]
Another solution i come up with is to create a function
`def username(self):
      return self.<_your_username_field>` in the models.py  of your custom user model
