### ISSUE TITLE
UI Bug: Tabular Inline Admin Interface Stacking Default Value on Field Name

### ISSUE THREAD

**Issue by spkuehl** [viewflow/django-material#146]
<img width="880" alt="screen shot 2016-07-13 at 7 42 26 am" src="https://cloud.githubusercontent.com/assets/8636697/16803721/97481422-48cd-11e6-8fce-c363a2289eb0.png">

Image above as evidence. A date model with default value is stacking on the field name. Clicking on the field floats the label upward and reveals the contents.

The issue exists on unsaved, new inlines.

**Comment by kmmbvnr** [comment]
Could you please try git version?

I think 0b2b33e8521146b8a15e42deeada2d5a4ce18296 fix that

**Comment by spkuehl** [comment]
The most recent version I get is 0.8.0 and the issue is unresolved. Your commit addresses the issue exactly so perhaps I am not getting the most recent build, is this the correct way to install from git?

> pip install git+https://github.com/viewflow/django-material.git

I am on Django 1.9.4

**Comment by kmmbvnr** [comment]
yep, `pip install git+https`
