### ISSUE TITLE
Where to define current_module

### ISSUE THREAD

**Issue by alvarosaavedra** [viewflow/django-material#147]
Ok so the menu is not been show becouse current_module is blank, do youy have a mixin??? or other thing I missing???

**Comment by kmmbvnr** [comment]
I recently upgraded the frontend quick start sample - https://github.com/viewflow/cookbook/tree/master/frontend_quickstart

Please follow the documentation.

probably you didn't listed your module in INSTALLED_APPS setting or in <app>/__init__.py `default_app_config `

Yu can also take a look to the django apps system documentation - https://docs.djangoproject.com/es/1.9/ref/applications/

**Comment by TobinFrost** [comment]
Hello guys, i think i have the same issue :
**Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable.**
how can i fix it ?

**Comment by MScMechatronics** [comment]
I also have the error. Would appreciate any help to resolve this. 
Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable.

**Comment by kmmbvnr** [comment]
django-material v1.x templates works only for views included with frontend.urls, that establishes current_module variable

**Comment by MScMechatronics** [comment]
Thanks, I just solved it. I did not have url for frontend in the root url config file. I added below code in the root urls.py file which then solved my problem.
urlpatterns = [
    url(r'^$', generic.RedirectView.as_view(url='/workflow/', permanent=False)),
    url(r'', include(frontend_urls)),
