### ISSUE TITLE
Multiple admin modules support

### ISSUE THREAD

**Issue by sysint64** [viewflow/django-material#148]
I have two custom admin modules, how can I apply material admin for both of them?

**Comment by kmmbvnr** [comment]
Do you have problems with it?

**Comment by sysint64** [comment]
If I set `MATERIAL_ADMIN_SITE = 'admin.lowerlevel_admin.lowerlevel_admin'` admin work fine else I get an error: `'app_list' with arguments '()' and keyword arguments '{'app_label': 'auth'}' not found. 1 pattern(s) tried: ['admin/(?P<app_label>filer|ads|news|articles|cities)/$']`

**Comment by kmmbvnr** [comment]
`MATERIAL_ADMIN_SITE` site settings is for standard `admin.site` replacement.

I didn't test django-material with custom admin sites.

**Comment by sysint64** [comment]
ok, no problem.

**Comment by kmmbvnr** [comment]
Generally, i don't think that ability to have 2 admin modules at the same website is so required, so `wontfix`, but pull requests still welcome, if anyone would like to fix that.

**Comment by sysint64** [comment]
I fixed this, but this is not general solution. I redefine MaterialAdmin and each of my admin inherit from this admin. In MaterialAdmin has get_app_list method because that does not work. And make some fixes with templates. Maybe later I try make common solution for this.

**Comment by kmmbvnr** [comment]
Since django 1.9 there is `available_apps` variable available on each admin page

https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.AdminSite.each_context

`get_app_list` template tag need to be used only for django 1.8, for the rest of all Django's, it's the possibility to build multiple admin modules support in a generic way

**Comment by brianhhq** [comment]
Hopefully django material can support multiple admin site

**Comment by kmmbvnr** [comment]
Closed due #373
