### ISSUE TITLE
Material Desing Version?

### ISSUE THREAD

**Issue by Bernardoow** [viewflow/django-material#149]
HI Team!!

Incredible project. I like a lot!!!
About css, where is it is based ?

https://design.google.com/? 
https://getmdl.io/?

And I want to contribute to the project . What can I do?

**Comment by kmmbvnr** [comment]
Hi, Bernando

The project is based on http://materializecss.com/

Thanks for wanting to contribute. 

Can you try to implement this easy picking issue? 

https://github.com/viewflow/django-material/issues/122
