### ISSUE TITLE
run cmd "manage.py collectstatic",  Is this bug?

### ISSUE THREAD

**Issue by springleng** [viewflow/django-material#150]
my env:
===============
> python -V
Python 3.5.2
> pip freeze
Django==1.10rc1
> git clone git@github.com:viewflow/django-material.git
> cd django-material
> python setup.py install

> ./manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /Users/silen/Development/python/myshop/src/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Found another file with the destination path 'admin/js/jquery.init.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/prepopulate.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/SelectFilter2.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/admin/DateTimeShortcuts.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/admin/RelatedObjectLookups.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

0 static files copied to '/Users/silen/Development/python/myshop/src/static', 117 unmodified.

**Comment by kmmbvnr** [comment]
That's common problem for django admin themes project, caused by django recently.

Read this - https://github.com/sehmaschine/django-grappelli/issues/751

**Comment by springleng** [comment]
thanks
