### ISSUE TITLE
form field's value escaped

### ISSUE THREAD

**Issue by dcale** [viewflow/django-material#156]
There's a bug in the form template, whenever you want to update a previously populated model field that contained a special character, the next time you save it will save the escaped version over and over again.

Example:
1. I populate CharField manually with "Tom & Jerry".
2. I save this -> the value in the DB is actually "Tom & Jerry".
3. I reopen the same entity and will see that the prepopulated value now is "Tom & amp; Jerry". 
4. I save this -> the value in the DB is actually "Tom & amp; Jerry".

This is a problem because:
1. everytime I want to update another field of my model I'd have to replace manually "&amp;" with "&" before saving (even though I did not intend to touch that field).
2. If I don't replace the escaped sequence, for every update the whole thing grows (since & is included in the escaped version -> & amp; -> && amp;& amp; -> ...

For the django admin this does not seem to be an issue, they don't escape the value (they do escape the quotes used inside the value attribute.)

**Comment by dcale** [comment]
I added spaces before amp because otherwise github renders it and you can;t see the difference...

**Comment by kmmbvnr** [comment]
Already fixed. Try - http://forms.viewflow.io/demo/widget/char/
