### ISSUE TITLE
Replacing form fields

### ISSUE THREAD

**Issue by alonecoder1337** [viewflow/django-material#161]
I just defined a form as follows

address = forms.CharField(widget=FroalaEditor,max_length=65536,label="Option Text", required=False)

it using material's text area widget instead of  froalaeditor widget,

**Comment by kmmbvnr** [comment]
Yes, this is intended behavior. django-material use tempaltes to render widgets according to widget __mro_ class hierarchy. You can define `material/<yourtoppackage>_floalaeditor.html` template to provide a custom rendering for your widget.

See [_get_field_template](https://github.com/viewflow/django-material/blob/master/material/base.py#L54) for logic details.
