### ISSUE TITLE
TypeError: $(...).formset is not a function

### ISSUE THREAD

**Issue by alonecoder1337** [viewflow/django-material#162]
TypeError: $(...).formset is not a function while loading form

Something went wrong  in material/static/material/material_init.js
   
    $('.formset-field').formset({
        animateForms: true,
        newFormCallback: material_init
    });

**Comment by kmmbvnr** [comment]
You missed to include `<script src="{% static 'material/js/jquery.formset.js' %}"></script>`

**Comment by alonecoder1337** [comment]
>         {% block js %}
>         <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
>         <script src="{% static 'material/js/materialize.js' %}"></script>
>         <script src="{% static 'material/js/jquery.datetimepicker.js' %}"></script>
>         <script src="{% static 'material/js/jquery.formset.js' %}"></script>
>         <script src="{% static 'material/frontend/js/jquery.activeNavigation.js' %}"></script>
>         <script src="{% static 'material/frontend/js/jquery.pjax.js' %}"></script>
>         <script src="{% static 'material/js/material_init.js' %}"></script>
>         <script src="{% static 'material/frontend/js/frontend.js' %}"></script>
>         {% endblock %}
> 

and  i added custom widget and it's working fine, but the problem is dateinputfield isnt working and it showing the below error 

> 
> $('.formset-field').formset({
>     animateForms: true,
>     newFormCallback: material_init
> });
