### ISSUE TITLE
[admin] custom user (without username) is not supported 

### ISSUE THREAD

**Issue by truhlik** [viewflow/django-material#164]
Hello,

I have a problem with material.admin ... all requests to Django admin raise error:
**Error:** VariableDoesNotExist
**Exception Value:** Failed lookup for key [username] in u'Custom User object'

My CustomUser model doesn't have any "username" field
`    first_name = models.CharField(_(u'Jméno'), max_length=64)
    last_name = models.CharField(_(u'Příjmení'), max_length=64)
    email = models.EmailField(_(u'Email'), unique=True, db_index=True)
    user_type = models.PositiveSmallIntegerField(_(u'Typ uživatele'), choices=USER_TYPE_CHOICES, default=1)
    phone = PhoneNumberField(verbose_name=_(u'Telefon'), blank=True, null=True)
    # company fields
    company_name = models.CharField(_(u'Název firmy'), blank=True, null=True, max_length=255)
    vat_number = models.CharField(_(u'IČO'), max_length=16, blank=True, null=True)
    tax_number = models.CharField(_(u'DIČ'), max_length=16, blank=True, null=True)
    # admin stuff
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False, help_text=u'Designates whether the user can log into this admin site.')
    date_joined = models.DateTimeField(auto_now_add=True)`

**Full stack trace:**
http://dpaste.com/1XZVH4B

**Comment by kmmbvnr** [comment]
Duplicae #96
