### ISSUE TITLE
Django 1.10-  'future' is not a registered tag library

### ISSUE THREAD

**Issue by yarnball** [viewflow/django-material#165]
Hi,

Not sure if 1.10 is compatible yet, but I noticed the demo folder in the latest commit mentions 1.10.

After upgrading to 1.10, I receive the following error:

``In template /Users/mac1/Dev/MeMail/2vennv/lib/python2.7/site-packages/material/admin/templates/admin/base.html, error at line 1
   'future' is not a registered tag library``

This is the full error:

http://dpaste.com/1Q4RSVT

**Comment by kmmbvnr** [comment]
fixed in master. Duplicate #143
