### ISSUE TITLE
Localization of date/time pickers

### ISSUE THREAD

**Issue by mattiagalati** [viewflow/django-material#166]
Is there a way to localize all datetimepickers (both formats and month names) to my language?

**Comment by kmmbvnr** [comment]
Yeah. Datetimepicker localization not in material_ibit.js yet.

You need to call jQuery.datetimepicker.setLocale('de');


http://xdsoft.net/jqplugins/datetimepicker/

**Comment by mattiagalati** [comment]
Let's say I want to change the default language for each picker created for the platform. Where I am supposed to use that notation?
Plus, the code you provided returns me:
`Uncaught TypeError: Cannot read property 'setLocale' of undefined`

**Comment by kmmbvnr** [comment]
I'm sorry I have no time to provide comprehensive answer.

I point you to the documentation for datetimepicker. Please take a time to investigate it.

Definitely django-material should have support for datetimepicker localization out of the box. Pull requests are welcome

**Comment by mattiagalati** [comment]
I've inspected the source of
django-material/material/static/material/js/jquery.datetimepicker.js and there is no trace of method "setLocale": "setLocale" was added in version 2.4.5 (or near Sept 2015) and django-material uses version 2.3.8.
Long story short, to correctly set the default locale, use this:
`jQuery.fn.datetimepicker.defaults['lang'] = 'de';`
