### ISSUE TITLE
Adding script tag during widget rendering disappear

### ISSUE THREAD

**Issue by talbenbasat** [viewflow/django-material#167]
Hi,

i'm trying to integrate django-smart-selects with a django-material app i'm building.
It appear to not integrate well, but i'm trying to solve it anyways.

Apparently there are 2 problems:
1. script tags are stripped from the widget after rendering.
2. args and kwargs doesnt transfer well during widget render time
material_admin.py, 294
'widget': rel_widget.widget.render(bound_field.name, bound_field.value())

vs

widgets.py 292 (plain django)
'widget': self.widget.render(name, value, *args, **kwargs),

Can you please help

**Comment by kmmbvnr** [comment]
Sorry. I. Have no times to working on this
