### ISSUE TITLE
Support for custom html in  admin readonly fields 

### ISSUE THREAD

**Issue by joda** [viewflow/django-material#168]
Hi,

I'd like to show a thumbnail image on the change page according to [this](http://stackoverflow.com/questions/16307307/django-admin-show-image-from-imagefield).

However, the way [django_adminreadonlyfield.html](https://github.com/viewflow/django-material/blob/0.8.0/material/admin/templates/material/fields/django_adminreadonlyfield.html) is implemented right now prevents me from doing this. Is there a way for me to solve this while keeping the current intention?

1. What is the reason for putting `fieldset_field.contents` inside an input which is disabled? 
1. What's the rationale for outputting a checkbox if `'<img' in fieldset_field.contents` is true?

I'd love to provide a pull request if I understand the reasons for the current logic.

**Comment by joda** [comment]
Thanks for your response!

Well, it does work in django-admin. Given the following model

``` 
class MyModel(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField()

    def image_tag(self):
        return format_html('<img src="%s" width="42" height="42" />' % (self.image.url))
    
    image_tag.short_description = 'An image'
```
and this admin:

```
class MyModelAdmin(admin.ModelAdmin):
  model = MyModel
  fields = ( 'name', 'image', 'image_tag')
  readonly_fields = ('image_tag',)

  list_display= ['name', 'image', 'image_tag']

admin.site.register(MyModel, MyModelAdmin)
```
I get the following on the change page:

<img width="519" alt="screen shot 2016-09-06 at 09 09 52" src="https://cloud.githubusercontent.com/assets/11804/18264706/308aba12-7412-11e6-8baf-9d4c777aaa4b.png">

Is there a way I can get the same result using django-material?

**Comment by kmmbvnr** [comment]
Hm, yep, you a right.

Maybe we could have a custom filter `|issafe` to test a field value. And only if value is not safe output them inside `input` tag, otherwise show them as is. Assuming that safe values could contain html content.

**Comment by joda** [comment]
Would you still like to have checkboxes for boolean readonly fields as it is now?

Also, is `|issafe` needed, or should the application itself be responsible for producing safe html? I'm new to django so not really sure where to put that responsibility.

**Comment by kmmbvnr** [comment]
https://github.com/viewflow/django-material/commit/31f7a17483b34d1863a20269df71826c468d9cd9 fix for readonly fields in stacked and tabular inlines
