### ISSUE TITLE
django-admin field is hidden in change list

### ISSUE THREAD

**Issue by daadu** [viewflow/django-material#170]
models.py:

```
class Otp(models.Model):
    country_code = models.CharField(max_length=2)
    mobile_number = models.CharField(max_length=10)
    otp = models.CharField(max_length=6)
    used = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s-%s" % (self.mobile_number, self.otp)

    @classmethod
    def generate_otp(cls):
        return "%d" % randint(100000, 999999)
```

admin.py:
```

class OtpAdmin(admin.ModelAdmin):
    search_fields = ['mobile_number']
    list_filter = ['used']
    date_hierarchy = "created_at"
    list_display = ['country_code', 'mobile_number', 'otp', 'used']
    readonly_fields = ["country_code", 'mobile_number', 'otp', 'used']
```

![screenshot from 2016-09-15 07-01-39](https://cloud.githubusercontent.com/assets/4963236/18535493/4ef97fc2-7b12-11e6-9d38-5a94a6cd2bb5.png)

as you can see the field is hidden.

what is the issure? how can i fix it?

**Comment by kmmbvnr** [comment]
It's not the issue. The table is to long to fit into your screens. That's behaviour of the respondive datatable.

**Comment by daadu** [comment]
I tried with:

`list_display = ['mobile_number']`

still the problem remains.
note: the max_lenght of that field is 10

**Comment by daadu** [comment]
It works in mobile view though:

![image](https://cloud.githubusercontent.com/assets/4963236/18536019/d8b0a41c-7b16-11e6-9edf-7e951051131f.png)
