### ISSUE TITLE
What happens to the various tools in django-admin

### ISSUE THREAD

**Issue by daadu** [viewflow/django-material#171]
I just tried using django-material for my admin panel.

Wanted to know what happens to the tool [like export in the image below]:
![image](https://cloud.githubusercontent.com/assets/4963236/18536148/1b4b79f4-7b18-11e6-9a29-132f9e87a56a.png)

I just noticed after switching to django-material that option disappeared.

**Comment by daadu** [comment]
export is used to export the database to various format such as: .csv .xls 

using this : [](https://django-import-export.readthedocs.io/en/latest/)

**Comment by kmmbvnr** [comment]
3d party addons have no support for django-material
