### ISSUE TITLE
pip version unusable as is

### ISSUE THREAD

**Issue by MrLinio** [viewflow/django-material#172]
Hi.

I don't know what your update policy is, but the pip referenced version is totally unusable, the trailing spaces in the includes causing the forms to be totally broken. I see this problem is resolved in your git repository, but this is not a minor bug, the pip version hasn't been updated since a while.

**Comment by kmmbvnr** [comment]
yeah, yeah. Something working need to be done for the next release

**Comment by hermanocabral** [comment]
any chance we can get an ETA on this? I'm evaluating using this for a big project and had to downgrade to 0.7.0 to properly test the admin site.

**Comment by MrLinio** [comment]
Apparently it's not that big of a deal ...

You could also directly get the working version from this repository...

**Comment by hermanocabral** [comment]
Yeah, a broken package on PyPI *is* a big deal, and the current master also seems to be broken. I'm using v0.7.0 to test and so far I really like this project, but it doesn't seem mature enough to use in production.
