### ISSUE TITLE
installation not recognised by python2.7

### ISSUE THREAD

**Issue by sahalsajjad** [viewflow/django-material#175]
When run by python3.4 it works fine, python2.7 gives Import Error: No module named 'material'

**Comment by kmmbvnr** [comment]
What command you use to install django-material?

**Comment by koopauy** [comment]
pip install django-material

**Comment by kmmbvnr** [comment]
Can't reproduce

```
$ virtualenv --python=python2.7 venv
$ ./venv/bin/pip install django-material django
$ ./venv/bin/python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import material
>>> import material.admin
>>>     

```

**Comment by koopauy** [comment]
You must activate the virtualenv like: 'source ./venv/bin/activate && pip install django-material'

**Comment by ThunderTrent** [comment]
I can verify that this is an issue on 2.7 without virtualenv.

**Comment by kmmbvnr** [comment]
Guys, you need to provide more info, how to reproduce the issue.

**Comment by ThunderTrent** [comment]
From Ubuntu 14.04 python 2.7 installed, literally trying to pip install django-material without a virtualenv installed. For small projects on standalone servers, people don't use virtualenvs.

**Comment by kmmbvnr** [comment]
@ThunderTrent when I'm asking about steps to reproduce, I've expected the exact list of commands how you are trying to install and verify the issue. 

I tried ubuntu 14.04 on vagrant and still everything works fine.

```
$ vagrant init ubuntu/trusty64
$ vagrant up && vagrant ssh
$ sudo apt-get update && sudo apt-get install apt-get install python-pip
$ python --version 
Python 2.7.6
$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
$ sudo pip install django django-material
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import material
>>> import material.admin

```

I'm locking the issue if anyone else experiences it, please send the pull request with a fix.
