### ISSUE TITLE
WYSIWYG Editor support

### ISSUE THREAD

**Issue by rewrz** [viewflow/django-material#176]
I use TinyMCE, but it not working after I install django-material.
Is it not support WYSIWYG Editor?

**Comment by kmmbvnr** [comment]
3d party packages are not supported

**Comment by kmmbvnr** [comment]
Medium editor going to be added to the PRO version

https://github.com/yabwe/medium-editor

**Comment by madEng84** [comment]
News on this Issue? @kmmbvnr 
Thanks in advance

**Comment by iMerica** [comment]
I've forked django-material with a goal of making it more friendly to third party packages in the Django ecosystem. If anyone is  interested in collaborating, the repo is [here](https://github.com/iMerica/django-material).

**Comment by tuxredux** [comment]
@madEng84 If you're looking for a hack, you can override templates to achieve a JavaScript solution:

Add `id="id_{{ bound_field.html_name }}_label"` to `<label>` in `material/fields/django_textarea.html`.

Add the snippet below to `admin/base_site.html`. Now all `<textarea>` fields named 'content' will be tinymce wysiwyg!
```html
{% block extrahead %}{{ block.super }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.6.4/tinymce.min.js" integrity="sha256-GWG+bvCeaNtPK93q+Xekg1JgEApGqFWPTnWxBuT8wwY=" crossorigin="anonymous"></script>
<script>tinymce.init({
    selector: '#id_content',
    plugins: [
      'advlist autolink lists link image charmap print preview hr anchor pagebreak',
      'searchreplace wordcount visualblocks visualchars code fullscreen',
      'insertdatetime media nonbreaking save table contextmenu directionality',
      'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
    ],
    toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
    toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
    image_advtab: true,
    forced_root_block: false
});</script>
<style>#id_content_label{display:none;}</style>
{% endblock extrahead %}
```

**Caveat:** The tinymce editor will have default styling. The medium editor in the PRO version will look MUCH better!

**Comment by christianbos** [comment]
@kmmbvnr Medium Editor is now available in a pro version?

**Comment by madEng84** [comment]
Medium editor browser support is a big limit.

However i found a more clean solution to use ckeditor, without forcing all textarea to use it

Thanks

**Comment by christianbos** [comment]
how did you do it?

**Comment by madEng84** [comment]
@christianbos 
You can see the html widget here:
https://github.com/viewflow/django-material/compare/master...madEng84:master#diff-e98101ab4314841c390c49ec0374fdf3

You have to install ckeditor by pip and override formfield_for_db_field in your admin to set the CKEditorWidget as your TextField widget

**Comment by christianbos** [comment]
thanks! @madEng84

**Comment by melvyn-sopacua** [comment]
The solution for ckeditor is much simpler.

Create `material/fields/ckeditor_ckeditorwidget.html` in your templates directory. Use the following code:

```html
{% load material_form material_form_internal %}
{% part bound_field.field %}
	<div class="row">
		<div{% attrs bound_field 'group' %}
			id="id_{{ bound_field.html_name }}_container"
			class="input-field col s12{% if field.required %} required{% endif %}{% if bound_field.errors %} has-error{% endif %}"
		{% endattrs %}>
			<div class="section">
				{% part field prefix %}{% endpart %}
				{% part field label %}
					<label{% attrs bound_field 'label' %}
						for="{{ bound_field.id_for_label }}"
						{% if bound_field.value %}class="active"{% endif %}
					{% endattrs %}>{{ bound_field.label }}</label>
				{% endpart %}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col s12">
			<div class="section">
				{% part field control %}
					{{ bound_field }}
				{% endpart %}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col s12">
			{% part field help_text %}{% if field.help_text %}
				<div class="help-block">{{ bound_field.help_text|safe }}</div>
			{% endif %}
			{% endpart %}{% part field errors %}
				{% if bound_field.errors %}
					{% include  'material/field_errors.html' %}
				{% endif %}
			{% endpart %}{{ hidden_initial }}
		</div>
	</div>
{% endpart %}
```

The extra layout is simply to offset the label and help text, but could probably be handled through customized css as well.
This will effectively use ckeditor for all fields marked as RichTextField, but not TextArea, leaving you with both options.

The clue to this is in `material.base._get_field_template`. It provides a number of candidates for both widget and field rendering templates in order of preference and returns the first one that exists.

**Comment by mathpaquette** [comment]
@melvyn-sopacua  question for you... I have a weird issue regarding your solution. The ckeditor is appearing only on a full refresh (F5) on the form. When I navigate through the menus, let's say I create a new process, when I land to the form with a ckeditor field the editor doesn't get initialized. I think this is related with javascript but just wanted to know if you already experienced that? Thank you very much!

**Comment by mathpaquette** [comment]
Anyone has the same issue I have? I confirm this is a javascript problem... If I do something like window.CKEDITOR.RemoveAll() this reinit the editor fields and it shows up....

**Comment by nathanurwin** [comment]
Hey @mathpaquette :wave: 

If you can't figure out that solution, I'm using CKEditor as well with a modified version of the solution I posted above. It consists of installing [django-ckeditor](https://github.com/django-ckeditor/django-ckeditor), using the [CKEditor Builder](https://ckeditor.com/cke4/builder) and installing the static assets to your `STATICFILES_DIRS`, and modifying your `TEMPLATES/admin/base_site.html` template:

```
<script src="{% static 'ckeditor/ckeditor.js' %}"></script>

<script>if (document.getElementById('id_')) { CKEDITOR.replace('id_', {

  customConfig: '{% static "ckeditor/build-config.js" %}',
  filebrowserBrowseUrl: '{% url "ckeditor_browse" %}',
  filebrowserUploadUrl: '{% url "ckeditor_upload" %}'
}); }</script>
```

Add the model field name to the `id_` in the `document.getElementById` line, so a `content = models.TextField()` would be `id_content`. Good luck! :+1:

**Comment by mathpaquette** [comment]
@nathanurwin  @melvyn-sopacua finally managed the problem with a not very clean workaround...
Since some forms are generated using materialize, some pages aren't fully generated server-side. So, I need to hook after XHR request and make sure that all fields get replaced. So, I finished with something like this! 

```
(function() {
    var origOpen = XMLHttpRequest.prototype.open;
    XMLHttpRequest.prototype.open = function() {
        this.addEventListener('load', function() {
            setTimeout(function(){
               CKEDITOR.replaceAll();
            }, 100);
        });
        origOpen.apply(this, arguments);
    };
})();
```

Thank you all for your clues.

**Comment by kmmbvnr** [comment]
Added to the PRO version, but generally seems new webcomponent based js allows easily to embed any editor on yuor choice http://docs.viewflow.io/material_frontend.html#custom-components

```
class OceanViewSet(ModelViewSet):
    model = models.Ocean
    form_widgets = {
        'description': MediumEditorWidget(
            options={
                'targetBlank': True,
                'toolbar': {
                    'buttons': ['h1', 'h2', 'h3', 'bold', 'italic', 'quote'],
                },
                'placeholder': {'text': 'Click to edit'}
            },
        )
    }
```

![crud sample material frontend](https://user-images.githubusercontent.com/282529/52337380-a74b3a00-2a31-11e9-9a56-1f747af8f484.png)
