### ISSUE TITLE
Admin save_on_top support

### ISSUE THREAD

**Issue by kmmbvnr** [viewflow/django-material#178]
Form-Title could be push-pinned, Save actions could be placed under dropdown menu in the form title row.

![change continent django site admin](https://cloud.githubusercontent.com/assets/282529/19213520/260ac392-8d90-11e6-990d-c3b26e2e494a.png)

**Comment by pedro-valentim** [comment]
is it still not implemented?

**Comment by kmmbvnr** [comment]
Pull requests are welcome. I'm not going to implement that in near fiture

**Comment by nyejon** [comment]
Hi,

I have made a small work around which isn't ideal, but works quite well for the save on top option.

With save on top it looks like this:

![image](https://user-images.githubusercontent.com/17871768/31494277-df974774-af52-11e7-961b-cee4c32587fc.png)

Would this be satisfactory?

**Comment by kmmbvnr** [comment]
Closed due #373
