### ISSUE TITLE
CheckboxSelectMultiple not displaying checkboxes

### ISSUE THREAD

**Issue by vjFaLk** [viewflow/django-material#18]
I'm using a ModelForm, my 'Person' model has a ManyToMany relationship with 'Problem' and I've set the form to show checkboxes as so

```python
class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        exclude = ('',)
        widgets = {
            'problems': forms.CheckboxSelectMultiple(),
        }
```

But it doesn't show checkboxes with Material Form, instead it shows a MultipleSelect
![With Material](https://i.stack.imgur.com/N1YHG.png)

Removing the Material template shows up the checkboxes
![Without Material](https://i.stack.imgur.com/GRO6E.png)

**Comment by kmmbvnr** [comment]
templates/material/fields/django_checkboxselectmultiple.html need to be added

**Comment by vjFaLk** [comment]
Could you suggest an alternative solution to implementing Material checkboxes for now?

**Comment by kmmbvnr** [comment]
I don't understand why implementing template for material design requires some another alternative )

**Comment by vjFaLk** [comment]
I guess I didn't phrase that properly, I was asking how I could show material styled Checkboxes manually using a loop or something and put them somewhere in the existing form. I'm fairly new at Django. I know this isn't the best place to ask this, sorry.

**Comment by kmmbvnr** [comment]
You have to look to existing templates and implement similar or wait for few month till django-material will be finished.

**Comment by vjFaLk** [comment]
I see, thanks for the help!

**Comment by kmmbvnr** [comment]
Actually django-material allows to do things like

    {% form %}
         {% part form.problems %}
                 
         {% endpart %}
    {% endform %}

so you can hard-code any html that you need for specific field

**Comment by vjFaLk** [comment]
Yeah, that's what I was looking at as well. Looping through the values doesn't seem to generate the right code, it creates the "input" tags inside the "labels" which doesn't render properly. I'll just have to manually code the checkboxes

**Comment by kmmbvnr** [comment]
Fixed  - https://github.com/viewflow/django-material/blob/master/material/templates/material/fields/django_checkboxselectmultiple.html

**Comment by vjFaLk** [comment]
Thank you!
