### ISSUE TITLE
Support for Materialize CSS v0.97.7

### ISSUE THREAD

**Issue by MrLinio** [viewflow/django-material#180]
Could it be possible to add support for the new version of Materialize CSS?

There are a few nice additions in this version, namely the autocomplete bit that could answer previous issues with integration of third parties plugins.

**Comment by kmmbvnr** [comment]
Django-material build on top of 0.9.96

0.9.97 contaims a lot of bugs

I suppose i'll update django-material to 0.9.98 when it could be released.

**Comment by kmmbvnr** [comment]
btw, the latest materializecss support just merged into the master branch
