### ISSUE TITLE
Change the branding icon

### ISSUE THREAD

**Issue by pixelead0** [viewflow/django-material#184]
¿Can I change the branding icon from the settings.py?
I have a custom logo.

![captura de pantalla de 2016-10-20 23 35 06](https://cloud.githubusercontent.com/assets/735873/19586749/f0c1cbf8-971d-11e6-9536-35b61c2d5693.png)

**Comment by kmmbvnr** [comment]
There is no way to do that using settings.py

You need to override block branding in base_site template

**Comment by pixelead0** [comment]
I can changed the branding icon.

I defined the site_header and site_title into urls.py and I changed the block branding into   /material/admin/templates/admin/base_site.html

```
# file: urls.py

# Change admin site title
admin.site.site_header = '<img class="responsive-img" src="/static/material/imgs/logo.png">'
admin.site.site_title = _("My Site Admin")
```

```
# File:  /material/admin/templates/admin/base_site.html
{% block branding %}{{ site_header|safe|default:_('<i class="material-icons" style="font-size:80px">settings_applications</i>') }}{% endblock %}
```
