### ISSUE TITLE
Django admin readonly_fields not working

### ISSUE THREAD

**Issue by markkohdev** [viewflow/django-material#187]
In my Django ModelAdmin, if I specify readonly_fields then the fields stop populating their inputs in the detail page.  When I remove those fields from the `readonly_fields` list, they populate like normal.  When I switch from django-material to standard django theme, the fields show up when they are declared as readonly.

Here's screenshots of the various cases

Django-material, fields specified as `readonly` (this is the broken scenario)
![image](https://cloud.githubusercontent.com/assets/1663379/19738938/3029276a-9b87-11e6-9cd9-cdac053c2bfc.png)

Django-material, fields NOT specified as `readonly`
![image](https://cloud.githubusercontent.com/assets/1663379/19739423/d9f41e98-9b88-11e6-93fb-c4c81b6e2778.png)

Django standard admin, fields specified as `readonly`
![image](https://cloud.githubusercontent.com/assets/1663379/19739596/8fc31878-9b89-11e6-99f5-e907990fcf7d.png)

Here's the model specification
```python
class Data(BaseModel):
    # Crawler attributes

    # These three fields combined specify a tableset
    project_id = models.CharField(max_length=200)
    dataset_id = models.CharField(max_length=200)
    table_base = models.CharField(max_length=1000)

    table_id = models.CharField(max_length=200)
    link = models.CharField('BigQuery Link', max_length=500)
    bq_description = models.TextField(max_length=1000, blank=True, default='')
    num_partitions = models.IntegerField()
    num_rows = models.IntegerField()
    date_modified_by_bq = models.DateTimeField('Last Crawled', null=True)
```

And the ModelAdmin read_only definition
```python
    readonly_fields = ['project_id',
                       'dataset_id',
                       'table_base',
                       'link',
                       'date_modified_by_curator',
                       'date_modified_by_bq',
                       'bq_description',
                       'num_partitions',
                       ]
```

I'm using django-material 0.9.1 with django 1.10.2
I'm fairly confident that this is a bug.  Please help me fix it!

**Comment by markkohdev** [comment]
It looks like this caused the breakage - https://github.com/viewflow/django-material/commit/04ae12d4066efd3022b68c9535147a4444e39c6b#diff-e69783835aed26c42f263123d796e83e.  
Rolling back this change fixes the issue.

**Comment by markkohdev** [comment]
Ahh, found the issue.  
`fieldset_field.contents` got changed to `field.contents` here https://github.com/viewflow/django-material/blob/master/material/admin/templates/material/fields/django_adminreadonlyfield.html#L15 and broke the things
Will make a PR :)

**Comment by kmmbvnr** [comment]
Thanks for the fix!

That happens even with demo   http://forms.viewflow.io/admin/integration/continent/Australia/

**Comment by kmmbvnr** [comment]
I pushed 0.9.2 with the fix to the PyPI
