### ISSUE TITLE
Imported Form CSS Overwrites Default Site CSS

### ISSUE THREAD

**Issue by alexadkins** [viewflow/django-material#189]
Question: Is this a desired behavior? 

In my base.html template I have:

`{% include 'material/includes/material_css.html' %}`
`{% include 'material/includes/material_js.html' %}`

and I load the `{% load material_form %}`library in the desired page with my form, and render my form with 

`{% form form=form %}{% endform %}`

but the CSS for my entire site is being overwritten by materialize.css. I doubt this is desired behavior and assume the CSS should only load for the form. I've tried loading the CSS only on the form page, but it's proving difficult there as well, as my form is a bootstrap modal overlay of a different page on my site. Am I loading something wrong?

Thanks

**Comment by kmmbvnr** [comment]
Yes,that's desired behaviour.

**Comment by kmmbvnr** [comment]
It looks possible to build stripped down MaterializeCSS version only for forms

Forms related parts need to be hand-picked from:

https://github.com/Dogfalo/materialize/tree/master/js
https://github.com/Dogfalo/materialize/tree/master/sass/components

I'm just not sure that it's the thing that everybody needs.

Django-Material is for sites designed with Google Material Design and MaterializeCSS. Mixing different frameworks on the same web page does not look like a good idea.

If anyone would like to see django-material to be compatible with other CSS frameworks, please leave a comment here. I'm thinking about to implement tht feature in a some day.

See also #104

**Comment by alexadkins** [comment]
Thanks for the response, I couldn't remember seeing anything about incompatibility with Bootstrap in the documentation. I ended up loading a separate template with the needed CSS from an iframe, and that worked just fine.

**Comment by an0o0nym** [comment]
@kmmbvnr I would love to see this feature if you are still up to for implementing it.

**Comment by goromachine** [comment]
I would love to see this feature too if possible to implement it.
