### ISSUE TITLE
 raw_id_fields popup is not returning a pk

### ISSUE THREAD

**Issue by pixelead0** [viewflow/django-material#190]
I'm using  raw_id_fields, when I clicking in the icon search a new window displays a list of all sublines, when selecting an option opens the edition shown, but doesn't return the id to the previous screen.

How I can do to return the ID to the previous screen?

![captura de pantalla de 2016-11-02 17 59 29](https://cloud.githubusercontent.com/assets/735873/19953072/c128ca56-a12f-11e6-824d-9ff5fcdf218d.png)
![captura de pantalla de 2016-11-02 17 59 44](https://cloud.githubusercontent.com/assets/735873/19953078/c8fc2f02-a12f-11e6-8e81-3d72969f7af8.png)
![captura de pantalla de 2016-11-02 18 02 55](https://cloud.githubusercontent.com/assets/735873/19953082/d64556fc-a12f-11e6-8e6b-99cf12e91e6a.png)

![captura de pantalla de 2016-11-02 20 20 16](https://cloud.githubusercontent.com/assets/735873/19954030/d140f5ee-a139-11e6-8895-e57047b29078.png)

`models.py`

```python
class Line(models.Model):
    """Model for Lines """
    name = models.CharField(max_length=512)
    category = models.ForeignKey(Category,  related_name='lines', blank=False, null=False)

    class Meta:
        unique_together = ('name', 'category' )
        ordering = ['name']

    def __unicode__(self):
        return self.name

class Subline(models.Model):
    """Model for Sublines """
    name = models.CharField(max_length=512)
    line = models.ForeignKey(Line,  related_name='sublines', blank=False, null=False)

    class Meta:
        unique_together = ('name', 'line' )
        ordering = ['name']

    def __unicode__(self):
        return self.name
```

`admin.py`
```python
@admin.register(models.Line)
class LineAdmin(admin.ModelAdmin):
    icon = '<i class="material-icons">flag</i>'
    list_display = ('category','name')
    list_display_links = ('category',)
    list_filter = ('category','name' )

    list_select_related = ('category', )
    search_fields = ('name',)

@admin.register(models.Subline)
class SublineAdmin(admin.ModelAdmin):
    icon = '<i class="material-icons">flag</i>'
    list_display = ( 'line','name',)
    list_filter = ('line','line__category',)
    search_fields = ('name',)

    raw_id_fields = ('line',)
```

**Comment by kmmbvnr** [comment]
Can you reproduce the issue here - http://forms.viewflow.io/admin/integration/city/ ?

What browser / django version / django-material version do you use?

**Comment by pixelead0** [comment]
1. I'm trying with models & admin for country and city, its same problem.
2. Yes.
3. Firefox 49.0 / python 2.7.12 / django 1.10.3 / django-material 0.10.0

![captura de pantalla de 2016-11-02 21 00 32](https://cloud.githubusercontent.com/assets/735873/19954637/6b160114-a13f-11e6-8cc1-08cf717f2568.png)

**Comment by kmmbvnr** [comment]
i've got the same on django 1.10.

django 1.8/1.9 works well
