### ISSUE TITLE
Themes support

### ISSUE THREAD

**Issue by bendavis78** [viewflow/django-material#191]
It's currently difficult to customize colors in the admin. You have to write CSS that overrides elements explicitly. Ideally one should be able to override the `_variables.sass` file and set the `$primary-color`, `$secondary-color`, etc.

This would likely involve the inclusion of another django app to allow greater control over the static pipeline, such as `django-compressor`.

**Comment by kmmbvnr** [comment]
I don't think that mixing nodejs based pipeline with a django projects is a good idea.

Theming would be available as part of pro package.

```
$ pip install django-material-theme

INSTALLED_APPS = [
     'material_theme.yellow-light-green',
     'matetial',
     'material.fronend',
    ...
]

And as static builder option on a viewflow.io website.

**Comment by kmmbvnr** [comment]
Would be available in the next release
![themes](https://cloud.githubusercontent.com/assets/282529/21543008/7f7a5be4-cdec-11e6-8f7a-d413b1f93229.png)
