### ISSUE TITLE
Issue with cards for models in admin

### ISSUE THREAD

**Issue by MrLinio** [viewflow/django-material#198]
If there's more than 9 models in the admin for a specific module, the card breaks and the additional models are listed on the right with a nasty page break
![capture](https://cloud.githubusercontent.com/assets/5601871/20431695/be86afb6-ad9b-11e6-99d5-80c68faa3479.PNG)

**Comment by kmmbvnr** [comment]
Browser ?

**Comment by MrLinio** [comment]
Firefox and Edge.
No issues on Chrome.

2016-11-18 14:38 GMT+01:00 Mikhail Podgurskiy <notifications@github.com>:

**Comment by kmmbvnr** [comment]
Can't reproduce it with FF
![administracao do site site de administracao do django 2016-11-26 13-26-06](https://cloud.githubusercontent.com/assets/282529/20638826/ed524f80-b3db-11e6-9d76-91285a3f9fb6.png)

**Comment by kmmbvnr** [comment]
I can't reproduce it on IE11.

I suppose it somehow related to the `break-inside` problem within some browsers.

Here is the corresponding piece of code:

https://github.com/viewflow/django-material/blob/a759c8f3cbe0e5d6742e60f998e36a17606f164c/material/static/material/sass/materialize.admin.scss#L173-L174

That should work for modern browsers - https://css-tricks.com/almanac/properties/b/break-inside/

I'm closing issue right now, seems I'm not able to reproduce and fix it.

If someone has a suggestion how to fix it, feel free to send a pull request.
