### ISSUE TITLE
Issues with i18n

### ISSUE THREAD

**Issue by MrLinio** [viewflow/django-material#200]
Hi.
It seems there are some issues with i18n throughout the project.
Example in django_selectmultiple.html :
`<option value="" disabled selected>Choose your option</option>`

The "Choose your option" should be into {% trans %}.
Same goes for date format on date pickers (haven't checked if there was a parameter to set in the JS)

**Comment by kmmbvnr** [comment]
Yeah, i'm never worring about such things, since all paying customers are english soeakimh only. 

Pull requests are welcome, any way.

**Comment by MrLinio** [comment]
Ok, I'll try and find the places to change this, although i'm not very familiar with translations within libraries

**Comment by kmmbvnr** [comment]
Fixed in 67944bda11dfc6a66d20a11339df484297e1d2ae
