### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by rv1996** [viewflow/django-material#217]
when i am trying to use the form render layout it is giving me an error in the materilize html file.

![screenshot from 2016-12-30 15-19-06](https://cloud.githubusercontent.com/assets/14890514/21562998/636c6390-cea3-11e6-9de0-d43f3ba82e78.png)

**Comment by rv1996** [comment]
when i just simply remove the  layout code section , it works but again there is an issue with selecting the radio button.
Help is required asap

**Comment by kmmbvnr** [comment]
Obviously, there is not enough information in your request. I think there are some problems on your side.

Check the viewflow documentation and demo to get how to use it.
