### ISSUE TITLE
Error : 'ParoViewSet' object has no attribute '__dir__'

### ISSUE THREAD

**Issue by yalit** [viewflow/django-material#218]
Hell there, 

I'm trying to use material.frontend but when I launch the django server I receive the following error:
```   
File "local/lib/python2.7/site-packages/material/frontend/views/viewset.py", line 32, in urls
    for attr in self.__dir__()
AttributeError: 'ParoViewSet' object has no attribute '__dir__'
```

I've looked at the demo site and copied from it what was needed.
Here are the files
main/urls.py
```
urlpatterns = [
    url(r'', include(frontend_urls)),
]
```

<app>/urls.py
```    
urlpatterns = [
    # ex: /polls/
    url(r'^test/', include(views.ParoViewSet().urls)),
]
````

<app>/views.py
```
from material.frontend.views.viewset import ModelViewSet

class ParoViewSet(ModelViewSet):
    model = models.Paro
    list_display = ('title', 'location')
```

I'm running on Python2.7 (as seen in the error) and with the last version of django-material (installed today via pip).
What am I missing here?

**Comment by kmmbvnr** [comment]
That's py2.7 incompatibility problem. Thanks for the report.

**Comment by yalit** [comment]
Thanks for the quick answer (and fix ;-)). Works for me.
