### ISSUE TITLE
Incorrect menu displaying

### ISSUE THREAD

**Issue by mejmo** [viewflow/django-material#221]
Django 1.10.x, the layout of menu is not rendered correctly. Is this CSS issue that could be quickly fixed? I did not find the solution, why it displays it in such form:

<img width="243" alt="screen shot 2017-01-11 at 12 24 56" src="https://cloud.githubusercontent.com/assets/5256385/21846870/61ac0cea-d7f9-11e6-82df-1f42851a015d.png">

**Comment by kmmbvnr** [comment]
Have you tried to clean up browser cache? This probably caused by cached admin.css styles.

**Comment by mejmo** [comment]
Yes, I cleaned up the browser cache. My installed apps:

> INSTALLED_APPS = [
>     'material',
>     'material.frontend',
>     'material.admin',
>     'django.contrib.admin',
>     'django.contrib.auth',
>     'django.contrib.contenttypes',
>     'django.contrib.sessions',
>     'django.contrib.messages',
>     'django.contrib.staticfiles',
>     'blog',
>     'rest_framework',
>     'django.contrib.sites',
>     'allauth',
>     'allauth.account',
>     'allauth.socialaccount',
>     'allauth.socialaccount.providers.google'
> ]

**Comment by mejmo** [comment]
Update: it works with Safari. The problem is only in Chrome (macOS Sierra).

**Comment by mejmo** [comment]
Ok I got it. The issue is in zooming, in Chrome I had 90% and it caused this behaviour.
