### ISSUE TITLE
Admin dashboard layout problem

### ISSUE THREAD

**Issue by torehc** [viewflow/django-material#226]
Hello, when I put the web to the maximum resolution does the image.

![material](https://cloud.githubusercontent.com/assets/5724756/22293002/dcb5fbbe-e305-11e6-88e4-8006a65a2d8b.jpg)

I also do not know because it appears in gray instead of in green.

I use a Django 1.10 in a Debian VPS with Gunicorn and Nginx.

Thanks!

**Comment by kmmbvnr** [comment]
Is this firefox or ie?

**Comment by kmmbvnr** [comment]
Btw, the netural grey is the new default. Here is the documentation how to switch to other theme http://docs.viewflow.io/forms_themes.html

**Comment by torehc** [comment]
I did not know that the new default was gray.
I use firefox 50.1.0.
Thanks for the quick answer.

**Comment by kmmbvnr** [comment]
I'm sorry. Personally, I'm not going to work on fixes for that.

The overall problem with the admin dashboard that masonry layout is implemented using `multi-column` CSS - http://www.w3schools.com/css/css3_multiple_columns.asp

Firefox ignores `page-break-inside:avoid` property for the app cards.

The solution could be

1. Get the idea for the nice admin without masonry layout
2. Found a way to tell ff do not do page break inside app card
3. Use some mansory js to layout the admin dashboard

See also #220 #198 

Pull requests are welcome, anyway.
