### ISSUE TITLE
Theme change does not work

### ISSUE THREAD

**Issue by torehc** [viewflow/django-material#228]
Hi!
I have tried to change the gray to green theme by adding as it says in the documentation (Http://docs.viewflow.io/forms_themes.html), but **it did not work**.
```
INSTALLED_APPS = [
    'material.theme.lightgreen',
    'material',
    ...
]
```

I have tried with firefox and chrome, both also in private mode and even from a mobile device that had no cookie from the previous web.

The code is added in the setting and has not given any error. I have also used the `python manage-py collectstatic` command and I have restarted the vps services.

Maybe I'm missing something ...

Thank you!

**Comment by kmmbvnr** [comment]
Sorry, I don't think that I can help there.

There is no magic with themes, it just overrides several css and svg files, if you use css shiped with django-material. so you should have in you template:

```
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}
```

Check your setup and what's your webserver returns, for the `static/material/css/materialize.forms.css` and `static/material/imgs/sidenav.svg`
