### ISSUE TITLE
Update docs about custom widget rendering

### ISSUE THREAD

**Issue by cdvv7788** [viewflow/django-material#229]
As said in here: https://github.com/viewflow/django-material/issues/161 There are times when one wants to use a custom rendering.

In my case, i am trying to use django-taggit and i am getting the django representation of the object (<queryset [tag blabla]>). This should be parsed in the widget before rendering, but it seems that you are using another method. However it is not clear how it should be implemented.

**Comment by cdvv7788** [comment]
I was able to override it creating a file in 'material/fields/taggit_taggitwidget.html'.

**Comment by kmmbvnr** [comment]
Sorry, this is intentional. The widget rendering going to be changed eventually #183
