### ISSUE TITLE
'material_admin' is not a valid tag library: ImportError raised loading material.admin.templatetags.material_admin: No module named ...

### ISSUE THREAD

**Issue by mrafieee** [viewflow/django-material#23]
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.6
Exception Type:	TemplateSyntaxError
Exception Value:	
'material_admin' is not a valid tag library: ImportError raised loading material.admin.templatetags.material_admin: No module named apps
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py in load, line 1084
Python Executable:	/usr/bin/python2.7
Python Version:	2.7.9
Python Path:	
['/home/mohammad/github/DCIIM',
 '/home/mohammad/github/DCIIM',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7']

have you any idea where this came from? https://github.com/mrafieee/DCIIM

**Comment by kmmbvnr** [comment]
Unfoortunatelly material.admin have no support for django 1.6. You need to upgrade your django version at leat to 1.7

**Comment by mrafieee** [comment]
thanks!

**Comment by cleopatra27** [comment]
having error with viewflow..i used the quickstart example  and i have an import error; No module named viewflow

**Comment by kmmbvnr** [comment]
That's a django-material project. Viewflow is the separate one.
