### ISSUE TITLE
Elements appear repeatedly

### ISSUE THREAD

**Issue by marctc** [viewflow/django-material#233]
Hi,

I noticed some scenarios on Material Frontend which provoke strange behaviours:

Scenario 1:
1. Click on a link to a detail of item.
2. Go back
3. Every dropdown appear repeatedly:
![selection_038](https://cloud.githubusercontent.com/assets/280193/23059176/7e121dd6-f4f8-11e6-9ce3-c7e860032c33.png)

Scenario 2:
1. Delete an item. It redirects you to the items table.
2. Click on another item.
3. Go back
4. The toast appear repeatedly:
![selection_039](https://cloud.githubusercontent.com/assets/280193/23059449/c07624f0-f4f9-11e6-92ae-431ca0d4b67a.png)

I can open each scenario in separate issues but it seems that the root of all evil is the same: `turbolinks`. I tried to remove it temporally and both issues disappeared.

Maybe `turbolinks` is not a good option at all for this kind of project which not seems to fit the requirements of SPA site.

**Comment by kmmbvnr** [comment]
Yep, it's need to be fixed. Elements just need to be destroyed on a `turbolinks:before-cache` event

**Comment by bcanyelles** [comment]
While using material tabs I found a similar error: When the page is loaded with turbolonks the tabs apparently doesn't work and no content is displayed if you click on tabs but if you loaded without turbolinks everything works. 

![seleccion_003](https://cloud.githubusercontent.com/assets/11503500/23407805/ef247bce-fdc5-11e6-995a-61ff3e5a7598.png)

Generally speaking it happends with many of custom JS snippets inserted in pages. Agree with @marctc: turbolinks causes a lot of troubles in this project.

**Comment by kmmbvnr** [comment]
MaterializeCss itself have no way to destroy tabs. Probably, you can fill a feature request to it.

**Comment by kmmbvnr** [comment]
Btw, tabs not working, b/c you didn't initialize it on turbolinks:load event
