### ISSUE TITLE
404 "/admin/{% static" in base.html

### ISSUE THREAD

**Issue by nordbit** [viewflow/django-material#24]
```
 <script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
```
"admin" => 'admin'

**Comment by kmmbvnr** [comment]
Invalid.

There is no 404. There is no external requests.

It works exactly as in django admin. It renders as:

      <script type="text/javascript">window.__admin_media_prefix__ = "/static/admin/";</script>

**Comment by nordbit** [comment]
Strange, because after my fix error gone - I simple relpaced " " with ' '
python 3.4.2  django 1.8.2
