### ISSUE TITLE
Customize admin menu feature wanted

### ISSUE THREAD

**Issue by jinyu121** [viewflow/django-material#243]
Hi~

You really did a great job! Thank you!

But I have a problem: I want to add a new custom item in admin menu. I can do this with `django-suit`, using [some configurations(http://django-suit.readthedocs.io/en/develop/configuration.html#menu) in `settings.py`. But I do not know how to do this in django-material.

This feature will make the admin-site more flexible. For example, we can add some custom views, like dashboard, or some links into the menu.

Thanks again.

**Comment by kmmbvnr** [comment]
You can override `{% block header %}`  or one of its children `{% block sidenav_header %}`  and `{% block sidenav_items %}`  in you custom  `base_site.html`
