### ISSUE TITLE
Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable.

### ISSUE THREAD

**Issue by TobinFrost** [viewflow/django-material#244]
hello guys,
I created a module with manage.py startmodule applitest
and i leave all by default and i uncomment default code in (models.py, urls.py and views.py)
and everything was fine.
But when go to localhost:8000/applitest/mymodel/
it throws TemplateSyntaxError.

**Comment by kmmbvnr** [comment]
What django version do you use?

And what is the stacktrace and message of the TemplateSyntaxError?

**Comment by TobinFrost** [comment]
Django version 1.10.5

Error during template rendering
In template C:\Python27\lib\site-packages\material\frontend\templates\material\frontend\views\list.html, error at line 1


Environment:


Request Method: GET
Request URL: http://localhost:8000/applitest/mymodel/

Django Version: 1.10.5
Python Version: 2.7.6
Installed Applications:
['material',
 'material.frontend',
 'material.admin',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'applitest.apps.ApplitestConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template C:\Python27\lib\site-packages\material\frontend\templates\material\frontend\views\list.html, error at line 1
   Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable.   1 :  {% extends current_module.base_template %} 
   2 : {% load i18n material_form material_frontend %}
   3 : 
   4 : {% block breadcrumbs_items %}
   5 : <a class="active" href="{% url view.model|frontend_urlname:'list' %}">{{ view.model|verbose_name_plural|title }}</a>
   6 : {% endblock %}
   7 : 
   8 : 
   9 : {% block footer %}
   10 : <script type="text/javascript">
   11 :   config = {{ datatable_config|safe }};


Traceback:

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\core\handlers\exception.py" in inner
  39.             response = get_response(request)

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\core\handlers\base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\core\handlers\base.py" in _get_response
  215.                 response = response.render()

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\template\response.py" in render
  109.             self.content = self.rendered_content

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\template\response.py" in rendered_content
  86.         content = template.render(context, self._request)

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\template\backends\django.py" in render
  66.             return self.template.render(context)

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\template\base.py" in render
  208.                     return self._render(context)

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\template\base.py" in _render
  199.         return self.nodelist.render(context)

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\template\base.py" in render
  994.                 bit = node.render_annotated(context)

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\template\base.py" in render_annotated
  961.             return self.render(context)

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\template\loader_tags.py" in render
  152.         compiled_parent = self.get_parent(context)

File "C:\Python27\lib\site-packages\django-1.10.5-py2.7.egg\django\template\loader_tags.py" in get_parent
  142.             raise TemplateSyntaxError(error_msg)

Exception Type: TemplateSyntaxError at /applitest/mymodel/
Exception Value: Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable.

**Comment by kmmbvnr** [comment]
I can't reproduce

**Comment by TobinFrost** [comment]
what do you mean ?

**Comment by kmmbvnr** [comment]
I mean, everything works for me fine with dj 1.10 and py 2.7

**Comment by TobinFrost** [comment]
OK ! So how can i fix it.
any ideas ?

**Comment by kmmbvnr** [comment]
Are you sure that you are on django 1.10.5 and not on django 1.11 alfa?

**Comment by TobinFrost** [comment]
Soory but Traceback never lie.lol

**Comment by kmmbvnr** [comment]
Here is the working sample project attached.

You can explore and see what's differ with yours.

[demo.zip](https://github.com/viewflow/django-material/files/819241/demo.zip)

**Comment by TobinFrost** [comment]
Thx.
"i'll be back" 👍

**Comment by TobinFrost** [comment]
You app sample works well to me.
The problem source was caused by my  template setting **'DIRS'** in setting.py
It was  `'DIRS': [os.path.join(BASE_DIR, 'templates')]`
and i bring it to : `'DIRS': []`

**Comment by kmmbvnr** [comment]
`DIRS` just sen an additional directory for the templates. It should not cause any exceptions.

**Comment by kmmbvnr** [comment]
I'm closing this b/c I don't think that I can help here more.

If someone experience that issue, please consider to debug and send a pull request with a fix, or create a small GitHub sample project repository where the issue could be reproduced.

**Comment by narnikgamarnikus** [comment]
Exactly the same problem.
I tried to install through CLI, and manually, but it did not work out.
It seems that there is no registration of the module, for some reason.
My application has a slightly unusual structure, maybe it's this.

**Comment by maxiplux** [comment]
Hello , any news about this problem , i have the same issue.

**Comment by kmmbvnr** [comment]
The reason that it happens, that there is no `{{ current_module }}` variable in the template context.

The variable is injected by `material.frontend.urlconf.ModuleURLResolver` that used instead of usual  `django.core.urlresolvers.RegexURLResolver`

So if you directly include a material.frontend view and use material.fronted templates with `url(...)` you will get  `Invalid template name in 'extends' tag: ''.` error

**Comment by maxiplux** [comment]
hi thanks for your comment , i try add on class context but don't work , this only happend when i use 
url('^mymodel/', include(views.MyModelViewSet().urls)), , would be possible do work this , i think that this library is amazing.
Thanks.

**Comment by nuarhu** [comment]
```
from material.frontend import urls as frontend_urls

urlpatterns = [
    url(r'', include(frontend_urls)),
]
```

If I only specify it like this (without adding the URLs of the materialized module explicitly -  I cannot even navigate anywhere (404 on localhost:8000/):

```
Using the URLconf defined in hb_django.urls, Django tried these URL patterns, in this order:
    ^accounts/
The empty path didn't match any of these.
```

Adding the modules urls like this (or with `url`, doesn't matter):

    path('iot/', include(iot_urls)),

gives me that Template error from above. I've created the module with `startmodule` and I've just modified the names of the models. However, I am adding the app to INSTALLED_APPS like this:

    'my_project.apps.iot',

while `startmodule` suggested:

```
To enable the module you need to add 'iot.apps.IotConfig' to the INSTALLED_APPS setting
and run ./manage.py migrate after that
```
which did not work at all (`ModuleNotFoundError: No module named 'iot'`). (BTW `migrate` without `makemigrations` has no effect.)

**Comment by nuarhu** [comment]
How I solved this problem (my setup of the AppConfig was wrong):

Defining the app in `INSTALLED_APPS` with the regular path like `my_project.apps.my_app` requires that in the app itself the following is set:

my_project/apps/my_app/__init__.py: contains `default_app_config = 'my_project.apps.my_app.apps.MyAppConfig'`

my_project/apps/my_app/apps.py:

    class MyAppConfig(ModuleMixin, AppConfig):
        name = 'my_project.apps.my_app'
        label = 'my_app'
        icon = '<i class="material-icons">settings_applications</i>'

Most likely, the actual problem was that `name` in `MyAppConfig` was only set to `my_app`.

**Comment by MScMechatronics** [comment]
I have the same very problem Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable.
Would appreciate any advice. I've read this thread and tried to solve it however I'm not successful.

**Comment by Sachin9822** [comment]
Hey just add {% block ____%} and {% endblock ____%}in the other html page it solved my problem

**Comment by zhitoo** [comment]
put '  you forget put ' for example : extends main.html is wrong and extends 'main.html' is true
