### ISSUE TITLE
Admin logout hidden on mobile

### ISSUE THREAD

**Issue by tuxredux** [viewflow/django-material#246]
`Change password` is missing too. Easy template fix on users end, but wasn't sure if it was by design or not.

**Comment by kmmbvnr** [comment]
Yep, they are intentionally hidden. There is no place on mobile in the site header for an additional links.

**Comment by tuxredux** [comment]
Why not put the links above 'View site' in the side nav? That's what I'm doing for my projects, and it works great.

To my knowledge, mobile users have no other way of logging out other than manually typing in the URL...
