### ISSUE TITLE
Material pickadate usage

### ISSUE THREAD

**Issue by parruc** [viewflow/django-material#247]
I could not find how to use material SelectDateWidget. 

```python
class MySignupForm(forms.ModelForm):
    layout = Layout(Row('birth_date'))

    class Meta:
        model = get_user_model()

    def signup(self, request, user):
        user.birth_date = self.cleaned_data['birth_date']
        user.save()
```
and

```jinja
`{% block content %}
<form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
    {% csrf_token %}
    {% form form=form layout=form.layout %}{% endform %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <button class="btn waves-effect waves-light" type="submit">{% trans "Sign up" %} <i class="material-icons right">send</i></button>
</form>
{% endblock %}
```

But standard  datepicker is used. I tried to add

```javascript
$("input[name='birth_date']").datepicker("disable").pickadate({
            selectMonths: true,
            selectYears: 50,
            max: 2017,
        });
```

to my javascript but I get two datepicker popups...

**Comment by kmmbvnr** [comment]
Due limitations of shipped with materializeCSS picadate calendar, django-material using `jquery-datetimepicker` instead.

To change that, you need to write you own javascript initialization file. Just don't include `{% include 'material/includes/material_js.html' %}` but instead `<script src="{% static 'material/js/materialize.js' %}"></script>` and follow to the materializeCSS documentation to initilize materialize controls in a way that would works for you.

**Comment by parruc** [comment]
Just for reference I ended up overriding 

`{% static 'material/js/materialize.forms.js' %}`

into my static folder. Doing this I can override  only certain date fields to use beautiful materialize pickdate and leaving untouched (and working) the datetime fields.

```javascript
    // Date/DateTime/Time
    // https://github.com/xdan/datetimepicker
    // Overriding jquery date controller with materialize one
    // for certain fields
    $container
      .find('[data-form-control="date"]')
      .each(function () {
        if($(this).attr("name") == "birth_date"){
          $(this).pickadate({
            format: "yyyy-mm-dd",
            selectMonths: true,
            selectYears: 30
          })
        }
        else{
          $(this).datetimepicker({
            format: this.dataset.dateFormat,
            timepicker: false,
            mask: false,
            scrollInput: false
          })
        }
      })
    $container
      .find('[data-form-control="time"]')
      .each(function () {
        $(this).datetimepicker({
          format: this.dataset.dateFormat,
          datepicker: false,
          timepicker: true,
          mask: false,
          scrollInput: false
        })
      })
    $container.find('[data-form-control="datetime"]').each(
      function () {
        $(this).datetimepicker({
          format: this.dataset.dateFormat,
          datepicker: true,
          timepicker: true,
          mask: false,
          scrollInput: false
        })
      })
  }
```

**Comment by Juliaandavid** [comment]
Hi @kmmbvnr, I have the same problem, tried to write my own initialization file like this:

`<link href="{% static 'material/fonts/material-design-icons/material-icons.css' %}" rel="stylesheet">`
`<link href="{% static 'material/css/materialize.css' %}" rel="stylesheet">`
`<script src="{% static 'material/js/jquery.js' %}"></script>`
`<script src="{% static 'material/js/jquery.formset.js' %}"></script>`
`<script src="{% static 'material/js/materialize.js' %}"></script>`

but the error `$(...).pickatime is not a function` appear, I try to follow the materializecss docs but I haven't result. I don't know what to do, please, need your help!

Thats my code: 

`<input id="{{ form.start_date.id_for_label }}" name="start_date" type="text" class="timepicker" required>`
`$('.timepicker').pickatime({default: 'now', twelvehour: false});`

Thank you very much.
