### ISSUE TITLE
Error in website

### ISSUE THREAD

**Issue by parruc** [viewflow/django-material#248]
I dont think this is the right place but in the website: http://forms.viewflow.io/ the code examples do not work. Clicking on code button nothing happens.

Inspecting the pace I can see the code at the end of the page but the popup  does not work on chrome 56

**Comment by kmmbvnr** [comment]
Thanks for the report. This definitely need to be fixed.

Currently you can found demo code at https://github.com/viewflow/django-material/blob/master/demo/forms.py
