### ISSUE TITLE
Unable to login in admin module V0.12.5

### ISSUE THREAD

**Issue by tks-dp** [viewflow/django-material#256]
Hello, 

First of all, Thank you for such an awesome repo on material design ... 

I am learning django and trying to implement forms in my app,

I had downloaded 0.6th version of the repo and recently I have downloaded 0.12.5 version of this repo.

But I am unable to login in admin module with my local URL :

> http://localhost:8080/admin/login/?next=/admin/

it says "
Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive. "

![django material demo 0 12 5 unable to login](https://cloud.githubusercontent.com/assets/8553462/24369992/68f46814-1343-11e7-899c-3ad05cbcc740.png)

in My manage.py I have included URL from 'demo' module instead of 'tests'.

If I continue with Test URL login is done but output comes as follows

![django material 0 12 5 login with tests urls](https://cloud.githubusercontent.com/assets/8553462/24371767/8032978e-1349-11e7-98d8-ceadbd12a2d9.png)

I have also looked at #115 but no luck, ....

**Comment by kmmbvnr** [comment]
Please follow the docs

https://docs.djangoproject.com/en/1.10/ref/contrib/admin/
https://docs.djangoproject.com/en/1.10/ref/django-admin/#createsuperuser
http://docs.viewflow.io/material_admin.html

**Comment by tks-dp** [comment]
Thank you for quick response, I will look into them right away.

**Comment by tks-dp** [comment]
That works now! Thank you again.....
