### ISSUE TITLE
Form help_text should not be html-escaped

### ISSUE THREAD

**Issue by solarissmoke** [viewflow/django-material#257]
Django allows you to insert HTML into the `help_text` of both [model and form fields](https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.Field.help_text).

> Note that this value is not HTML-escaped in automatically-generated forms. This lets you include HTML in `help_text` if you so desire.

Django itself adds HTML to some core forms (e.g., password reset form). Currently, this ends up getting escaped by the `django-material` templates.

Happy to submit a PR if you agree to this change. It will also require wrapping the help text in a `<div>` instead of a `<small>`.

**Comment by kmmbvnr** [comment]
Thanks, that's really need to be fixed.

**Comment by solarissmoke** [comment]
[PR here](https://github.com/viewflow/django-material/pull/259).
