### ISSUE TITLE
Display issue in the admin panel

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [viewflow/django-material#258]
Hello guys,

Thanks for this amazing library by the way. However I have a small display issue.
I'm using:
* django-material==0.13.1
* django==1.10.6
* Python 3.6

Here is a screen shot : 

![image](https://cloud.githubusercontent.com/assets/10923599/24478946/55e5b05c-14dd-11e7-9263-88cd3d5d0c2c.png)

All of the following should be on the same level and appears as followed when loading the admin panel:

![image](https://cloud.githubusercontent.com/assets/10923599/24479001/8db29522-14dd-11e7-9b14-519170717e6d.png)

Thanks for the help

**Comment by kmmbvnr** [comment]
Thats Chrome bug. Just set page zoom to default.
