### ISSUE TITLE
Contributing by adding formsets: little bit of guidance

### ISSUE THREAD

**Issue by Zowie** [viewflow/django-material#26]
Hi! First of all: awesome project, first thing i thought about when I learned about Google's Material design.

I don't have an issue but I didn't know where to put this, so I figured I'd do it here.

I'd like to build out some missing parts of the Admin, I want it in one of my projects and would love to be able to offer this design to my clients. I've forked and integrated the project as a dev version in a current project, and ran into the missing formsets thing and I'd like to start there! 

I was hoping someone could point me in the right direction for adding formsets, it would save me quite some time figuring out how the Admin internals work. If not, no problem, I'll do it anyway but it'll take me a little bit longer :) I'll take a look at the issues as well to see if I can fix a couple of them while I'm at it.

I'd be happy to write a small contributing guide in the process to try to give the project a boost.

Let me know if help is welcome!

**Comment by kmmbvnr** [comment]
Go ahead )

Close. Duplicate #1

**Comment by jleszczynski** [comment]
Hi Zowie,
I plan to tackle this issue as well. Have you made any advances yet?

**Comment by Zowie** [comment]
Hi @jleszczynski.

I haven't had time, i plan to look at Django-Suit and copy as much as possible. If you would like to work together on this, i think we can manage to build it pretty fast. I've currently set up a branch of one of my projects to develop and test in but i'd be happy to create a new fork of the project and integrate the tiny bit of code i've created thus far.

Let me know. You can mail me at zowie@akoten.com as well.

**Comment by auvipy** [comment]
any working codes for PR yet? @Zowie

**Comment by auvipy** [comment]
Hi guys, how do you deal with this error?

Template error:
In template /usr/local/lib/python2.7/dist-packages/material/templates/material/fields/django_select.html, error at line 19
   Attempted relative import beyond toplevel package

   9 :                 {% endpart %}"{% endtagattrs %}>



   10 :         {% part field label %}



   11 :         <label for="{{ bound_field.id_for_label }}" class="{% part field add_label_class %}{{ form_label_class }}{% endpart %}">{{ bound_field.label }}</label>



   12 :         {% endpart %}{% part field prefix %}{% endpart %} {% part field control %}



   13 :         <select {% tagattrs %}



   14 :                 class="{% if field.widget.attrs.class %}{{ field.widget.attrs.class }} {% endif %}{% if bound_field.errors %}invalid {% endif %}{% part field add_control_class %}{{ form_control_class }}{% endpart %}"



   15 :                 name="{{ bound_field.html_name }}"



   16 :                 {% for name, value in field.widget.attrs.items %}{% if name != 'class' %}{{name}}="{{value}}" {% endif %}{% endfor %}



   17 :                 id="id_{{ bound_field.html_name }}"



   18 :                 {% part field add_control_attr %}{% endpart %}{% endtagattrs %}>



   19 :             {% part field options %} {% for value, choice in field.widget.choices %} 



   20 :             <option {% tagattrs %}{% if value|force_text == bound_field.value|force_text %}selected="selected"{% endif %}



   21 :                     {% if value == None or value == '' %}value{% else %}value="{{ value }}"{% endif %}



   22 :                     {% endtagattrs %}>{% if value == None or value == '' %}{{ form_select_empty_label|default:choice }}{% else %}{{ choice }}{% endif %}</option>{% endfor %}{% endpart %}



   23 :         </select>



   24 :         {% endpart %}{% part field help_text %}{% if field.help_text %}



   25 :             <span class="help-block">{{ bound_field.help_text }}</span>



   26 :         {% endif %}{% endpart %}{% part field errors %}



   27 :         {% if bound_field.errors %}



   28 :             {% include  'material/field_errors.html' %}



   29 :         {% endif %}{% endpart %}{{ hidden_initial }}

**Comment by kmmbvnr** [comment]
Check the bottom of your error log.

This will lead you to a line in your python code.

**Comment by auvipy** [comment]
File "/home/asif/p/smt/opsmonitor/tower/tasks.py" in <module>
  6. from ..opsmonitor.celery import app

Exception Type: ValueError at /admin/djcelery/periodictask/add/
Exception Value: Attempted relative import beyond toplevel package

**Comment by kmmbvnr** [comment]
So it's in your code

**Comment by auvipy** [comment]
now I got IT thanks for suggestion, wasn't ware
