### ISSUE TITLE
turbolinks in django admin material 

### ISSUE THREAD

**Issue by narnikgamarnikus** [viewflow/django-material#260]
Hi!
I really like what you do.
In the source, I found a turbolinks.js, which connects only to the material frontend,
When I try to connect the turbolink to the material admin, I get 

> Velocity is already loaded. You may be needlessly importing Velocity again; note that Materialize includes Velocity.

And thus, not all links work as it is necessary, sometimes it is necessary to reload a page.

The hamburger menu is not pressed in the mobile version, and the toggle in the left menu does not always work

What do you want to do?

Thanks!

**Comment by kmmbvnr** [comment]
Material admin have no turbolinks support. There is no plan yo add it.
