### ISSUE TITLE
 jQuery upgrade

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [viewflow/django-material#261]
> Jquery is a javascript library for DOM traversal and manipulation, event handling, animation, and Ajax.
> 
> When text/javascript responses are received from cross-origin ajax requests not containing the option dataType, the result is executed in jQuery.globalEval potentially allowing an attacker to execute arbitrary code on the origin.

This project requires jQuery == 2.2.0, and unfortunately every version-2 jQuery lib is vulnerable.
**Vulnerable:** >=1.4.0 <=1.11.3 || >=1.12.4 <=2.2.4
**Patched:** >=3.0.0

I hope it won't be too hard to update the lib.

More information available here : https://nodesecurity.io/advisories/328

**Comment by kmmbvnr** [comment]
The project itself does not use cross-orign requests.

**Comment by DEKHTIARJonathan** [comment]
Absolutely agree with you.
I'll keep an eye on this issue.

Have a nice day
