### ISSUE TITLE
Carousel isn't working with django-material

### ISSUE THREAD

**Issue by ShivamSharma13** [viewflow/django-material#263]
I've been trying for hours but have failed to make the materializecss **carousel** working.
I've got 3 images . The code ..
```<html>
<head>
	{% load staticfiles %}
	{% include 'material/includes/material_css.html' %}
</head>
<body>
<div class="carousel carousel-slider">
        <a class="carousel-item" href="#one!"><img src="{% static 'c1.jpg' %}"></a>
        <a class="carousel-item" href="#two!"><img src="{% static 'c2.jpg' %}"></a>
        <a class="carousel-item" href="#three!"><img src="{% static 'c3.jpg' %}"></a>
   </div> 
   <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
   {% include 'material/includes/material_js.html' %}
   <script type="text/javascript">
         $(document).ready(function(){ $('.carousel').carousel(); });
   </script>
</body>
</html>
```

The above HTML works fine using the original materialize.css file in a simple HTML file.
I've also checked the `{% static %}` existence and path of images and it's completely fine.
Please help if possible.
Thanks a lot in advance.

**Comment by kmmbvnr** [comment]
That's not true; your code does not work with MaterializeCSS from CDN also. 

Remove ` carousel-slider` to make it works. Or  add `  {fullWidth: true};` to carusel initialization, like it noted in MaterializeCSS docs.

**Comment by ShivamSharma13** [comment]
I got the ```carousel-slider``` from another reported issue.
I further tried what you mentioned and tried both the tweaks you asked me to. 
Upon removing the class ```carousel-slider``` I'm still not able to get the images.
I get the following result from inspect element.
**All the 3 anchor tags are in light shade text. The one which appears when an element is hidden in DOM**
```
<div class="carousel initialized">
            <a class="carousel-item" href="#one!" style="z-index: 0; opacity: 1; transform: translateX(540px) translateY(100px) translateX(0px) translateX(0px) translateZ(0px);"><img src="/static/c1.jpg"></a>
            <a class="carousel-item" href="#two!" style="transform: translateX(540px) translateY(100px) translateX(200px) translateZ(-200px); z-index: -1; opacity: 0.6;"><img src="/static/c2.jpg"></a>
            <a class="carousel-item" href="#three!" style="transform: translateX(540px) translateY(100px) translateX(-200px) translateZ(-200px); z-index: -1; opacity: 0.6;"><img src="/static/c3.jpg"></a>
</div>
```
Can it be a problem with my django-material version?
I'm using **django-material==0.8.0** .
Also I should mention that I'm able to successfully run other elements like django-material tabs and forms.
Thanks for the support @kmmbvnr 

Also the current code which I'm using
```
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
	{% include 'material/includes/material_css.html' %}    


</head>
<body>
<div class="carousel">
            <a class="carousel-item" href="#one!"><img src="{% static 'c1.jpg' %}"></a>
            <a class="carousel-item" href="#two!"><img src="{% static 'c2.jpg' %}"></a>
            <a class="carousel-item" href="#three!"><img src="{% static 'c3.jpg' %}"></a>
</div>   
          
    <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
    <script type="text/javascript">
           $(document).ready(function(){
                  $('.carousel').carousel();
    });
    </script>
</body>
</html>
```
Thanks again

**Comment by kmmbvnr** [comment]
Please, don't screw django-material issue tracker with invalid bug descriptions.

Obviously django-material==0.8.0 contains outdated version of MaterializeCSS. Check the old documentation for the old version of the MaterializeCSS to get carousel working.
