### ISSUE TITLE
Admin menu issue when zooming in and out

### ISSUE THREAD

**Issue by bradlishman** [viewflow/django-material#264]
![image](https://cloud.githubusercontent.com/assets/2871146/24829307/4ccb9fc4-1c6f-11e7-9de7-7ede6af22a31.png)

When I zoom to 80% ,90% and 110%, the menu items indent instead of showing on top of each other.

I've tested this in chrome and firefox.

I've looked at the admin base.html file and the css for side-nav and everything seems fine. Not sure where else to look. Happy to help if I can.

**Comment by kmmbvnr** [comment]
Yep, this is well known chrome bug

**Comment by bradlishman** [comment]
Also happens on firefox.
