### ISSUE TITLE
Error using django-categories admin

### ISSUE THREAD

**Issue by narnikgamarnikus** [viewflow/django-material#266]
Hi!
I trying use django-categories with django-material and when i go to `admin/categories/category/`, i get error: 

> AttributeError at /django-admin/categories/category/
> 
> 'str' object has no attribute 'user'

This error arise when I use django-material, but if i use original django-admin, this error don't arise.
Where is it worth to look for a mistake?

**Comment by kmmbvnr** [comment]
Yep, context_processor setting is ignored by `django-categories` and `request` is not passed to the admin templates.
