### ISSUE TITLE
filter and action forms in material_frontend

### ISSUE THREAD

**Issue by philejmath** [viewflow/django-material#272]
What's the secret to getting the filter and action forms to display on the material_frontend? I've installed a fresh app and everything is working nicely except this. The demo app has filters/actions on the frontend ModelViewSet for most of the examples. 

I've read every file in the demo app and I just can't figure out how to get these to display. Unless I'm totally missing something! Thanks for your help.

**Comment by philejmath** [comment]
As soon as I wrote this I found the material pro feature list.

**Comment by kmmbvnr** [comment]
Yep, the general rule - open source version goes to be lightweight and unopinionated, whereas pro - got more functionality with 3d party dependencies and essentially enforces the how things are implemented.
