### ISSUE TITLE
Template fail Submiting Admin Actions

### ISSUE THREAD

**Issue by FRReinert** [viewflow/django-material#275]
### When it happens 
When Action is triggered from Django admin

### Error
> invalid literal for int() with base 10: '1" class="action-select'

### Why
This is a relevant part of the Source-code provided from the Browser
```hmtl
<input class="action-select" name="_selected_action" id="_selected_action_1" type="checkbox" value="1&quot; class=&quot;action-select" />
``` 
it happens that, the action value should be an integer but the **&quot** is interpreted as part of the **Value Tag** and the rest of the element (until next quote) is being POSTED.

### Validation
Using the browser inspector, i've changed the &quot by a normal quote character and the action works.

... Thanks in advance

**Comment by FRReinert** [comment]
### Solution
1. Edit **change_list_results.html** on the following line:
```html
<input class="action-select" name="_selected_action" id="_selected_action_{{ forloop.parentloop.counter }}" type="checkbox" value="{{ item|admin_change_list_value }}" />
```
2. Add a "safe" filter ate the end of **Value** tag or copy the following code:
```html
<input class="action-select" name="_selected_action" id="_selected_action_{{ forloop.parentloop.counter }}" type="checkbox" value="{{ item|admin_change_list_value|safe }}" />
```

**Comment by DEKHTIARJonathan** [comment]
Any chance it could be linked to : #267

**Comment by kmmbvnr** [comment]
Duplicate #267
