### ISSUE TITLE
Admin layout multiple inline crash

### ISSUE THREAD

**Issue by erick-orestes** [viewflow/django-material#277]
@kmmbvnr  i'm having the same problem as this issue reported https://github.com/viewflow/django-material/issues/128 and it is persistent. The problem arise when two or more inlines are declared in the layout. 
It rises 'InlineAdminFormSet' object has no attribute 'model' at /material/admin/templatetags/material_admin.py in fieldset_layout, line 124

**Comment by kmmbvnr** [comment]
Can't reproduce.

**Comment by erick-orestes** [comment]
@kmmbvnr  to reproduce it's only necessary to use two inlines in the admin and use layout to order them. Like this
```
from .models import Question, Answer, Choice
from material import Layout, Row, Fieldset
from material.admin.base import Inline

class AnswerInline(admin.TabularInline):
    model = Answer
    extra = 1


class ChoiceInline(admin.TabularInline):
    model = Choice
    extra = 1

class QuestionAdmin(admin.ModelAdmin):

    list_display = ('question_text', 'pub_date')
    inlines = (ChoiceInline, AnswerInline)
    layout = Layout(
        Fieldset('Grettings', Row('question_text', ),
                 ),
        Inline(ChoiceInline),
        Fieldset('Grettings 2',
                 Row('pub_date',), ),
        Inline(AnswerInline),
    )

admin.site.register(Question, QuestionAdmin)
```
with the following models
```
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.TextField(default='Question not answered')
    answer_date = models.DateTimeField('date answered')
```

The first time you enter the change view of the admin it raise this AttributeError

![captura de pantalla de 2017-05-11 09 18 56](https://cloud.githubusercontent.com/assets/28451847/25957671/160846be-362c-11e7-9a07-544fe5d6eec4.png)

**Comment by kmmbvnr** [comment]
Layout in admin is not supported.

Admin has own way to manage field positions with `fields` and `fieldsets` attributes.

**Comment by erick-orestes** [comment]
@kmmbvnr  Nevertheless I found it quite useful in the admin and it works perfectly fine except for that case. The error only shows the first time you enter the change view. Debugging i found the problem at the template tag fieldset_layout with this nested loop
```
    for element in layout.elements:
        # TODO Ugly hack to substitute inline classes to instances
        if isinstance(element, Inline) and isinstance(element.inline, type):
            for inline in inline_admin_formsets:
                if inline.formset.model == element.inline.model:
                    element.inline = inline

```
The outer loop is iterating over element and the inner loop access a attribute of element and then change that attribute so the next iteration the call to element.inline.model will fail because the inline attribute of element has changed.

**Comment by kmmbvnr** [comment]
Yeah, that's was an initial idea, to have support for the layout in the admin. But it's not the last issue that happens. 

So the artifacts of layout support would be removed eventually.

Generally, the admin part of this project has the low priority, so the state of python/html/css is far from ideal. But anyway, only things related to the standard admin functionality going to be supported.
