### ISSUE TITLE
Overriding TextAreas (when using django-ckeditor)

### ISSUE THREAD

**Issue by leblancpierre** [viewflow/django-material#28]
Hi, 

For my project I've been looking for django admin interfaces, I'm coding my own blog with Django and I'll use the django admin to write my  posts.
The thing is that I'll want some of my friends to use this backend part of django, and the original display isn't that rookie friendly.

So basicly I found django-admin-bootstrapped, django-suit, and django material.

I'm using django-ckeditor to be able to use RichTextFields to write the content of a post.
Thing is that the RichTextField doesn't display the CK editor when I'm using django material.

So what I'm basicly asking : Is the support of django ck editor and the display of their RichTextField planned ?

Thank you.

(Otherwise I'll be using django-suit)

**Comment by kmmbvnr** [comment]
No. There is no richtext support.

**Comment by somerrajab** [comment]
Install django-ckeditor
Create a JS file include the following:
`var config={}; //add your ckeditor config
$('.materialize-textarea').each(function(){
  CKEDITOR.replace($(this).attr('id'), config);
}
`
You might need to do some extra work for plugins

include your js in template or admin like so:
`
    class Media:
        js = ('js/YOUR JS FILE',)
`
