### ISSUE TITLE
problam with checkbox input-field position

### ISSUE THREAD

**Issue by tutzy1** [viewflow/django-material#287]
Hi,
In [this file](https://github.com/viewflow/django-material/blob/master/material/static/material/css/materialize.css) at line 4792 the value of left attribute of  checkbox input-fields (which have absolute position) is set to -9999px.
Why is that?
It makes my screen unnecessarily wide.
Thanks!

**Comment by kmmbvnr** [comment]
That's the question to https://github.com/Dogfalo/materialize

But probably you do something wrong or use too old browser.

**Comment by tutzy1** [comment]
OK! BTW - There is an open issue for this problem...
