### ISSUE TITLE
Admin Inline Form Field Customization (Select Widget's Option customization)

### ISSUE THREAD

**Issue by madEng84** [viewflow/django-material#292]
Hi, 
This is not a bug but a help request.
I want to customize one field adding a data-attribute to every select's option to add js interaction with a other fields

So i have changed the template of my AdminInline.
In this template i changed the part:
`{% with form=inline_admin_form.form %}{% render field.field %}{% endrender %}{% endwith %}`

in 

```
{% with form=inline_admin_form.form %}
{% if field.field.name == "my-custom-field" %}
{% render field.field %}{% part field.field %}
{% part field suffix %}DEBUG{% endpart %}
{% part field options %}`{{see_after}}`{% endpart %}
{% endpart %}{% endrender %}
{% else %}
{% render field.field %}{% endrender %}
{% endif %}
{% endwith %}
```
I can see DEBUG as prefix but...
`{{see_after}}` could be similar to the part options i can see in template django_select.html but i can access only to `choice, value, selected` values form material's templatefilter select_options

This is the part options of django_select.html
```
{% part field options %}{% for group, items in bound_field|select_options %}
            {% if group %}<optgroup label="{{ group }}">{% endif %}{% for choice, value, selected in items %}
            <option {% if value == None or value == '' %}value{% else %}value="{{ value|unlocalize }}"{% endif %}{% if selected %} selected="selected"{% endif %}>{% if value == None or value == '' %}{{ form_select_empty_label|default:choice }}{% else %}{{ choice }}{% endif %}</option>{% endfor %}
            {% if group %}</optgroup>{% endif %}{% endfor %}{% endpart %}
```

My question is: what is the best manner to accomplish my request? 

Do you think is the best way to change the templatefilter to have additional data in my option's tag?
Consider that the data-attr is known only in the backend

Thanks in advance

**Comment by kmmbvnr** [comment]
Yeah, part context, and select/optinos attribute is tough in the current implementation. That's need improvements.

First of all `{% if field.field.name == "my-custom-field" %}` should be dropped. Just use `{% part form.my_custom_field  ... %}`

And you can use `form.my_custom_field` directly in the part declaration
