### ISSUE TITLE
Django admin customisation

### ISSUE THREAD

**Issue by Sahana312** [viewflow/django-material#295]
I have a django admin which has a list view and on click of the list item, the detail view appears. I want to customize how the layout looks. how do I do that? I tried using the layout field in my models field like below 

layout = Layout(
            'tail_number',
            'schedule_id',
            'flight_group_code',
            'scheduled_days',
            Row('origin_port_code', 'destination_port_code'),
            Row('start_date', 'end_date', 'flight_departure_time')
        )

But this doesn't change my layout in the page. How do I customize the admin site looks ? Is it do able? If you could provide me an example it would be of great help.

**Comment by kmmbvnr** [comment]
Just follow the django admin documentation https://docs.djangoproject.com/en/1.11/ref/contrib/admin/
