### ISSUE TITLE
Select options for TimeField with choices -- don't humanize the date

### ISSUE THREAD

**Issue by tammyalexandra** [viewflow/django-material#296]
In my models.py, I have

`checkin_time = models.TimeField(default=time(10,0), choices=[(time(10,0), '10 AM'), (time(12,0), '12 PM')])`

Without django-material, this renders and validates just fine.  With django-material, it does not.  The reason is that in the template, instead of turning time(10,0) into '10:00', it turns it into '10 a.m.'  Compare:

**WITHOUT django-material:**

    <select id="id_checkin_time" name="checkin_time">
            <option value="10:00:00">10 AM</option>
            <option value="12:00:00" selected="selected">12 PM</option>
    </select>

**WITH django-material:**

    <select id="id_checkin_time" name="checkin_time" class="initialized">
            <option value="10 a.m.">10 AM</option>
            <option value="noon" selected="selected">12 PM</option>
    </select>

The only way to get django-material to work is to add the following in forms.py:

`checkin_time = forms.TypedChoiceField(choices=[('10:00', '10 AM'), ('12:00', '12 PM')] )`

This shouldn't be necessary.  The date shouldn't be humanized in a non-human context.  Thanks!

**Comment by kmmbvnr** [comment]
Probably you are on an outdated django-material version.  This was fixed a year ago

https://github.com/viewflow/django-material/commit/8ec1c3f660f4f394b57665de5a6cf83b93871d74
