### ISSUE TITLE
Display same app models under different headers 

### ISSUE THREAD

**Issue by Sahana312** [viewflow/django-material#297]
`Other` is my app name. It has 4 models under it.

`PaymentMethods`, `Currencies`,` ReasonCodes` ,` DeviceInfo`

Now in the default admin, all the 4 models are displayed under other app.

I need to display like this, verbose name of other will be `'payments'` and under this i would want `PaymentMethods`, `Currencies`

and another section named 'device info' and under this,  `ReasonCodes` , `DeviceInfo` should be shown.

Can this be configured using the library?

**Comment by kmmbvnr** [comment]
yep, just customize templates

**Comment by Sahana312** [comment]
How do I do it? Can you please give me an example or a documentation link?

**Comment by Sahana312** [comment]
I have two base_site.html in material folder. But it doesnt contain the sidenav_items block
