### ISSUE TITLE
Hidden columns in site mobile

### ISSUE THREAD

**Issue by lukasgarcya** [viewflow/django-material#299]
I open admin site in my smartphone with cloumns hidden in change page. I put screenshots in this issue.
![screenshot_20170709-115414](https://user-images.githubusercontent.com/1985696/27995004-e91d0b58-649d-11e7-8d30-851a6651ca92.png)
![screenshot_20170709-115424](https://user-images.githubusercontent.com/1985696/27995005-e91f05e8-649d-11e7-86cc-63cc0dbd5e37.png)

**Comment by kmmbvnr** [comment]
Yep. That's how it works on small screen
