### ISSUE TITLE
unique_together doesnt give message when there is an error.

### ISSUE THREAD

**Issue by Sahana312** [viewflow/django-material#300]
Django 1.8
Python 2.7
Material - latest

I have a model for which I have given the unique_together field. Find the model below. 

    class ProductPriceList(models.Model):
        product_code = models.ForeignKey(Product)
        product_price = models.IntegerField()
        price_list_code = models.ForeignKey(Pricelist, null=True, related_name='product_price_list')

        def __unicode__(self):
            return '%s' % self.product_code

        class Meta:
            verbose_name_plural = "Product Pricelist"
            unique_together = ('price_list_code', 'product_code')

But when I violate the `unique_together` field, it just displays "Please correct the error below." But doesnt say what the error is.

Have attached the screenshot for reference.

![uniqu_together_error](https://user-images.githubusercontent.com/19899785/28006551-6d0f5a04-656d-11e7-9413-5167ee55ab21.png)

**Comment by kmmbvnr** [comment]
Can't reproduce

http://demo.viewflow.io/admin/integration/city/add/

![add city django site admin](https://user-images.githubusercontent.com/282529/28058697-391b6bee-6643-11e7-834e-bd45eed4dcae.png)
