### ISSUE TITLE
ListModelView.ordering has little effect

### ISSUE THREAD

**Issue by orgkhnargh** [viewflow/django-material#301]
Using `ordering` on `ListModelView` has only a short-term effect, as it is only used when the template is being rendered for the first time. Subsequent request from the same page made by frontend would normally fall into [this branch](https://github.com/viewflow/django-material/blob/859ef27b39e385d8b42648bea5ed0ef1aeb5a127/material/frontend/views/list.py#L271-L284), which ignores `ListModelView.ordering`.

I think it might be reasonable to deprecate `ListModelView.ordering` in favor of `order` from `datatable_config`, as this is what is takes effect right now anyway. Any thoughts?

**Comment by kmmbvnr** [comment]
It just a small missing piece
