### ISSUE TITLE
Inline formsets missing

### ISSUE THREAD

**Issue by nick-lehmann** [viewflow/django-material#306]
The documentation shows [here](http://docs.viewflow.io/forms_formsets.html) how the user can use fields like `ModelFormField` to nest forms. Unfortunately, I can't find this feature in the current version. Was this feature removed for some reason, or moved so I can't find it or is the documentation wrong?

**Comment by kmmbvnr** [comment]
Inline form sets is one of the feature of the pro version http://viewflow.io/pro/
