### ISSUE TITLE
createtheme says command error

### ISSUE THREAD

**Issue by Sahana312** [viewflow/django-material#321]
Command 
python manage.py createtheme --primary-color=1b5e20  --secondary-color=01579b

gives Unknown command: 'createtheme'
Type 'manage.py help' for usage.

Do we have to do anything extra? Also in the documentation, it says PRO only. What does this mean?

**Comment by kmmbvnr** [comment]
The `createtheme` command available in the Material PRO package only - http://viewflow.io/pro/
