### ISSUE TITLE
How to override admin static files?

### ISSUE THREAD

**Issue by Kianoosh76** [viewflow/django-material#322]
Hi!
I've recently installed your wonderful project! But there is one thing unclear for me:
How can we change the background image or the main theme of the material admin interface?
Thanks a lot

**Comment by kmmbvnr** [comment]
Like in any other django app, put the required image in STATICFILES_DIR

https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-STATICFILES_DIRS
