### ISSUE TITLE
Don't titleize object instances

### ISSUE THREAD

**Issue by bendavis78** [viewflow/django-material#324]
There are places in the admin, such as the change form, where instance names are titleized, for example:

    {{ adminform.form.instance|title }}

This is much too implicit, and breaks formatting for instance strings that aren't intended to be titleized. For example, "Invoice ABC-123" is changed to "Invoice Abc-123". Also, some instances might have a brand name that starts with a lowercase letter, and it's always intended to look that way.

I know it's mostly a cosmetic issue, but I think there's a good case for removing `|title` from object instances in the admin.

**Comment by kmmbvnr** [comment]
Closed due #373
