### ISSUE TITLE
Datatable issue (copying datatable_default_config) 

### ISSUE THREAD

**Issue by francescarpi** [viewflow/django-material#325]
Hi, 
I've four datatables in the same page and often appears this error:

![error1](https://user-images.githubusercontent.com/287872/29754661-6d5a2694-8b4f-11e7-9946-d2dd01fc6e16.png)

This is because the table columns and ajax response columns, doesn't match. The ajax's request url doesn't seems to be correct.

Investigating I've discovered that when the template of config dictionary is copied return an shallow copy of original dictionary. 

https://docs.python.org/3.5/library/stdtypes.html?highlight=dict%20copy#dict.copy

This is a problem, because when ajax's url is updated, this also updated in original dictionary.

Take a look this example:

![error2](https://user-images.githubusercontent.com/287872/29754667-8220aa80-8b4f-11e7-8bdf-2418af73a8a0.png)

And then, when config is updated with this response method (get_datatable_action_config()), that return a datatable_defult_config, the ajax's url is wrong.

The best way for clone template dictionary, is using deepcopy. Take a look this example:

![error3](https://user-images.githubusercontent.com/287872/29754669-865ce79e-8b4f-11e7-9294-7c44d36234a8.png)

Do you want that I sent to you a pull request?

**Comment by kmmbvnr** [comment]
Having multiple data tables on the same page are not supported
