### ISSUE TITLE
Disable turbolinks

### ISSUE THREAD

**Issue by MrSaints** [viewflow/django-material#328]
Is there a quick way I can disable turbolinks? It's presenting more problems than it is solving.

**Comment by kmmbvnr** [comment]
Probably you can just override js template and just not to include the turbolinks script. But this could leave some js plugins uninitialized. 

Developing plain old 200x fronend is not a goal for this project. 

Generally any problems with turbolinks can be solved by reading turbolinks documentation.

**Comment by MrSaints** [comment]
If anyone is interested in a solution, set Turbolinks to only run on a path that you will never use, for example:

```
<meta name="turbolinks-root" content="/_disabled">
```
