### ISSUE TITLE
Url management 

### ISSUE THREAD

**Issue by pablovg2** [viewflow/django-material#330]
Hello,

I have reviewed all the documentation and I realized that I was dragging an error in my project that was causing me a lot of errors, now everything seems to work correctly.

Sorry for the tickets opened earlier but was a bit overshadowed ..

I have a question about the handling of urls, according to the documentation I understand that you do not have to add the url of each app in the project, but all are added directly through 'frontend_urls'.

However I have this problem:
```
NoReverseMatch at /blog/list/
Reverse for 'blog-entry-list' not found. 'blog-entry-list' is not a valid view function or pattern name.

```

If I comment the line of the app 'blog' in the `project/urls.py` I get the error, if I uncomment it and include the urls of the blog app then it works.

*blog/urls.py*

```
from django.conf.urls import *
from django.conf import settings
from django.views import generic


from . import views


urlpatterns = [
    url('^$', generic.RedirectView.as_view(url='./list'), name="index"),

    url(r'^$', views.BlogEntryList.as_view(), name="blog-entry-list"),
    url(r'^list/$', views.BlogEntryList.as_view(), name="blog-entry-list"),
    url(r'^view/(?P<pk>\d+)$', views.BlogEntryView.as_view(), name="blog-entry-view"),
    url(r'^view/(?P<slug>[\w-]+)$', views.BlogEntryView.as_view(), name="blog-entry-view"),
]


```

*project/urls.py*

```
...
from material.frontend import urls as frontend_urls

urlpatterns = [

    url('^$', generic.RedirectView.as_view(url='./dashboard'), name="index"),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'', include(frontend_urls)),

   # url(r'^blog/', include(blog_patterns)), #THIS LINE
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

```

Thank you very much!

**Comment by kmmbvnr** [comment]
You didn't include namespace in the url name

http://docs.viewflow.io/material_frontend.html

![material frontend 1](https://user-images.githubusercontent.com/282529/30109766-6797f5e2-9329-11e7-85df-b1fa5493fbfc.png)
