### ISSUE TITLE
raw_id_field search box does not show a search field

### ISSUE THREAD

**Issue by nyejon** [viewflow/django-material#333]
Hi,

Thanks for all of the effort on this! It's quite the achievement!

I am using the raw id field as I cannot get any of the autocomplete widgets (DAL, Select2.. ) to work in the admin.

However, if I click on the search button it shows a page where I can select the instance but there is no search field. That makes it very difficult to find the one instance I'm looking for in my 10000 pages.

Thanks

**Comment by nyejon** [comment]
Ah, It seems like the search box is just hidden with the default size. If I resize the window it appears so it could be there needs to be some CSS or breakpoints changed?

**Comment by kmmbvnr** [comment]
yep, django-material admin has no support for other 3d party django extensions for autocomplete in the admin.

**Comment by nyejon** [comment]
Thanks for the fast response. Is there a way to get the search window to open a bit larger by default so that the search box appears automatically and the user doesn't need to resize the window? and to drop the 'centering' of the table. As you can see in the image below there is a lot of dead space on the left hand side.

![image](https://user-images.githubusercontent.com/17871768/30327398-2eb10924-97cc-11e7-823d-6385c93f2e7b.png)

**Comment by kmmbvnr** [comment]
Closed due #373
