### ISSUE TITLE
Is possible to prevent action add in ModelViewSet

### ISSUE THREAD

**Issue by pablovg2** [viewflow/django-material#334]
I would like to prevent action add in frontend for one specific model.

What is the best way to do this?

thanks

**Comment by emihir0** [comment]
This might just do the trick:

    @property
    def create_view(self):
        return 

When a ModelViewSet's urls are created by looking at the attributes ending with _view. However, it only accepts those who return list/tuple as a valid view. If you return nothing, then it is not considered a view and hence the add view will not be created =).

**Comment by kmmbvnr** [comment]
In v2 CRUD actions became available as mixins, that would allow creating an URL config with only required entities.
