### ISSUE TITLE
Filter ListModelView by filterset_fields 

### ISSUE THREAD

**Issue by spolpen** [viewflow/django-material#335]
Hello,

I have a view with ListModelView and i want to add some filters with filterset_fields like it's explain  [in the doc](http://docs.viewflow.io/frontend_crud.html#material.frontend.views.ListModelView).

**views.py**
````
class ContactListView(ListModelView):
    model = Contact
    list_display = ('name','surname','nif')
    filterset_fields = ('nif',)
    template_name = 'addcontact.html'
    def get_context_data(self, **kwargs):
        contacts = get_object_or_404(Contact,pk=1)
        return super(ContactListView, self).get_context_data(contacts=contacts, **kwargs)
    def get_queryset(self):
        qs = Contact.objects.all()
        if(self.request.GET.get('nif')):
            qs = Contact.objects.filter(nif=self.request.GET.get('nif'))
            return qs
        return qs

class ContactViewSet(ModelViewSet):

    model = Contact
    list_display = ('contact', 'expedient')
    list_filter = ('contact',)

    contact_list_view = [
    r'^(?P<expedient_pk>[^/]+)/addcontact',
    ContactListView.as_view(),
    '{model_name} contact'
]
````

**urls.py**
```
urlpatterns = [
    url('^$', views.expedient_list, name="index"),
    url(r'addnew/', views.expedient_add_new, name="addnew"),
    url('',include(views.ContactViewSet().urls), name="addcontact"),`
```

If i write the url like example.com/app/?nif=value the filter it's works fine, the problem is when it's filter with a input text and a petition by ajax. Which view/url should process the search?

**Comment by kmmbvnr** [comment]
Filters and actions available only in the PRO version

http://docs.viewflow.io/frontend_crud.html#material.frontend.views.ModelViewSet

Thank's for pointing to the ListView docs, I'll add the additional information.

**Comment by spolpen** [comment]
I implemented the filters by code, but the view doesn't refresh the table when apply it. Which url should call ajax for it?

**Comment by kmmbvnr** [comment]
django-material motto is to use same view URL for everything. That allows DRY querysets and permissions check.  That's well described in the article about autocomplete implementation - https://medium.com/@viewflow/redesigning-an-autocomplete-for-django-1994fd07c0a6

Filters are bit tricky to implement and available only in PRO version

![pro list filter and actions support kmmbvnr material pro 2bff9d9](https://user-images.githubusercontent.com/282529/30424986-76384ae8-9969-11e7-8a3c-03eb6e9d025d.png)
