### ISSUE TITLE
Using django-smart-selects

### ISSUE THREAD

**Issue by pablovg2** [viewflow/django-material#337]
I want to related 

I want to relate one select field to another. 

First, with django-material-PRO are there any option to do it?

I'm trying to do it now with [django-smart-selects](https://github.com/digi604/django-smart-selects)  and I've tested with this and work fine  [grouped-selects])https://github.com/digi604/django-smart-selects#grouped-selects)

But if I try with the [chainedforeignkey](https://github.com/digi604/django-smart-selects#chainedforeignkey-options) I get this error: 

```

Request Method: GET
http://127.0.0.1:8000/admin/configuration/trigger/add/
1.11.3
TypeError
'NoneType' object does not support item assignment
/home/pablov/.virtualenvs/project/lib/python3.5/site-packages/smart_selects/widgets.py in render, line 136
```
```
Error during template rendering

In template /home/pablov/.virtualenvs/project/lib/python3.5/site-packages/material/admin/templates/material/fields/django_relatedfieldwidgetwrapper.html, error at line 3
'NoneType' object does not support item assignment

 
{% admin_related_field_urls bound_field as bound_field_urls %}
 
<div class="related-widget-wrapper">
{% render bound_field widget=field.widget.widget %}
{% part field label %}
<label for="{{ bound_field.id_for_label }}" class="related-widget-label">
<span style="margin-right:5px">{{ bound_field.label }}</span>
{% if bound_field_urls.can_change_related %}
<a class="related-widget-wrapper-link change-related"
data-href-template="{{ bound_field_urls.change_related_template_url }}?{{ bound_field_urls.url_params }}"
id="change_id_{{ bound_field.html_name }}"

```

**Comment by kmmbvnr** [comment]
No, currently there is no such feature.

**Comment by pablovg2** [comment]
Ok, and you know why it may be failing? 

Regards

**Comment by dvb7836** [comment]
I have the same problem: django-smart-selects is not working with material.admin. What information do I need to provide for this to be fixed?

**Comment by kakinoki** [comment]
i'm facing the same problem and has almost finished fixing this.
but i'm having some trouble with the material side.

so i wrote a custom template for rendering smart-select widgets, but i need to add some custom attributes to the <select> tag. is there any way to do this?


`<select{% attrs bound_field 'widget' default field.widget.attrs %}
            id="id_{{ bound_field.html_name }}"
            name="{{ bound_field.html_name }}"
            data-chainedfield="{{ bound_field.data_chainfield }}"
            data-url="???"
            data-value="???"
            data_auto_choose="???"
            data-empty_label="-----------"
            class="chained-fk"
            {% if bound_field.errors %}class="invalid"{% endif %}
        {% endattrs %}>`
