### ISSUE TITLE
When I click an item in dropdown selector , the item won't be selected

### ISSUE THREAD

**Issue by liangWenPeng** [viewflow/django-material#340]
for example ,in http://forms.viewflow.io/demo/bank/, when I click America in Nationality, America won't be choosed. My browser is Google Chrome v61.0.3163.100.

**Comment by kmmbvnr** [comment]
mm, there is no America in Nationality
![screenshot from 2017-10-01 11-48-20](https://user-images.githubusercontent.com/282529/31052184-8dee116c-a69e-11e7-8072-566233842028.png)

**Comment by roffel** [comment]
I have got the same problem. This also applies to my local setup.

**Comment by kmmbvnr** [comment]
Can someone give more details about that? 

I don't even understand what do you mean, there is no American in the Nationality.

**Comment by roffel** [comment]
![screen shot 2017-10-02 at 18 06 34](https://user-images.githubusercontent.com/9349165/31087218-877753ee-a79c-11e7-872a-26b3eaac029f.png)

The main issue is that when an item has been selected from a dropdown it doesn't select properly in the background and it returns an error when submitting the form.

**Comment by kmmbvnr** [comment]
I can't reproduce.

**Comment by roffel** [comment]
Seems to happen with relationships. Same at: http://demo.viewflow.io/admin/integration/sea/add/

**Comment by kmmbvnr** [comment]
Still, have no idea how to reproduce

**Comment by liangWenPeng** [comment]
I have recorded  a video about this problem. Here is the video link: https://pan.baidu.com/s/1boCCNyZ

**Comment by liangWenPeng** [comment]
American is just for an example, I mean that sometime when I click an item in the dropdown, the item can't be selected . May be a bug.

**Comment by kmmbvnr** [comment]
That's hard to say what caused the issue. And still, there is no description how to reproduce it.

I update MaterializeCSS to 0.100.2, probably it could solve that.
