### ISSUE TITLE
Tabbed admin forms instead of a long single form

### ISSUE THREAD

**Issue by nyejon** [viewflow/django-material#343]
Hi,

I would like to add the functionality to have the different formsets in an admin form as tabs instead of the vertical layout.

I see how I can implement the tabs with materialize css, but I could use some starting pointers where to add that to the various templates.

**Comment by kmmbvnr** [comment]
django-material admin project scope limited to the features that django admin has.

**Comment by nyejon** [comment]
Ok, and where would I need to start to try and implement the collapsed class? Would it just be a template update?
