### ISSUE TITLE
Better than css?

### ISSUE THREAD

**Issue by rizplate** [viewflow/django-material#348]
I am a bit confused what is the advantage of using this vs just adding material css classes to a an element, why add this app and middleware ?

**Comment by kmmbvnr** [comment]
If you take closer at materialize/css you'll find that django is not capable to handle that

Django allows to customize only `<input ...` part of the widget rendering, while modern frameworks requires to customize label and wrapper element rendering also, ex `<div class="input-field><input class="...">`
