### ISSUE TITLE
material-dashboard is not present (django-material v1.1.0)

### ISSUE THREAD

**Issue by RedPelle** [viewflow/django-material#350]
From API documentation:
http://docs.viewflow.io/material_dashboard.html

> "Material Dashboard comes as part of django-material package."

Adding material.dashboard in the INSTALLED_APPS results in the error:

> No module named 'material.dashboard'.

In fact no package is present in "site-packages" after "pip install django-material".

**Comment by kmmbvnr** [comment]
yep, dashboard going to be part of pro, and not released yet,
