### ISSUE TITLE
Material Admin - Logout button is not present in small screens

### ISSUE THREAD

**Issue by RedPelle** [viewflow/django-material#351]
As shown in the screenshots at:
http://forms.viewflow.io

Material Admin seems to keep the logout button in small devices, but it not happens.
Not even in the demo:
http://demo.viewflow.io/admin/

<img width="314" alt="schermata 2017-10-29 alle 10 41 47" src="https://user-images.githubusercontent.com/32457048/32142347-e32cfa6e-bc95-11e7-828d-118a808e03ce.png">

**Comment by kmmbvnr** [comment]
Closed due #373
