### ISSUE TITLE
Material Admin - No action is present in small devices after selecting items

### ISSUE THREAD

**Issue by RedPelle** [viewflow/django-material#352]
In responsive mode of Material Admin, list of items, when selecting a small device, like iPhone 6 you can select items in order to make actions, but action panel is not present.

Demo site:
http://demo.viewflow.io/admin/integration/continent/

Screenshot:
<img width="317" alt="schermata 2017-10-29 alle 10 47 53" src="https://user-images.githubusercontent.com/32457048/32142411-2d183520-bc97-11e7-9d78-2d06cd7b2e25.png">

**Comment by mashrikt** [comment]
Hi guys, I have actually taken care of this in one of my projects. I believe I can take care of this.

**Comment by kmmbvnr** [comment]
Closed due #373
