### ISSUE TITLE
Admin material doesn't show custom icon

### ISSUE THREAD

**Issue by ramondepieri** [viewflow/django-material#354]
I´m trying change de app admin icon and models. However, doing the steps as documentation said(change the app.py or models.py) and add the` icon = '<i class="material-icons">flag</i>'` nothing happens. The default icon still being shown.

My static file is working normally and running on localhost.

The version that I´m have been testing is django 1.11, dajango-material 1.1.0 and python 3.6.3

**Comment by kmmbvnr** [comment]
Mm, I don't think that I can help there. Probably you do something wrong.

You can check the demo for the reference sample https://github.com/viewflow/django-material/blob/master/demo/examples/employees/admin.py
