### ISSUE TITLE
ENTER in admin search field execute a action

### ISSUE THREAD

**Issue by ramondepieri** [viewflow/django-material#355]
Adding a search field on admin to any model and using the field, then pressing ENTER(to effectuate the search) the following message is show: Items must be selected in order to perform actions... like attach img: 
![django-material-search-bug](https://user-images.githubusercontent.com/6942734/32545484-0d595e02-c463-11e7-9847-6bf8bcfb04fc.png)

**Comment by kmmbvnr** [comment]
yep, currently it works only on search icon click

**Comment by kmmbvnr** [comment]
Closed due #373
