### ISSUE TITLE
How use custom form admin with material

### ISSUE THREAD

**Issue by ramondepieri** [viewflow/django-material#357]
In original admin page, I have been using a custom form as bellow:

**#forms.py**
```
from django import forms

class PlanoReplaceURLActionForm(forms.Form):
    teste = forms.CharField(required=False, widget=forms.Textarea)
```

In this way, I using something like 
**#admin.py**
  ```
      return TemplateResponse(
            request,
            'admin/my_app/my_model/edit_form.html',
            context,
        )
```
to my template. **My template is:**
`
{% extends "admin/change_form.html" %}
{% load i18n admin_static admin_modify %}

{% block content %}
<div id="content-main">

  <form action="" method="POST">
    {% csrf_token %}

    {% if form.non_field_errors|length > 0 %}
      <p class="errornote">
          "Please correct the errors below."
      </p>
      {{ form.non_field_errors }}
    {% endif %}

    <fieldset class="module aligned">
      {% for field in form %}
        <div class="form-row">
          {{ field.errors }}
          {{ field.label_tag }}
          {{ field }}
          {% if field.field.help_text %}
          <p class="help">
            {{ field.field.help_text|safe }}
          </p>
          {% endif %}
        </div>
      {% endfor %}
    </fieldset>

    <div class="submit-row">
      <input type="submit" class="default" value="Submit">
    </div>
  </form>
</div>

{% endblock %}`

however in django-material admin, this custom form does´t show with django-material class and format.

**Comment by kmmbvnr** [comment]
You can check [django-material docs](http://docs.viewflow.io/material_forms.html) and admin [change form template](https://github.com/viewflow/django-material/blob/master/material/admin/templates/admin/change_form.html#L41) for the references
