### ISSUE TITLE
[Bug] ForeignKey field don't work on mobile

### ISSUE THREAD

**Issue by JayTurnr** [viewflow/django-material#358]
In the standard Flat admin theme, on mobile, ForeignKey supplies an auto-generated option.

On django-material, it seems to only take an integer.

**Comment by JayTurnr** [comment]
```
@admin.register(Update)
class UpdateAdmin(AjaxSelectAdmin):

	form = make_ajax_form(Update, {
		'trainer': 'trainer'
	})
	list_display = ('trainer', 'xp', 'datetime')
	search_fields = ('trainer__username', 'trainer__account__username')
	ordering = ('-datetime',)
	date_hierarchy = 'datetime'
	icon = '<i class="material-icons">insert_chart</i>'
```

**Comment by JayTurnr** [comment]
It may be an issue with Ajax, I need to test.

**Comment by kmmbvnr** [comment]
django-ajax-selects is the 3d-party addon and is not supported

**Comment by JayTurnr** [comment]
Do you know any workaround? A pull down menu doesn't suffice when the options for in the hundreds

**Comment by kmmbvnr** [comment]
https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields

**Comment by JayTurnr** [comment]
That's not acceptable, again, over 300 options, none of the admins are going to remember the raw IDs of the options.

**Comment by kmmbvnr** [comment]
Please refer to the Django documentation. raw_id_field doesn't not imply remembering IDs.
