### ISSUE TITLE
Forms are not responsive.

### ISSUE THREAD

**Issue by sourabhdattawad** [viewflow/django-material#36]
Hi admin,

Forms aren't responsive and are aligning out of the screen when viewed on mobile. I tried everything I could. I haven't changed any CSS and followed the forms code you provided here.

**Comment by kmmbvnr** [comment]
Did you check the demo? Ex: http://forms.viewflow.io/demo/hospital/

It's responsuve on your browser? What mobile browser do you use?

**Comment by sourabhdattawad** [comment]
I use chrome. Forms are center aligned in normal view, but they move out of the screen when the size of the browser is shrunk. Please check the images attached. Thanks!
![screenshot from 2015-08-14 23 43 33](https://cloud.githubusercontent.com/assets/8778050/9280879/f50fdb9e-42de-11e5-8fe8-f475e0699aa3.png)
![screenshot from 2015-08-14 23 43 51](https://cloud.githubusercontent.com/assets/8778050/9280909/27791136-42df-11e5-8621-e7fe9a13c133.png)

**Comment by kmmbvnr** [comment]
Could you post screens from our demos? forms.viewflow.io

**Comment by sourabhdattawad** [comment]
This worked perfectly fine. I linked the all the CSS with forms.viewflow.io. 
![screenshot from 2015-08-15 12 06 42](https://cloud.githubusercontent.com/assets/8778050/9287794/26c9e118-4346-11e5-8621-5ef373f9725b.png)

**Comment by kmmbvnr** [comment]
So. It's a problem in you code. Take a look is your forms container resized properly.
