### ISSUE TITLE
django 2 admin

### ISSUE THREAD

**Issue by hone5t** [viewflow/django-material#361]
Hi does this still support admin interface in django2
is there any change to the latest master branch prevent that from working
it use to work fine in django1 but i am having difficulty making it work in django2

**Comment by kmmbvnr** [comment]
Django 2.0 admin is responsive and has a flat theme. So I see no reasons to port django-material admin to the django 2.0

Instead, django-material frontend going to be a complete admin replacement.

I'm working on this in the v2 branch.
