### ISSUE TITLE
Release for django 2.0 support

### ISSUE THREAD

**Issue by gogson** [viewflow/django-material#367]
Looks like in https://github.com/viewflow/django-material/commit/e67bed5a4b44bc11c7a058cd034be281830c5848 Django 2.0 is now supported but do we have a new release date for django-material ? Django 2.0 went live a few days ago

**Comment by kmmbvnr** [comment]
Django-material/Viewflow opensourced and pro versions with django 2.0 support would be available at the December or early January next year.

**Comment by jpic** [comment]
Hi !

I'm using the master branch, trying to enable the admin design, is it gone in favor of the frontend system ?

Thanks ;)
