### ISSUE TITLE
fn.autocomplete conflicts with jQuery.ui

### ISSUE THREAD

**Issue by joseamaya** [viewflow/django-material#368]
I'm using django-material y jQuery Ui in the same project but i'm having problems: the name of the function autocomplete conflicts with similar name function in jQuery UI, as $.fn.autocomplete is too generic and i suggest be changed to materialize_autocomplete.

Thanks!

**Comment by kmmbvnr** [comment]
that's a problem of underlining MaterializeCSS library. See https://github.com/Dogfalo/materialize/issues/4567
