### ISSUE TITLE
[QUESTION] Django 2 compatibility

### ISSUE THREAD

**Issue by oiacrasec** [viewflow/django-material#369]
Hello, is the project compatible with django2?

**Comment by kmmbvnr** [comment]
Duplicate #367

**Comment by jpic** [comment]
Using the forms part in Dj2 with Jinja2 without issue ;)

**Comment by jpic** [comment]
Do you know when you're going to make a new pypi release ?

Are you going to wait until all viewflow supports dj2.0 or are you making a release with just partial dj2.0 support for material frontend users ?

Thanks <3

**Comment by kmmbvnr** [comment]
In order not confusing users, django-material released only with viewflow.

**Comment by kmmbvnr** [comment]
1.2.0 and 1.2.0.pro released.

At that time, I've got no response form djangopackages site maintainers ;(
