### ISSUE TITLE
Drop admin styling

### ISSUE THREAD

**Issue by kmmbvnr** [viewflow/django-material#373]
Unfortunately, i can't no longer support django-material admin custom theme.  But it's not so bad

- Django 2.0 got responsive mobile interface. 
- There are a lot of issues in the django-material [admin customization](https://github.com/viewflow/django-material/issues?q=is%3Aissue+is%3Aopen+label%3Aadmin)
- No paying customer interest in the custom admin

I going to spend more efforts on the material.frontend improvements. Frontend going to be complete, more flexible and customizable django-admin replacement.

--

- [x] drop admin templates
- [ ] remove django-material from admin-styling grid on djangopackages

**Comment by kmmbvnr** [comment]
admin dropped https://github.com/viewflow/django-material/commit/06490c4eb37e7f9a66f97965fa0f4caf26506e61

**Comment by kmmbvnr** [comment]
Got no response from djangopackages maintainers :(

**Comment by bendavis78** [comment]
Might I suggest forking the admin templates into a separate project? There may still be interest in the community to keep this going, and it might be easier to maintain as a separate project.

**Comment by andrewyager** [comment]
Kinda sad - we were using the admin site integration.

**Comment by moorchegue** [comment]
Have anyone picked up on where this was dropped off? django-material was a decent admin interface, which was dealing with far more than just styling. It would be a shame that'd be lost forever.

**Comment by tammyalexandra** [comment]
Late to upgrading our dependencies and v. sorry to see material. admin go.

**Comment by shayneoneill** [comment]
Ah goddamn it. Why drop the bit that people use?! Pretty much everything else material  can be done via bootstrap material. It was the integration with admin that was the pain point :(

**Comment by shayneoneill** [comment]
God I feel like I'm back in javascript hell again, where you build something then a major framework just disappears. This is not how pythons supposed to be!

**Comment by andreportela** [comment]
People are still looking for this.
