### ISSUE TITLE
bug: safari search filter

### ISSUE THREAD

**Issue by iamike** [viewflow/django-material#374]
search filter wont work at safari, but it works fine at chrome, 

my mac/safari 11

**Comment by kmmbvnr** [comment]
Is it about admin or frontend part?

**Comment by iamike** [comment]
yes, it is.

**Comment by kmmbvnr** [comment]
Where is the search filter you talking about?

**Comment by iamike** [comment]
admin section

**Comment by kmmbvnr** [comment]
Unfortunately, admin already dropped, so this won't be fixed. See #373

**Comment by iamike** [comment]
when you click enter, the browser didn't trigger the event
