### ISSUE TITLE
Regular donation

### ISSUE THREAD

**Issue by jpic** [viewflow/django-material#375]
Hello !

Is there any way we can make a monthly donation to thank you for django-material development ? Materializecss has patreon and we're sponsoring :guitar: 

Note: we're not using any viewflow pro software so we're not buying anything from your company so far, hence my question.

Thanks

**Comment by kmmbvnr** [comment]
No. Django-material has separate commercial licence. Django-material v2 going to be AGPL licenced, that would help to sustain that project.

**Comment by jpic** [comment]
Thanks, got viewflow pro, I thought it was 450$/month :rofl: 

Got my material frontend pro license ;)
