### ISSUE TITLE
Javascript API

### ISSUE THREAD

**Issue by jpic** [viewflow/django-material#376]
Can we discuss a JS api for users who use something else than turbolinks ? Currently, the init/destroy functions are not exposed in any reusable global.

Also, would it be possible to enable/disable features from the init/destroy functions ? Ie. keep every

For the moment we're using a forked override of material.forms.js which is ok because it's a small script but it would be great to have a more upgrade-friendly solution in the future.

Would you be interested in reviewing design proposals ?

**Comment by kmmbvnr** [comment]
V2 branch addresses this issue by switching to google-mdc. Google library has standard in init/destroy live-cycle. And auto activation from `data-...` attribute.

**Comment by kmmbvnr** [comment]
So the problem not in turbolinks by itself. But in the missing component model and component live-cycle.

Without turbolinks this would arises in the dynamic form parts (ex formset add)

And generally, complex frontend requires some sort of components for js and css. Google-mdc addresses both issues with BEM for css, common Es6 base class for js component, and standard for component auto-wiring

https://github.com/material-components/material-components-web/blob/master/packages/mdc-auto-init/README.md

**Comment by jpic** [comment]
Thanks !

Found it: https://material.io/components/web/catalog/auto-init/

It's great ! Is v2 also using materializecss ?

Do you think we can switch to v2 right now if we're just using the forms part of django-material ?

**Comment by kmmbvnr** [comment]
V2 would be google-mdc based (but still with jQuery 3d-party  components)

I'm expect v2 open source would be useful around February 2018, and pro at April. 

Currently v2 only has textinput/checkbox/select widgets implemented.

**Comment by jpic** [comment]
Found my answer: "This is django-material version 2 rewrite, replaces MaterializeCSS library with Google MDC. Work in progress."

Thanks !
