### ISSUE TITLE
How to activate CRUD scaffolding in frontend ?

### ISSUE THREAD

**Issue by jpic** [viewflow/django-material#380]
With django-material v1 (master)

After following the documentation on http://docs.viewflow.io/material_frontend.html

In our apps.py:
```
from django import apps
from material.frontend.apps import ModuleMixin

class MRSRequestAppConfig(ModuleMixin, apps.AppConfig):
    name = 'mrsrequest'
    icon = '<i class="material-icons">flight_takeoff</i>'
```

Loads properly (with proper default_app_config):

```
In [1]: from django.apps import apps

In [2]: apps.get_app_config('mrsrequest')
Out[2]: <MRSRequestAppConfig: mrsrequest>


```

In our app urls mrsrequest/urls.py:

    urlpatterns = [ 
    path(
        '',
        generic.TemplateView.as_view(template_name='mrsrequest/index.html'),
        name='index'
    ),
    ]

In ROOT_URLCONF:

          path('', include(frontend_urls)),

This doesn't create any of the "CRUD scaffolding build with django class based views", only the index url is defined. Is there anything else to do to add CRUD ? Perhaps register the model ?

Thanks !

**Comment by kmmbvnr** [comment]
I'm not sure that I correctly understand the question.

Django-material has a quickstart guide, you can just follow it http://docs.viewflow.io/material_frontend.html

You can generate a sample code with `./manage.py startmodule appname`

**Comment by jpic** [comment]
Yeah I think I just need to add a viewset, thanks !
