### ISSUE TITLE
Documentation is damaged

### ISSUE THREAD

**Issue by voronov007** [viewflow/django-material#381]
Example http://docs.viewflow.io/viewflow_rest_activation.html
Lots of pages are empty.
Also, admin section was removed

**Comment by kmmbvnr** [comment]
thanks, i'm working on v1.2 release right now that cause the issue.

But admin section is really dropped #373

**Comment by voronov007** [comment]
I have copied `base.html` for admin from this file https://github.com/viewflow/django-material/blob/67944bda11dfc6a66d20a11339df484297e1d2ae/material/admin/templates/admin/base.html and paste in my project. Currently, django material admin looks good for me. What admin issues should I aware? Thanks in advance.

**Comment by kmmbvnr** [comment]
All closed bugs listed in the #373 (and unknown amount of new happens under django 2.0)

**Comment by kmmbvnr** [comment]
REST docs fixed
