### ISSUE TITLE
Auth ViewSet

### ISSUE THREAD

**Issue by jpic** [viewflow/django-material#383]
Hello !

Thanks for sharing this fantastic app !

Is there an open source ViewSet available for to manage auth.User (with set password like in django admin) or can this be contributed upstream ?

Thanks

**Comment by emihir0** [comment]
The only reason I still use admin is to manage existing users, so if we could have a built in ViewSet for default User which we can adjust to our needs - that would be just perfect.

**Comment by ivdmitriev** [comment]
If it is possible for you, you can try to create `./templates/account/base.html`, extending `material/frontend/base_lockscreen.html`.

```
{% extends "material/frontend/base_lockscreen.html" %}
```
