### ISSUE TITLE
Materialize datepicker ?

### ISSUE THREAD

**Issue by jpic** [viewflow/django-material#385]
Currently, django-material provides jquery.datepicker but materialize ships a datepicker widget, is it ok to switch to the materialize one which seem to have better mobile UX ?

Thanks a lot for sharing this app it's the best CRUD of 2017 <3

**Comment by kmmbvnr** [comment]
I never used Material picker, b/c it seems completely keyboard unfriendly.

In v2 would try to make some 3d party material datepicker available by clicking on the calendar icon and masked text-input for keyboard input.  On the mobile native `<input id="datetime" type="datetime-local">` would be used.

**Comment by emihir0** [comment]
It would also be great if we could control the date/datetime picker's options directly in the widgets you will provide, such as showing time intervals in every 30 minutes.

**Comment by MickaBar** [comment]
Hi,
Thx for this package.

Like emihir0 suggest, it would be nice to get the **ability to control init options**.

Cheers !

**Comment by jpic** [comment]
We use native datepicker which has better mobile support, it's [pretty simple really](https://github.com/betagouv/mrs/blob/master/src/mrs/forms.py).
