### ISSUE TITLE
Django material not working on production

### ISSUE THREAD

**Issue by jackquin** [viewflow/django-material#386]
```
INSTALLED_APPS = [
    'material', 
    'material.admin',
    'django.contrib.admin',
```
also here its my TEMPLATE

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```
i added django-material to installed apps and there is my requirements.txt for production

```
Django>=1.8,<2.
mysqlclient
django-crispy-forms
django-simple-history
django-ckeditor
gunicorn==19.7.1
gevent==1.2.2
django-filter
django-widget-tweaks
django-material

```
what is the problem my django material its working on local but not working on the production.(AWS)

**Comment by kmmbvnr** [comment]
It's unclear, what do you mean by "not working" Do you have an exception?

Did you run collectstatic/migrate etc?

**Comment by jackquin** [comment]
yes i did collectstatic and migrate. When i publish to server django-admin theme always coming default admin template not material theme but in my local django-material working fine. I'm wondering it can be about my django version or material version ?

**Comment by kmmbvnr** [comment]
Yep, see the changelog

**Comment by jackquin** [comment]
What version should be for django material and django-admin ? Which is the stable with each other

**Comment by jackquin** [comment]
Thx for help its all about django-material versions :+1:
