### ISSUE TITLE
Django 2.0 support?

### ISSUE THREAD

**Issue by KevinMind** [viewflow/django-material#387]
Admin material is not working. I don't seem to have any issues, it just does not work. 

I see django 2.0 support released 10 days ago. Are we still following the same install and setup instructions as mentioned here http://forms.viewflow.io/ ??

I'm using pipenv, I get no dependency conflicts. Here is my pipfile.
NOTE: I've tried the same install setup using django 1.11 and django-material 1.1.0 and it worked, as long as you don't install graphene-django, but this led me to believe the issue is with django-material / django versions and not other features of my setup.

djzen = "*"
dj-database-url = "*"
"psycopg2" = "*"
graphene-django = "*"
djangorestframework = "*"
django-filter = "*"
markdown = "*"
django-cors-headers = "*"
graphene = "*"
django-uwsgi = "==0.2.1"
django = "==2.0"
django-material = "==1.2.0"
names = "*"
requests = "*"

git clone https://github.com/KevinMind/django-crm.git to see issue. I get NO ERRORs... just no beautiful material.. :(

**Comment by kmmbvnr** [comment]
Please read the changelog and #373

But yes, fresh version of Forms.viewflow.io need to be deployed.

**Comment by kmmbvnr** [comment]
forms.viewflow.io updated, admin demo removed.
