### ISSUE TITLE
Make list_actions consistent between ModelViewSet and ListMovelView

### ISSUE THREAD

**Issue by emihir0** [viewflow/django-material#388]
`ModelViewSet` accepts list of tuples in format:

```
list_actions = [
    ('Delete objects', DeleteView)
]
```

Whereas the `ListMovelView` accepts in format:

```
list_actions = [
    ('Delete objects', 'delete_view_url')
]
```

A relatively easy fix should be to simply move the `_get_actions`, `get_action_view_kwargs` and `get_action_view` from `ModelViewSet` into `ListMovelView` because as default `ModelViewSet` uses `ListMovelView` as its `list_view_class` anyway. This would make it possible to use `list_actions` in `ListMovelView` with passing the view directly into it, rather than reversing the url regardless of whether the `ListMovelView` is used from `ModelViewSet` or independently.

EDIT:
Additionally, it would be nice to have `template_name` default to `{model_name}_action_{action_name}.html` (through `get_template_names`)
  
EDIT 2:
A `has_action_permission` should be added to `BaseActionView` which defaults to not requiring any permission. This makes it easy to e.g. restrict delete action to people with model's `can_delete` permission (which makes sense).

**Comment by kmmbvnr** [comment]
There is no ListViewSet in the django-material

**Comment by emihir0** [comment]
Sorry, I meant `ListMovelView` (edited my post).

**Comment by kmmbvnr** [comment]
Action views listed in the view, would not be mapped to url config

**Comment by emihir0** [comment]
I do realise that the `ListModelView` does not have `urls` property, but there has to be a way to make this work, but surely there has to be a way where this can be automated? It is very convenient to be able to do `list_actions = [('action name'), view]` without having to add the view into urls. 

Maybe the `urls` that handle this in `ListMovelView` could be moved into `BaseViewset`, such that we could look at each `_view` and see if it has `list_actions` (usually it would have 1 in its `ListModelView`, but there can be multiple `_view`s that use `list_actions`). This should not break any current behaviour and all the functionality can be moved now to `ListModelView`.

This makes it so that we can pass the same parameters into both `ListModelView` and `ModelViewSet`, which makes it consistent and easy to document.

However, this wouldn't help with url config of `ListModelView` that is not used by `ModelViewSet`.

**Comment by kmmbvnr** [comment]
>> However, this wouldn't help with url config of ListModelView that is not used by ModelViewSet

Yep, that's inconsistent and hard to document

**Comment by emihir0** [comment]
The point is that right now both `[ListModelView](http://docs.viewflow.io/frontend_crud.html#material.frontend.views.ListModelView)` and `[ModelViewSet](http://docs.viewflow.io/frontend_crud.html#material.frontend.views.ModelViewSet)` both have the same documentation for `list_actions`. Either the documentation should be changed, or the behaviour should be made consistent. It is easier to use the view directly as a parameter, rather than reversing a url, and so, ideally, both `ListModelView` and `ViewModelSet` should use `list_actions` that accept a list of tuples `('Action Name', ActionView)`

**Comment by kmmbvnr** [comment]
Yep documentation would be changed.

**Comment by emihir0** [comment]
Btw I've made a second edit in my OP. Please add `has_action_permission` as this should be very trivial to add and it would be extremely useful.

**Comment by kmmbvnr** [comment]
V2 already handles permission for generic pages actions. Same logic would be for row bulk actions https://github.com/viewflow/django-material/blob/v2/material/views/viewset.py

**Comment by kmmbvnr** [comment]
Btw adding has_perm is not trivial, since just adding it, would not prevent access to action by direct url.

**Comment by emihir0** [comment]
I see, my bad, I still use `django-material-pro==1.1.3`. I see that you've also added `list_page_actions` and such, which is really, _really_ nice. I'm glad you are extending material frontend heavily.

And yes, I do realise that they would be still accessed through direct url, but the direct url is still a request to the ActionView and so all that is required is to handle it in `dispatch` method (or both `get` and `post` methods), no? I might be wrong though.

**Comment by kmmbvnr** [comment]
V2 is not released yet.

To get action permission check In V1.2 you can define ListView.list_actions as property and use self.request.user to filter list actions.

**Comment by kmmbvnr** [comment]
I'm closing this, since the issue goes far away from original request.
