### ISSUE TITLE
Django 1.8 admin template rendering error

### ISSUE THREAD

**Issue by matthewpull** [viewflow/django-material#39]
After following the steps on the docs (http://docs.viewflow.io/django_material.html), I get the following error when using Django 1.8:

AttributeError at /admin/
'str' object has no attribute 'user'
Request Method:	GET
Request URL:		http://localhost:8000/admin/
Django Version:	1.8.3
Exception Type:	AttributeError
Exception Value:	'str' object has no attribute 'user'

The debug page says that the occurs in line 60 of 'material\admin\templates\admin\base.html', which reads:
`{% get_app_list request as app_list %}`

Looking into the issue further, I have noticed that the error is actually in line 25 of 'material\admin\templatetags\material_admin.py', which reads:
`user = request.user`

This is an issue, as the variable 'request' contains no value at that point.

Please can you advise how to fix this error.

Thanks,
--Matt

**Comment by kmmbvnr** [comment]
Read the doc again. You missed adding request context process setting
