### ISSUE TITLE
Search fields in Frontend ListView (DataTableMixin is not compatible)

### ISSUE THREAD

**Issue by SalMax** [viewflow/django-material#395]
Hello! 

It's possible to add search fields in frontend listview? I think that there is a problem in DataTableMixin or in ListView.html js code. I am a pro user.

I have been doing tests with Datatable, for example enabling `searching' : true` in datatable_config, but it does not work. It seems to be a problem with data pagination or similar (not sure sorry)

I'm right? Are you planning to resolve this? I think search fields is a must have feature in this great app. 

Thank you in advance

**Comment by kmmbvnr** [comment]
I, see no problem with `searching: true` option

django-material uses ajax server-side datatable rendering mode. You've got search value in `request.GET['datatable-search[value]']` and should process in your view
