### ISSUE TITLE
Select field not being rendered

### ISSUE THREAD

**Issue by darahsten** [viewflow/django-material#397]
![material_select_form](https://user-images.githubusercontent.com/7501274/35625415-f7a76872-069a-11e8-993d-b53f5c3dc8b7.png)
Material form is not is not displaying select fields in django forms. This might be related or resulting from the issue that materialize requires select to be explicitly initialized since it overrides the browser defaults see [SO](https://stackoverflow.com/questions/28258106/materialize-css-select-doesnt-seem-to-render).
The recommended  solution does not work for me. 
![error_js](https://user-images.githubusercontent.com/7501274/35625840-762ee6a6-069c-11e8-91f1-2a52050b454e.png)
Trying to initialize the select. 
This is the case even when I include the materialize css cdn js.

**Comment by kmmbvnr** [comment]
The provided error log screenshot is incomplete.

**Comment by darahsten** [comment]
Hi @kmmbvnr , that is end of the error log. as you can see the function material_select is not found.
There is nothing else related to this that shows up as error. The start trace ends in minified js code. Have you seen the Stackoverflow related question I referenced.

**Comment by kmmbvnr** [comment]
Can you show the full stacktrace?

**Comment by darahsten** [comment]
@kmmbvnr, No I cant show a stack trace, that is a javascript error. That is all the stacktrace there is. Nothing else to be found. Please take a look at the related stack over flow question I am referencing. In fact The section of code causing that error`<script>
  $(document).ready(function() {
    $('select').material_select();
});
</script>`
probably has got nothing to do with django material. As it is a recommendation about materialize not rendering the Select.

**Comment by kmmbvnr** [comment]
I think it's caused but misuse the js code. But it's hard to diagnose it from trimmed stack trace.

Since, the reference demo works fine, I'm closing the issue.

**Comment by darahsten** [comment]
Hey @kmmbvnr , Can you point me to the reference demo showing using a select field. I will be very greatful because that error is in actuallity manufactured it should not exist. I don't believe we communicated on the same page.
