### ISSUE TITLE
Django 1.11.9 admin template rendering error

### ISSUE THREAD

**Issue by joelalves** [viewflow/django-material#399]
Hello, i am to have one error
django 1.11.9
python 3.5

I'm to add on custom view on django admin [view code](http://collabedit.com/53cxu)
but i am to hava this error [view error](http://prntscr.com/icmuil)

**Comment by kmmbvnr** [comment]
Probably that means that you have no `request` in the admin template context.

Please also note that admin was removed recently (#373)
