### ISSUE TITLE
Forms with images do not submit - Validation Error

### ISSUE THREAD

**Issue by e911miri** [viewflow/django-material#4]
![screen shot 2015-04-06 at 9 56 00 am](https://cloud.githubusercontent.com/assets/710643/7002480/3a9ea9fe-dc43-11e4-96bc-40b6bd44d94d.png)

**Comment by kmmbvnr** [comment]
Is it image file field?

**Comment by e911miri** [comment]
Hi there, thanks for responding in time.

Yes, it is an image field

**Comment by e911miri** [comment]
Yes, It is
