### ISSUE TITLE
validation error for choice field appears at the top left page

### ISSUE THREAD

**Issue by snjain** [viewflow/django-material#403]
Hi,

  I am using django viewflow for one of the projects that I am currently working on. Here are the different versions.

pytz
django==1.11.6
django-material==1.1.0
django-viewflow==1.1.0

  In my form, I am using choice fields without any initial values. When I click on submit button, the validation error message (only for choice fields) - 'Please select an item in the list'' getting displayed  at the top left corner of the page instead of getting displayed near the choice fields.

This is confusing if there are  many choice fields in the form.

Can you please advise what could be the root cause for this issue?

**Comment by kmmbvnr** [comment]
Closed. No OP activity

**Comment by Shailendranjain** [comment]
Sorry for the delay in responding.

Looks like the issue was happening when I was doing form field alignment in html file.

            <div class="row">
                {{ form.field1 }}
                {{ form.field2 }}
                {{ form.field3 }}
            </div>

When I used the below approach of formatting the form fields in forms.py, the issue went away.

    class SomeForm(forms.ModelForm):
    layout = Layout(
                    Row('field1', 'field2', 'field3'),),
