### ISSUE TITLE
DOMContentLoaded isn't fired after page load

### ISSUE THREAD

**Issue by mathpaquette** [viewflow/django-material#405]
I need to wait for the DOMContentLoaded event to execute some js code on some pages. I have realized that when I click on menu subitem (not the default one. as you can see on the screenshot), DOMContentLoaded isn't getting raised. Are you aware of this and what's the event that I should hook on to make sure that my javascript code is ran?

Thank you for your help.

![image](https://user-images.githubusercontent.com/4358455/37969706-656250c8-319f-11e8-9925-57872975ee70.png)

**Comment by kmmbvnr** [comment]
Yep, frontend based on the turbolinks, so 'turbolinks:load' fired instead
