### ISSUE TITLE
material.admin doesn't work on version 1.2

### ISSUE THREAD

**Issue by KyrychukD** [viewflow/django-material#406]
## Steps to reproduce

1. Download and unpack [test_material.zip](https://github.com/viewflow/django-material/files/1865897/test_material.zip)
1. Run `pip install -r requirements-latest.txt`
1. Run `./manage.py runserver`
1. Navigate to http://127.0.0.1:8000/admin (username: `demo`, password: `demodemo`)

**Expected result**: admin site looks differently from default.
**Actual result**: admin site looks exactly the same as if there were no `material.admin` listed in `INSTALLED_APPS`.

The issue is reproducible on Django 1.11 as well (`pip install -r requirements-latest-django1.txt`).
The issue is **not** reproducible on django-material 1.1 (`pip install -r requirements-working-admin.txt`).

**Comment by kmmbvnr** [comment]
Yep, check the changelog.

**Comment by KyrychukD** [comment]
Oh, I see. I did not expect major features to be removed in a minor release, so I assumed this could be a regression.
