### ISSUE TITLE
Filtering datatable causes visual glitch.

### ISSUE THREAD

**Issue by emihir0** [viewflow/django-material#408]
Please see this gif:
https://i.imgur.com/AB2cf5T.gif

When the datatable is filtered, the data in first row shifts all the way to the last (right) column. 
This did not happen in v 1.1.x version.

**Comment by kmmbvnr** [comment]
Yeah. I don't think this can be fixed. Django-material 2.0 going to drop datatables and use plain html table instead to avoid visual glitches.

**Comment by emihir0** [comment]
I see. Well, I hope the html tables will be rendered through AJAX or some async method - because the datatables were really nice in this regard.
