### ISSUE TITLE
Selecting an item in datatable, going to next page and trying to perform action - the action is not performed on the item from previous page.

### ISSUE THREAD

**Issue by emihir0** [viewflow/django-material#409]
If we select an item on page 1 of datatable, go to page 2 and select 1 more item, then try to perform action (e.g. delete), the action is performed only on the 1 item from second page.

See:
https://i.imgur.com/apEHsr8.gif

**Comment by kmmbvnr** [comment]
Gmail interface works same

**Comment by emihir0** [comment]
Really? I'm quite sure this was working as 'expected' in version 1.1.x thought.

It would really be a good feature to have; maybe it's possible to implement through saving the selected items on client side?

**Comment by kmmbvnr** [comment]
I don't know the answer on this.

**Comment by emihir0** [comment]
There must be a reason why this worked in 1.1.x django-material version and no longer works now? Surely this can be reverted.

**Comment by kmmbvnr** [comment]
I don't remember is worked or not, django-material just updated with latest dependencies. Some of them could change something. There is no goal to keep this changes off the django-material.

**Comment by emihir0** [comment]
Sigh, that makes me sad because we have a lot of PDF outputs that rely on being able to select multiple items from multiple pages. These PDF outputs have very useful/important summaries at the end and so it's not just about printing 1 page instead of 2, it's also about summarising the data.

Can you at least point me to where should I look to try and fix this?

**Comment by emihir0** [comment]
I've made a bit of research and this is definitely a bug and it definitely worked before the update.

This is server side processing of datatables checkboxes plugin: https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/server-side/server-side-processing/

It gets the selected checkboxes in the same way it is done in django-material, ie. `datatable.column(0).checkboxes.selected();`

Similarly, when you try to select all checkboxes through js, ie:
`$('#table').DataTable().column(0).checkboxes.select();`, it selects only the current page (on http://demo.viewflow.io/integration/city/), whereas it selects ALL of the pages on https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/server-side/server-side-processing/.

This really should be fixed, it's an important feature. Being able to select only current page leads to too much unexpected behaviour for the user.
