### ISSUE TITLE
Multiple files upload not working

### ISSUE THREAD

**Issue by fabriciojoc** [viewflow/django-material#411]
https://github.com/viewflow/django-material/blob/1a1a5521665a17a5d19519cadce1ff8dd36504c4/material/templates/material/fields/django_fileinput.html#L9

Multiple files upload is not working. The solution found [here](https://github.com/luminousmen/django-material/blob/ed80b9575d66123bfd35f78ba21947e72f7c74ce/material/templates/material/fields/django_fileinput.html) is not implemented in the repository.

**Comment by kmmbvnr** [comment]
Fixed in c1de382d0af15aef977880fa158ea0eb69b560c9
