### ISSUE TITLE
How can i use for loop inside form tag?

### ISSUE THREAD

**Issue by nikolaysm** [viewflow/django-material#412]
Hallo,

Example:

```
{% form %}
{% attr form.email 'widget' class append %}red-text{% endattr %}
{% attr form.username 'widget' class append %}red-text{% endattr %}
{% attr form.password1 'widget' class append %}red-text{% endattr %}
{% attr form.password2 'widget' class append %}red-text{% endattr %}
 {% endform %}
```

I would like to use for loop instead manually calling each field.
```
{% for field in form %}
{% attr field 'widget' class append %}red-text{% endattr %}
{% endform %}
```
So i get `Invalid block tag on line 39: 'endform', expected 'endblock'. Did you forget to register or load this tag?`

I would also add a feature to remove attribute.`{% attr form.field 'widget' class  remove %}{% endattr %}`

Thanks

**Comment by kmmbvnr** [comment]
There is no such functionality in django-material
