### ISSUE TITLE
Modals don't open at http://demo.viewflow.io/materialforms/pro/signup/

### ISSUE THREAD

**Issue by mbaechtold** [viewflow/django-material#414]
Where can I find the Python and HTML source of the demo example at http://demo.viewflow.io/materialforms/pro/signup/ ?

The problem is, that the modals containing the source code (box in the right column) don't open.

**Comment by emihir0** [comment]
It seems that the modals are not opening properly for the python and html code. Go to the [website](http://demo.viewflow.io/materialforms/pro/signup/), open console and run `$('#python').modal('open')`. This will open the modal for the python code. Run `$('#html').modal('open')` for HTML code.

**Comment by kmmbvnr** [comment]
Thanks for noticing. Fixed.
