### ISSUE TITLE
DecimalField with input type number has separator comma

### ISSUE THREAD

**Issue by lukasgarcya** [viewflow/django-material#42]
I have my LANGUAGE_CODE with pt-br and the tag html language has en-us then my field has value decimal with comma separator. When I use django admin without material the value show normal in form but the material not is showing.

**Comment by kmmbvnr** [comment]
i hope it fixed with 55b3e0c789fbf3916daa77118106d5df50e55e45

**Comment by lukasgarcya** [comment]
Eu testei com a solução que eu mesmo criei no qual o valor está vindo com a virgula então não apresenta o valor ao editar.
Caso crie um model com campo decimal tendo vírgula(34,33) na edição o valor volta com 34,33 no campo DecimalField sendo que o Django Admin padrão retorna 34.33 para que o field seja editado.
