### ISSUE TITLE
django admin not working in django 1.11.15 and django-material>1.1.1

### ISSUE THREAD

**Issue by p02diada** [viewflow/django-material#422]
I am not able to work properly the django admin with an uppern version than 1.1.1. Version 1.1.1 are correct.

![image](https://user-images.githubusercontent.com/6508269/44872024-c7ade600-ac94-11e8-91f6-e8703fe2d811.png)

![image](https://user-images.githubusercontent.com/6508269/44872067-e1e7c400-ac94-11e8-8de9-5d8f957ce42d.png)

**Comment by kmmbvnr** [comment]
Admin part was removed from django-material

**Comment by p02diada** [comment]
is there a replacement or is not longer support?

**Comment by kmmbvnr** [comment]
Django-material frontend is the replacement for crud interfaces.

**Comment by jsenecal** [comment]
Do you have a documentation on how to set this up ? I was relying on this for an app i'm building - perhaps update the docs and demo ?

**Comment by jsenecal** [comment]
Nevermind - #373
