### ISSUE TITLE
 Icon is not created automatically

### ISSUE THREAD

**Issue by Jinhee81** [viewflow/django-material#423]
I did the same thing as the example, but the icon is not created automatically
I want to create the icon.
What should I do?
(and I'm a Korean)

![image](https://user-images.githubusercontent.com/39583659/45066757-c77d7280-b0fa-11e8-8bc2-c87b327716b5.png)

**Comment by kmmbvnr** [comment]
Icons are not added automatically. You should list them in a template, ex:

```
<form method="POST">
    {% csrf_token %}    
    {% form %}
        {% part form.username prefix %}<i class="material-icons prefix">account_box</i>{% endpart %}
        {% part form.email prefix %}<i class="material-icons prefix">email</i>{% endpart %}
        {% part form.password prefix %}<i class="material-icons prefix">lock_open</i>{% endpart %}
    {% endform %}
    <button type="submit" class="btn">Submit</button>
</form>
```

**Comment by Jinhee81** [comment]
Thanks a lot! But I have not tried it yet. I'll try agian. ^^
