### ISSUE TITLE
Flow chart is not internationalised. 

### ISSUE THREAD

**Issue by emihir0** [viewflow/django-material#430]
Right now the cell names' text is drawn from the function names. I suggest to use `task_description` and in case it is `None` then default to the current behaviour. 

Ie.:
```
name = cell.node.task_description or cell.node.name
segments = wrap(' '.join(name.capitalize().split('_')), 20)
```
In line 517 file chart.py

We can set `task_description` to translatable string so this is a simple fix.

**Comment by kmmbvnr** [comment]
Fixed to use `task_title` if present
