### ISSUE TITLE
Updating Select with AJAX

### ISSUE THREAD

**Issue by zintj** [viewflow/django-material#431]
When using AJAX to populate a secondary select field based on what's selected in an initial one, it appears as if all the options are loaded correctly from the AJAX success function, and on a raw html page, the drop down appears to work. With material loaded however, the second select doesn't dropdown when clicked, it just show the top most option.

**Comment by kmmbvnr** [comment]
django-material based on the materilizecss library. So basically, you can just search questions for a materializecss.

https://stackoverflow.com/questions/29132125/how-to-dynamically-modify-select-in-materialize-css-framework
