### ISSUE TITLE
An invalid form control with name='educations' is not focusable.

### ISSUE THREAD

**Issue by nikolaysm** [viewflow/django-material#435]
When i submit form with required selectfields I get in browser this error "An invalid form control with name='educations' is not focusable." .

With materializecss it is working https://codepen.io/anon/pen/qJpqZr. (without additional js)

**Comment by kmmbvnr** [comment]
Can you reproduce it on demo.viewflow.io?

**Comment by nikolaysm** [comment]
No, I couldn't find any form in which html5 validation is used.
All forms are only used by side validation.

**Comment by kmmbvnr** [comment]
There is no plans to enable html5 validation

**Comment by nikolaysm** [comment]
A quick solution to add a css, but not the best solution.
```
.select-wrapper>select[required] {
    position: absolute !important;
    display: inline !important;
    opacity: 0;
    left: 50%;
    top: 50%;
    width: 0;
    height:0;
    margin: auto;
    padding: 0;
}
```
