### ISSUE TITLE
[PRO] Stacked Class is missing 

### ISSUE THREAD

**Issue by lino** [viewflow/django-material#439]
I can't quite reproduce it, but after installing material and material-pro, some parts are missing. For example the Stacked class or Filtersets. Is there any way to reliably install material pro?

**Comment by lino** [comment]
Now the class is back again, however others are missing:

ModuleNotFoundError: No module named 'material.frontend.apps'

**Comment by kmmbvnr** [comment]
Mm, that's hard to say what thing when wrong in your case.

Probably starting from fresh virtual environment could solve the issue. django-material-pro package is a complete replacement for open source version. Both packages should not be installed together.

Could you please contact over zendesk with detail steps and materail package versions that you used and the complete stacktrace.
