### ISSUE TITLE
Overflow hidden in filters

### ISSUE THREAD

**Issue by farantesrodrigues** [viewflow/django-material#44]
in https://github.com/viewflow/django-material/blob/master/material/admin/templates/admin/change_list.html  (line 56 - 75)

```html
    <div class="col s12 m4 l3">
        <div class="card filters" style="overflow: visible">
            <div class="card-content">
                <span class="card-title black-text" style="margin-bottom:20px">Filters</span>
                {% block search %}{% search_form cl %}{% endblock %}

                {% block filters %}
                {% if cl.has_filters %}
                <div id="changelist-filter row">
                    {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
                </div>
                {% endif %}
                {% endblock %}

                {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}
                <div class="clearfix"></div>
            </div>
            <div class="card-action">&nbsp;</div>
        </div>
    </div>
```

causes a problem to any `list_filter` that is sufficiently long to overflow the filters card content.

In images : 

We have this 
![screen shot 2015-10-30 at 17 37 40](https://cloud.githubusercontent.com/assets/1882468/10853263/14761c70-7f2d-11e5-8a03-9fe600cb18ac.png)

And we should have this :
![screen shot 2015-10-30 at 17 38 05](https://cloud.githubusercontent.com/assets/1882468/10853271/230d995c-7f2d-11e5-8921-8fdece3178d0.png)

I fixed it for the picture by inserting and inline style to `...<div class="card filters" style="overflow: visible">...` but I am not sure this is the most permanent solution to make the suggestion. Overflow is ordered to hide by the card class, from materialize.css.

```css
.card {
  position: relative;
  overflow: hidden;    <--- HERE
  margin: 0.5rem 0 1rem 0;
  background-color: #fff;
  border-radius: 2px;
}
```

Maybe declaring the filters class in https://github.com/viewflow/django-material/blob/master/material/admin/static/material/admin/css/base.css (line 240) would be best (it's currently used only by its children).

```css
.filters {
    overflow: visible;
}
```

**Comment by kmmbvnr** [comment]
already fixed in git
