### ISSUE TITLE
Is there a possibility to render form in view?

### ISSUE THREAD

**Issue by nikolaysm** [viewflow/django-material#441]
Now i render my form in view so:
```
template = Template("{% load material_form %} {% form form=form %}{% endform %}")
context = Context({"form": person_form})
rendered_form = template.render(context)
```

**Comment by kmmbvnr** [comment]
What is the scenario when it's needed?

**Comment by nikolaysm** [comment]
I use an ajax request to update or create an object. And then I want that Ajax Response returns a rendered form.

**Comment by kmmbvnr** [comment]
so to render a template is a correct solution in that case.
