### ISSUE TITLE
How to capture a parameter from the global urlconf?

### ISSUE THREAD

**Issue by anjomshoaa** [viewflow/django-material#443]
I am using material Frontend and need to have a prefix parameter for all urls. I have added this to the global urlconf module: 

`path('<city_view>/', include(frontend_urls)),` 

However, this is not allowed in modules because Frontend expects to have <app_module>/urls.py file, with a single no-parametrized url with name=’index’ . In my case <city_view> is passed to all Frontend urls. Could you please guide me how to solve this? 

Thanks,
Amin

**Comment by kmmbvnr** [comment]
You need to override ModuleMixin.index_url method in your apps.py.
