### ISSUE TITLE
MessageUserMixin on delete tries to create an invalid URL

### ISSUE THREAD

**Issue by mperesson** [viewflow/django-material#447]
Same problem was kinda describe in #286

In report() from MessageUserMixin class (material/frontend/view/mixins.py:143)

On delete it try to create a link to the deleted object.

On your demo, when you remove an employee, in the success message you have this URL:

> http://demo.viewflow.io/employees/employees/None/detail/

Since in my project I specify that the PK in the URL is an integer, I get a NoReverseMatch exception.

Trying to generate a link to a deleted object is absurd.

**Comment by kmmbvnr** [comment]
fixed https://github.com/viewflow/django-material/commit/e0bb2a99b65e8e739b9d44887f1a1b8ae03d5553
