### ISSUE TITLE
django-matrial version 1.5.2 - Select widget with SelectMultiple is too slow

### ISSUE THREAD

**Issue by Shailendranjain** [viewflow/django-material#448]
Hi,

   I am using the latest version of django-material and the select widget with SelectMultiple is too slow when the select options are greater than 100. (100+).

  Please advise if there is any work around for this issue.

Thanks,
Shailendra

**Comment by kmmbvnr** [comment]
Mm, I don't think it's related to django-material.

I could fill that issue for materialize css library, but generally, div-based select can't be super-performant on big datasets. And anyway it's not very user-friendly.

In that case ajax-based autocomplete would be better widget choice.

**Comment by Shailendranjain** [comment]
Thanks for adding this to the materialize css library.

Can you please advise which versions of materialize css library and django-material will have the fix for this ? 

fyi - I found the link below about the similar issue.

https://github.com/n4kz/react-native-material-dropdown/issues/97
