### ISSUE TITLE
issue with djcelery in admin panel: KeyError at /admin/djcelery/taskmeta/add/

### ISSUE THREAD

**Issue by auvipy** [viewflow/django-material#45]
Error during template rendering

In template /usr/local/lib/python2.7/dist-packages/material/templates/material/layout/fieldset.html, error at line 5
Key 'result' not found in 'TaskMetaForm'
1	{% load material_form_internal %}
2	<div class="section row">
3	    <div class="col s12">
4	        <h5>{{ parent.label|default:"" }}</h5>
5	
              {% for element in parent.elements %}
      {% render element %}
      {% endrender %}{% endfor %}

      
6	    </div>
7	</div>
8

**Comment by auvipy** [comment]
how to fix it?

**Comment by auvipy** [comment]
@kmmbvnr any help?

**Comment by kmmbvnr** [comment]
admin part of django-material is not complete and in the lowest priority.

**Comment by auvipy** [comment]
any suggestion where I can contribute regarding these?
