### ISSUE TITLE
Checkbox data in sessions

### ISSUE THREAD

**Issue by PythonMLC** [viewflow/django-material#450]
This is now really an issue, but more like a question but because I do not know where this should be asked, I put it here.

I am getting familiar with Django and MaterializeCC and I was having a challenge with checkboxes how to show them correctly. With this django-material they started to work. Great!

I am still having a problem that how with this setup I can store the checkbox data so that when next time visiting on page, the data is not lost. 

Any advice where to look or how is it made?

**Comment by kmmbvnr** [comment]
Unfortunately the question sounds a bit generic. Probably you need to start with Django tutorial to get onto models and forms processing https://docs.djangoproject.com/en/2.2/intro/tutorial01/

BTW Django Learning community is the great place to ask questions https://www.reddit.com/r/djangolearning/
