### ISSUE TITLE
Admin setup does not work

### ISSUE THREAD

**Issue by Abel-Moremi** [viewflow/django-material#451]
I followed these instructions(http://docs.viewflow.io/material_admin.html) to the T...  I am using 

- Django 2.2

- Python 3.6.4

after that instruction, nothing would take effect to errors simply nothing...

**Comment by Gabriel-Desharnais** [comment]
After a bit of reading I'm sad but here you go:
https://github.com/viewflow/django-material/blob/master/CHANGELOG.rst#120-2017-12-20

> Drop Material Admin

**Comment by Abel-Moremi** [comment]
@Gabriel-Desharnais  dude thanks... they need to adjust their website accordingly...
