### ISSUE TITLE
Material Frontend customization

### ISSUE THREAD

**Issue by x2x4com** [viewflow/django-material#452]
I want to add a custom menu to the topbar.
I check the document and found it(http://docs.viewflow.io/frontend_customization.html), but doesn't work.

```
{% block topbar_links %}
Additional links on the top bar:

{% block userlinks %}
<li>
  <a class="dropdown-button" href="#!" data-activates="user-menu">
       <i class="material-icons right">arrow_drop_down</i>Menu
  </a>
</li>
<ul id="user-menu" class="dropdown-content"  style="min-width:200px">
    <li><a href="#">Item 1</li>
    <li><a href="#">Item 2</li>
</ul>
{{ block.super }}
{% endblock %}
```

{% block userlinks %} 

There may be an error here. After changing to topbar_link, the menu drop-down box appears on the page, but the mouse click is not working, nothing happen. How can I make it effective?

**Comment by kmmbvnr** [comment]
Mm, yep, some custom js need to be added to initialize material css - https://materializecss.com/dropdown.html

Or HTML code could be wrapped into `<dmc-dropdown>` 

I've updated the docs to clarify this.
