### ISSUE TITLE
non-existing paths in sass/materialize.scss

### ISSUE THREAD

**Issue by tomas-zemres** [viewflow/django-material#454]
When I try to use "sass/materialize.scss" for build own css-style (using djang-sass-processor)

I have own "main.scss", it contains:
`@import "material/sass/materialize.scss"`

But compiling scss failed due to:
`"@import "materialize-css/sass/components/..."` in your materialize.scss

because this path does not exist in your package.

Nice would be If django-material package (installed using pip) contains also all "materialize-css" required for sass processesor to generate complete css file.

**Question 1:**
Why there are only some *.scss files are part of "django-material" package?

**Question 2:**
Why are the sass/* files exposed to public static directory in every django project installing "django-material"?

**Comment by kmmbvnr** [comment]
Materialize library could be installed with npm

**Comment by tomas-zemres** [comment]
And what about "question 2":

Why are the sass/* files exposed to public static directory in every django project installing "django-material"?

**Comment by tomas-zemres** [comment]
It

> Materialize library could be installed with npm

But I must manually synchronize correct version of "npm packages" vs. correct version of python package "django-material".

I have currently installed material-css from npm + material-design-icons, but It lead to duplicated files (css, js, fonts, ... ) in public static dir  - partially from  package "material/static" and partially from npm packages
