### ISSUE TITLE
FormAjaxCompleteMixin with custom queryset

### ISSUE THREAD

**Issue by Hacker-CB** [viewflow/django-material#467]
Why `FormAjaxCompleteMixin` uses `form.base_fields` instead of `form.fields`?

```
field = form.base_fields.get(options.get('field'))
```

Sometimes I need to specify custom queryset. And I have to modify `fields`  as well as `base_fields` property:

```python
class BusinessRegionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['manager'].queryset = ErpUser.objects.filter(Q(is_staff=True))
        self.base_fields = self.fields # <-- this I should use now

    class Meta:
        model = BusinessRegion
        fields = '__all__'
```

Seems that `FormAjaxCompleteMixin` should use `self.fields` instead of `self.base_fields`.
 
How do you think?

**Comment by kmmbvnr** [comment]
That's hard to remember why, but currently, I can't recall any problems with it.

Changed in django-material-pro==1.6.4
