### ISSUE TITLE
ajaxSelected on stacked layout

### ISSUE THREAD

**Issue by bdbais** [viewflow/django-material#469]
Good morning,
          I'm in trouble with django-material-pro with widget
AjaxModelSelect on a inline / formset layout, it give me this error:

The error is 400 on ajax request of search element:

127.0.0.1/:1 Unchecked runtime.lastError: The message port closed
before a response was received.
materialize.frontend.min.js:1 OPTIONS
http://127.0.0.1:8000/example/mymodel/add/ 400 (Bad Request)
send @ materialize.frontend.min.js:1
ajax @ materialize.frontend.min.js:1
getSuggestions @ materialize.frontend.min.js:1
onValueChange @ materialize.frontend.min.js:1
onKeyUp @ materialize.frontend.min.js:1
(anonymous) @ materialize.frontend.min.js:1
dispatch @ materialize.frontend.min.js:1
v.handle @ materialize.frontend.min.js:1
materialize.frontend.min.js:1 OPTIONS
http://127.0.0.1:8000/example/mymodel/add/ 400 (Bad Request)
send @ materialize.frontend.min.js:1
ajax @ materialize.frontend.min.js:1
getSuggestions @ materialize.frontend.min.js:1
onValueChange @ materialize.frontend.min.js:1
onKeyUp @ materialize.frontend.min.js:1
(anonymous) @ materialize.frontend.min.js:1
dispatch @ materialize.frontend.min.js:1
v.handle @ materialize.frontend.min.js:1
----------------

Could you help us to understand how to stack a widget inside a stacked elements?
Could you provide a working example with widget working on stacked layout ?
        Stacked(10, 'Stacked_Form'),

Bais

**Comment by kmmbvnr** [comment]
I think request error means that is something wrong with the response from backend.

You could check what your view returns on HTTP OPTIONS request.

For the PRO issues it's better to use zendesk on http://viewflow.io/contacts/
