### ISSUE TITLE
Department employees listview doesn't work

### ISSUE THREAD

**Issue by shadow3312** [viewflow/django-material#472]
The listview doesn't show any data on department/d1/employees. Can see the department on the employee detail view and even the employee count on the departments listview but nothing shows when you perform a click on the related link.

**Comment by kmmbvnr** [comment]
Can't confirm that - http://demo.viewflow.io/employees/departments/d002/employees/

![Cотрудники_Viewflow_Demo](https://user-images.githubusercontent.com/282529/81634692-47f88880-9431-11ea-8659-1521160260bc.png)
