### ISSUE TITLE
Bug 1.6.0 -> 1.6.3: After update forms submit to a wrong routes

### ISSUE THREAD

**Issue by alex20465** [viewflow/django-material#473]
https://github.com/viewflow/django-material/commit/c525e9578dd8126581f806001721ff1609e7c2d5#diff-f4d3a6d290858d0bb8b34ee5bb6c0f0bR44

![image](https://user-images.githubusercontent.com/4742067/79358795-5d6db600-7f4a-11ea-9782-1f63fbe0aa6f.png)

The _performPost was changed and leads to a wrong post-url:

Mostly the current `location.search` is an empty string "" the code above sets it to `.` which is a relative notation and transforms the url and makes it invalid, check the miss-behaviour:

![image](https://user-images.githubusercontent.com/4742067/79358902-868e4680-7f4a-11ea-87f4-a2e784c251ed.png)

**Comment by kmmbvnr** [comment]
Don't you have APPEND_SLASH==True? https://docs.djangoproject.com/en/3.0/ref/settings/#append-slash

**Comment by alex20465** [comment]
APPEND_SLASH is enabled, but you have right, the route path was without a slash at the end:
```python
    path('add/event', service_assignment_create_view, name="service_assignment_add_event"),
```
I've just changed it to:

```python
    path('add/event/', service_assignment_create_view, name="service_assignment_add_event"),
```

and it worked. thanks
