### ISSUE TITLE
Please update the material font version

### ISSUE THREAD

**Issue by geemang2000** [viewflow/django-material#479]
Are you planning to upgrade the material icons? I'm trying to use icons from https://material.io/resources/icons/?style=baseline that do not work with the old version.

**Comment by kmmbvnr** [comment]
Seems material-icons package was not updated for a while, but we could switch to https://www.npmjs.com/package/material-design-icons-iconfont

**Comment by geemang2000** [comment]
that the great!

**Comment by geemang2000** [comment]
Thanks! I'm a viewflow pro owner.  Looking forward to the new version.

**Comment by kmmbvnr** [comment]
1.6.7 released
