### ISSUE TITLE
Support in Start New App - Error "django.template.exceptions.TemplateSyntaxError: Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable."

### ISSUE THREAD

**Issue by Cesaaar** [viewflow/django-material#481]
Hello,

I'm trying to start a project with 2 apps, 1 viewflow and 1 django-material for CRUD. Viewflow it's ok, budget I get the following error on django-material app "**Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable.**"

I started the project "ictg" and under the project I started the app 'vflow' and the module 'budget' with this command:

> ./manage.py startmodule budget

- INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sslserver',
    'django_auth_adfs',
    'material',
    'material.frontend',
    #'material.admin',
    'viewflow',
    'viewflow.frontend',
    'ictg.vflow',
    'ictg.budget'
]

- ROOT_URLCONF = 'ictg.urls'

- ictg.urls
urlpatterns = [
    url(r'^$', generic.RedirectView.as_view(url='/workflow/', permanent=False)),
    url(r'', include(frontend_urls)),
    url('oauth2/', include('django_auth_adfs.urls')),
    url('admin/', admin.site.urls),
    url(r'^budget/', include('ictg.budget.urls', namespace='budget'))
   ]

- budget.urls
urlpatterns = [
    url('^$', generic.RedirectView.as_view(url='./budget/'), name="index"),
    url('^budget/', include(views.MyModelViewSet().urls)),
]

- budget.views
class MyModelViewSet(ModelViewSet):
    model = models.Budget

-budget.model
class Budget(models.Model):
    """Model representing the Budget"""
    # Fields
    rif = models.CharField(max_length [...]

Can you help me?

Thanks
Andrea

**Comment by Cesaaar** [comment]
Resolved! This is the solutions:

- INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sslserver',
    'django_auth_adfs',
    'material',
    'material.frontend',
    #'material.admin',
    'viewflow',
    'viewflow.frontend',
    'ictg.vflow',
    #'ictg.budget',
    'ictg.budget.apps.BudgetConfig'
]

- ictg.urls
urlpatterns = [
    url(r'', include(frontend_urls)),
    url('oauth2/', include('django_auth_adfs.urls')),
    url('admin/', admin.site.urls),
   ]

- vflow.urls
urlpatterns = [
    url(r'^$', generic.RedirectView.as_view(url='/workflow/', permanent=False)),
    FlowViewSet(ShipmentFlow).urls
]

- budget.urls
urlpatterns = [
    url('^$', generic.RedirectView.as_view(url='./model/'), name="index"),
    url('^model/', include(views.BudgetViewSet().urls)),
    #url('^forecast/', include(views.ForecastViewSet().urls)),
]

**Comment by MScMechatronics** [comment]
I have the same very problem, where I receive error
"Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable"
How did you exactly resolve it?

**Comment by Cesaaar** [comment]
It's all about url settings

**Comment by MScMechatronics** [comment]
Thanks, I just solved it. I did not have url for frontend in the root url config file. I added below code in the root urls.py file which then solved my problem.
urlpatterns = [
url(r'^$', generic.RedirectView.as_view(url='/workflow/', permanent=False)),
url(r'', include(frontend_urls)),
