### ISSUE TITLE
Django Material Admin Support for Django 2.2 and Python 3.6

### ISSUE THREAD

**Issue by nagarjuna-satish** [viewflow/django-material#486]
We started using Django Material since from Django 1.9 where the Django Material has supported for Django Admin, currently, we are upgrading the Python 2.2 to 3.6 and Django 1.9 to 2.2, where we are facing issues related to Material design which is not supporting the Django Admin, as we have done lot many customizations in Admin based on the material design, we won't be able to revert back or change to any other admin designs of Django, Please let me know that whether Django Material Admin supports Python 3.6 and Django 2.2, if so please guide me the process how to update the Django material admin to support the Python 3.6 and Django 2.2. Please revert me back as soon as you can.

**Comment by kmmbvnr** [comment]
Due to missing paid customers for this feature, admin support was removed a long ago #373
