### ISSUE TITLE
TypeError: 'DateTimeFormatsIterator' object is not subscriptable

### ISSUE THREAD

**Issue by andrewyager** [viewflow/django-material#490]
In (at least Django 3.1) DateTimeFormatsIterator is now an iterator (if it wasn't before)

https://github.com/viewflow/django-material/blob/edbd9b31673c865c987b7d4c331223a7465ad42e/material/templatetags/material_form_internal.py#L120

This particular line of code fails because it is no longer an array. The correct syntax would look more like

`input_format = field.input_formats.next()`

**Comment by kmmbvnr** [comment]
Thanks for notice!
