### ISSUE TITLE
Possible conflict with two modules?

### ISSUE THREAD

**Issue by jcmlima-t4s** [viewflow/django-material#494]
I downloaded and run the demo app.
When I create another module/app (named Orders in my case), configure it and so on, I start receiving the error

`NoReverseMatch at /employees/departments/`

when accessing http://127.0.0.1:8000/employees/departments/

I have both AppConfigs defined as

`
class OrdersConfig(ModuleMixin, AppConfig):
    name = 'seller_backoffice.apps.orders'

class EmployeesConfig(ModuleMixin, AppConfig):
    name = 'seller_backoffice.apps.employees'
`

Also, urls.py as

orders/urls.py
`
urlpatterns = [
    re_path('^$', generic.RedirectView.as_view(
        url='./orders/'), name="index"),
    re_path('^orders/', include(views.OrderViewSet().urls)),
]
`

and employees/urls.py

`
urlpatterns = [
    re_path('^$', generic.RedirectView.as_view(
        url='./departments/'), name="index"),
    re_path('^departments/', include(views.DepartmentViewSet().urls)),
    re_path('^employees/', include(views.EmployeeViewSet().urls)),
]
`

And the full error page is 

<img width="1465" alt="Screen Shot 2021-01-14 at 11 16 22" src="https://user-images.githubusercontent.com/69477759/104602243-f48ea800-5659-11eb-98b5-00be73601561.png">

**but**, If I comment on one of the two app's, I don't get the error.

Is it a bug or a misconfiguration on my end?

**Comment by jcmlima-t4s** [comment]
Correcting employees/urls.py

urlpatterns = [ re_path('^$', generic.RedirectView.as_view( url='./departments/'), name="index"), re_path('^departments/', include(views.DepartmentViewSet().urls)), re_path('^employees/', include(views.EmployeeViewSet().urls)), ]

**Comment by kmmbvnr** [comment]
After module is define the ./manage.py migrate need to be executed, to get module enabled
