### ISSUE TITLE
VariableDoesNotExist - error in \material\templates\material\fields\django_datetimeinput.html

### ISSUE THREAD

**Issue by robertkowalski1974** [viewflow/django-material#497]
Template does not render any DateTimeField type.

Model:

`class Wtn(models.Model):
    form_id = models.IntegerField()
    form_name = models.CharField(max_length=250)
    submitted_on = models.DateTimeField(blank = True, null=True, default = timezone.now)`

Then get following error in \material\templates\material\fields\django_datetimeinput.html, error at line 19
`{% if bound_field.value %}value="{{ bound_field.value|datepicker_value:field.input_formats.0 }}"{% endif `%}``

Is it related to #495 ?

If I will remove DateTimeField from model all works fine.

**Comment by kmmbvnr** [comment]
Thank you for reporting! fixed

**Comment by robertkowalski1974** [comment]
Hello. I have not made extensive tests, but now error is

strftime() argument 1 must be str, not DateTimeField

Will have a look later why it is there.

**Comment by robertkowalski1974** [comment]
All good. 
Thank you for quick fix.
