### ISSUE TITLE
CRUD Pages Security

### ISSUE THREAD

**Issue by refactoredXYZ** [viewflow/django-material#499]
Hi,

I'm fairly new to the Django ecosystem and really impressed with the CRUD pages I've been able to generate using django-material.

I've read that Django admin pages should not be exposed to end users of a Django application and only be limited to administrators. Does that imply that CRUD pages generated using django-material should also not be exposed to end users of my application? Are there any specific measures I should be taking if I want to expose CRUD pages to end users?
The phrases "admin-line applications development" in the project description and "lightweight alternative to Django admin" in the docs are confusing me.

Thanks in advance

**Comment by kmmbvnr** [comment]
Unlike django admin, django-material crud is a composition of class-based views suitable for common projects

https://docs.djangoproject.com/en/3.1/topics/class-based-views/

**Comment by refactoredXYZ** [comment]
Thanks!
