### ISSUE TITLE
Support autocomplete-light

### ISSUE THREAD

**Issue by olivierdalang** [viewflow/django-material#50]
Hi !

I love django-material, but it doesn't seem to support autocomplete foreign key widgets. That's a deal breaker as soon as there's a model with lot of instances, which happens pretty often.
I guess the best would be to support django-autocomplete-light !

Awesome work by the way, the UI is gorgeous ! I really hope I can adopt it !

**Comment by kmmbvnr** [comment]
Django-material is big enough project. There is no plans to have here anything than core django support.

**Comment by auvipy** [comment]
@kmmbvnr good decision!

@olivierdalang work is going on for supporting auto complit light like feature i django. you could help the progress.
