### ISSUE TITLE
List view slow since 1.9.0

### ISSUE THREAD

**Issue by SamuelLayNZ** [viewflow/django-material#507]
Not sure if this is something specific to my setup or not, but since updating to 1.9.0 list views with large amounts of data take a long time to load despite pagination. Perhaps it is related to #224 ?

For example, loading a list that has 135700 entries, showing 100 at a time (1357 pages)
1.9.0: 23 Seconds
1.7.6: About 2.5 Seconds

I've rolled by production system back 1.7.6 so no huge rush here.
Thanks

**Comment by kmmbvnr** [comment]
I've added some improvments, that would be released in 1.10.0

But better speed up goes with Viewflow 2.0 and pure html table rendering, without datatables
