### ISSUE TITLE
AjaxMultipleModelSelect rendering is unpolished

### ISSUE THREAD

**Issue by Zenonquest** [viewflow/django-material#509]
I'm having a few issues with the way that the AjaxMultipleModelSelect field is rendered. 
1. The label doesn't become active.  It stays large and is positioned in the field.  Clicking and typing into the field doesn't move the label to the top-left corner.  The label ends up overlapping with the chips.  See example from demo http://demo.viewflow.io/integration/sea/add/
![image](https://user-images.githubusercontent.com/10536312/125539957-21645952-8f21-4438-8ff0-e1669c177a05.png)

2. Original select field isn't hidden.  The AjaxMultipleModelSelect field just renders below the default select field.  May be an individual issue as this doesn't seem to be an issue in the demo.  I've been writing my own JS function to hide the original select field (mimicking the behavior of AjaxModelSelect fields, which do render properly).
![image](https://user-images.githubusercontent.com/10536312/125540302-3c8e9aa1-ccb5-4c1c-8d00-e7e719b03612.png)

Otherwise been mostly happy with the library.  Thank you!

django-material-pro==1.7.6

**Comment by kmmbvnr** [comment]
Please contact over Zendesk for PRO version questions - http://viewflow.io/contacts

Looks like stlyes was clased with some your custom code, that makes select field looks different

https://github.com/viewflow/django-material/blob/master/material/static/material/css/materialize.css#L6708

**Comment by kmmbvnr** [comment]
I fixed the label positions for empty widgets, would be available in 1.10.0
