### ISSUE TITLE
Warning when recompile material.components.js with closure compiler 

### ISSUE THREAD

**Issue by nikolaysm** [viewflow/django-material#515]
Hi @kmmbvnr ,

I get a warning when compiling of **materialize.components.js**.

Here is an issue: https://github.com/google/closure-compiler/issues/2046#issuecomment-250036627

From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#invoking_strict_mode:

> Strict mode applies to entire scripts or to individual functions. It doesn't apply to block statements enclosed in {} braces; attempting to apply it to such contexts does nothing. eval code, Function code, event handler attributes, strings passed to setTimeout(), and related functions are entire scripts, and invoking strict mode in them works as expected.

`'use strict'` doesn't make sense in this case so.?

**Comment by kmmbvnr** [comment]
materialize.components.js file is already compiled from many sources

"use strict" looks like completely legitimate construct

**Comment by kmmbvnr** [comment]
Seems most of "use strict" added by babel

https://stackoverflow.com/questions/33821312/how-to-remove-global-use-strict-added-by-babel

Probably material build process could be improved to fix this

**Comment by nikolaysm** [comment]
> materialize.components.js file is already compiled from many sources
> 
> "use strict" looks like completely legitimate construct

`'use strict'` doesn't make sense as a directive unless it's the **first line of a file** or the **first line of a function**.

The correct use is then:
```
(function () {
  'use strict'; ⬅️ HERE
  if ( // No Reflect, no classes, no need for shim because native custom elements
  // require ES2015 classes or Reflect.
  ...
})();
```
