### ISSUE TITLE
Localization app in portuguese Brazil

### ISSUE THREAD

**Issue by lukasgarcya** [viewflow/django-material#52]
I want to help with translation this app to my tongue, Portuguese Brazil.
Can I create a locale folder and start putting the translation?

**Comment by kmmbvnr** [comment]
Yeah, sure. Thanks for the suggestion. Go ahead!

**Comment by lukasgarcya** [comment]
I just sent the translation.

**Comment by lukasgarcya** [comment]
My translation is pull request #58
