### ISSUE TITLE
if statement fetch all rows, slowdown

### ISSUE THREAD

**Issue by rasulovmuxtor** [viewflow/django-material#520]
material.frontend.views.list.DataTableMixin.get_data_attr    _line 220_

please change to something like this:
`if hasattr(self, 'object_list') and self.object_list is not None:`

https://github.com/viewflow/django-material/blob/615913ea86db35e56e518a772d317dc44f392f2b/material/frontend/views/list.py#L220

https://docs.djangoproject.com/en/4.0/ref/models/querysets/#when-querysets-are-evaluated

**Comment by kmmbvnr** [comment]
Thank you for good point! I wasn't able to spot the problem

Seems this fixes it? https://github.com/viewflow/django-material/commit/55561ac10e40c5e21bbc7fc42dba77a13b20384e
