### ISSUE TITLE
Tooltip not initialized

### ISSUE THREAD

**Issue by doudz** [viewflow/django-material#521]
Looks like the tooltip feature is not initialized as the following code doesn't work
`  <a class="btn tooltipped" data-position="bottom" data-tooltip="I am a tooltip">Hover me!</a>
`
Adding the following make it works

`$(document).ready(function(){
    $('.tooltipped').tooltip();
  });`

**Comment by kmmbvnr** [comment]
django-material contains js initialization code only for used in the frontend components
