### ISSUE TITLE
Reverse for 'index' not found. 'index' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by variable** [viewflow/django-material#534]
Similar to https://github.com/viewflow/django-material/issues/329

![image](https://user-images.githubusercontent.com/558175/224191588-b44588b7-0af9-48b4-ab44-73606210887c.png)

I did not get this error when running on Django 2.2, but once upgraded to Django 3.2 the error is raised in `material/frontend/apps.py`

```python
    def index_url(self):
        """Entry url for a module."""
        return reverse('{}:index'.format(self.label))
```

The app it is complaining about doesn't have `urls.py` at all.

So downgraded back to Django 2.2 and add a print statement to see if this gets called

```python
    def index_url(self):
        """Entry url for a module."""
        print(111111111111, self.label)
        return reverse('{}:index'.format(self.label))
```

It doesn't get called in Django 2.2

**Comment by kmmbvnr** [comment]
Based on the information you provided, it's difficult to determine the root cause of the issue. However, before further investigation, can you confirm if you have already run ./manage.py migrate after upgrading to Django 3.2? This might be a possible reason for the error.

**Comment by variable** [comment]
Yes I ran the migration, can you please explain why would it matter?

**Comment by kmmbvnr** [comment]
The reason why it matters is that Django-material allows you to enable/disable module urls by admin, and the migration creates a default entry with installed=True status. This could affect the behavior of the application, which is why it's important to make sure the migration has been run successfully.

**Comment by variable** [comment]
> The reason why it matters is that Django-material allows you to enable/disable module urls by admin, and the migration creates a default entry with installed=True status. This could affect the behavior of the application, which is why it's important to make sure the migration has been run successfully.

I see, is this something new related to django 3.2? Because on production running django 2.2 those modules are not registered in the "frontend admin"

**Comment by kmmbvnr** [comment]
Nope, it should not be related to the Django Version

Viewflow 2.x simplify URL handling by switching to Class-based URL and remove built-in options of installed modules. Also it could be implemented, on a client side
