### ISSUE TITLE
jinja2 template support with django-jinja help

### ISSUE THREAD

**Issue by auvipy** [viewflow/django-material#54]

**Comment by kmmbvnr** [comment]
What is the reason to have jinja2 support for django-material?

I made django-material for projects with complex forms like http://forms.viewflow.io/demo/bank/
The time required to fill the form is much greater than time to render. There is no reason to speed up template rendering.

 Is there any advantages in template syntax that could be implemented with jinja2? Could we simplify {% parts %} redefinition somehow?

**Comment by auvipy** [comment]
not fully sure about all your queries right now, but django 1.10 will ship the template based form rendering mechanism where jinja2 and dtl both will be supported.

**Comment by kmmbvnr** [comment]
So, what? Supporting jinja2 in django-material doubles amount of work required. What is the reason to do that?

**Comment by auvipy** [comment]
https://github.com/niwinz/django-jinja/blob/strip/doc/content.adoc#rationale

I will be helping you to get that completed.

**Comment by kmmbvnr** [comment]
Still see no reasons

**Comment by sassanh** [comment]
A project that is using jinja already and has lots of jinja templates and wants to use material seems to be a good reason.

**Comment by auvipy** [comment]
I agree with you @sassanh
