### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by lukasgarcya** [viewflow/django-material#59]
I try change password and show this error: Invalid block tag: 'form', expected 'endblock'.

**Comment by kmmbvnr** [comment]
What version of django-material do you use?

**Comment by lukasgarcya** [comment]
I tried in django-material 0.5.1 and 0.4.1 but without success.

**Comment by kmmbvnr** [comment]
why it works for me? http://forms.viewflow.io/admin/auth/user/2/

it was fixed a long ago

**Comment by kmmbvnr** [comment]
Could you please try latest  git version?

**Comment by lukasgarcya** [comment]
Try the link http://forms.viewflow.io/admin/auth/user/2/password/

**Comment by kmmbvnr** [comment]
still works

**Comment by kmmbvnr** [comment]
mm, i've got the problem, i've added material_form template tags library to build-in tags

So it's fixed now correctly in git

**Comment by lukasgarcya** [comment]
I tried and it's fine.

**Comment by nass600** [comment]
Any chance to get a tag and pypi version for this fix?
