### ISSUE TITLE
Use of permission_required

### ISSUE THREAD

**Issue by lukasgarcya** [viewflow/django-material#62]
The module does not generate dynamic urls depending on the user's permission
Logged.
Also when the user is not logged you are presenting error accessing the url.

**Comment by kmmbvnr** [comment]
I don't get the problem. Could you provide an example?

URLs can't be dynamic. It created once on django appstart and cached.

**Comment by lukasgarcya** [comment]
from django.contrib.auth.decorators import permission_required
I talk about url this url(r'^my_link/$', permission_required('app.model.any_permission')(View.as_view())),

**Comment by lukasgarcya** [comment]
In the https://docs.djangoproject.com/en/1.8/topics/class-based-views/intro/#decorating-class-based-views show permission in my url.

**Comment by kmmbvnr** [comment]
I have 6 years experience with django development. I know about permission required decorator.

I just can't understand how your issue related to django-material functionality

**Comment by lukasgarcya** [comment]
Case the user not login or have not permission the link is showing.

**Comment by lukasgarcya** [comment]
In getter explained how to solve
