### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by dajose22** [viewflow/django-material#67]
I installed django 1.9, on python 3.4. I copied the first form example from http://forms.viewflow.io/. 
When I run ```python manage.py runserver``` the dropdown for gender is not showing and the hover texts for fields is over the text I input.

When I inspect the page there is an error:

```
Uncaught ReferenceError: jQuery is not defined(anonymous function) @ jquery.datetimepicker.js:1631
jquery.formset.js:224 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ jquery.formset.js:224
materialize.js:44 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ materialize.js:44
material_init.js:5 Uncaught ReferenceError: $ is not defined(anonymous function) @ material_init.js:5
```

Any help?

**Comment by kmmbvnr** [comment]
Yep, jquery is no longer shippedwith django-material, you need to include them explicitly

```
   <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
   {% include 'material/includes/material_js.html' %}
```

**Comment by dajose22** [comment]
thanks for the quick answer!
