### ISSUE TITLE
Bad Static URL in material_init.js:2 

### ISSUE THREAD

**Issue by mikeumus** [viewflow/django-material#68]
It's loading urls like this:

`https://coderbounty-dev-mikeumus.c9users.io/accounts/signup/%7B%%20static `

Which gives an error and can't load robotofix.css from `material_init.js`: 
- https://github.com/viewflow/django-material/blob/9222431db84384859546b1349180a93e535164c2/material/static/material/js/material_init.js#L2

Not sure if I just have my `STATIC` setup in a bad way or if it's something else.

![](https://imgflip.com/s/meme/Futurama-Fry.jpg)

**Comment by kmmbvnr** [comment]
Isn't your settings problem?

In browser the line expands to
```
    <script type="text/javascript">
      if (navigator.appVersion.indexOf("Win")!=-1) {
           document.write('<link rel="stylesheet" type="text/css" href="/static/material/css/robotofix.css">');
      }
    </script>
```

**Comment by mikeumus** [comment]
Hey @kmmbvnr, thanks for a speedy reply. That is how I have `STATIC_URL` setup that way you said, see: 
- https://github.com/mikeumus/coderbounty-mikeDev/blob/django-material/coderbounty/settings.py#L189

**Comment by kmmbvnr** [comment]
Could you just debug and fix it?
