### ISSUE TITLE
Admin Date widget vs Apple Magic Mouse

### ISSUE THREAD

**Issue by machinist** [viewflow/django-material#74]
The date widget responds very sensitive to the apple magic mouse. When you scroll using mouse gestures  and your mouse pointer accidentally hovers over a date field it changes the value.

**Comment by kmmbvnr** [comment]
could be fixed by disabling scroll handling - https://github.com/viewflow/django-material/blob/master/material/static/material/js/jquery.datetimepicker.js#L291
