### ISSUE TITLE
Show image and nested inline in admin page

### ISSUE THREAD

**Issue by MahmoudFarid** [viewflow/django-material#75]
Hi, I have a problem when I upload the image, the URL doesn't appear when to save and the field still empty. but in fact, it saved in DB. what is the solution?
another problem, when using nested inline in an admin page using django-super-inlines app, the nested inline not create correctly and create with wrong design.

**Comment by kmmbvnr** [comment]
Nested inlines as any other 3d party app is not supported

**Comment by MahmoudFarid** [comment]
thanks
what about imageField it doesn't appear the image or URL?
another problem, when I set a default value in any integer field, it doesn't appear and still blank

**Comment by kmmbvnr** [comment]
pull requests are welcome

**Comment by kmmbvnr** [comment]
ImageField issues should be fixed in be2b9c165feaa02b292531ddeff584faa8f0cdd7
