### ISSUE TITLE
Faild to show multiples itens in list view (select-dropdown)

### ISSUE THREAD

**Issue by dmsouza** [viewflow/django-material#76]
Failure happens when a list with a lot of data is shown, never reaches the beginning, only the end.
The test was performed using the admin "ForeignKey" and "choices"

**Comment by kmmbvnr** [comment]
Is country fileld on http://forms.viewflow.io/demo/bank/ the right sample of this problem?

**Comment by dmsouza** [comment]
Yes, but on admin mode.See this exemple:http://iasdinfo.com.br/admin/departamentos/departamento/11/change/
user: danielpass: 123
Check "Diretor" filed, we have names with start letters "A".
Best,
Daniel Souza
"Quando a gente ora, alguma coisa acontece"

@dmsouza7

Date: Mon, 8 Feb 2016 18:37:51 -0800

**Comment by kmmbvnr** [comment]
fixed

**Comment by dmsouza** [comment]
Perfect!!!
