### ISSUE TITLE
forms.MultipleChoiceField do no materializing

### ISSUE THREAD

**Issue by dimka665** [viewflow/django-material#80]
`forms.MultipleChoiceField` has no materialized implementation. It's standard widget.
Django 1.9.2
django-material 0.3.0

**Comment by kmmbvnr** [comment]
That's not true

**Comment by dimka665** [comment]
It's good with `widget=forms.CheckboxSelectMultiple`, but no changes without widget specification.

**Comment by kmmbvnr** [comment]
Have you missed to include jquery before `includes/material_js.html`?

**Comment by dimka665** [comment]
No.
I use Python 3

**Comment by dimka665** [comment]
I tried your example code and got the same.

My code render result of `{% form %}{% ednform %}`:

```
<div class="row">
    <div id="id_languages_container" class="select-field col s12 required multiselect">
        <label for="id_languages" class="">Язык</label> <select class="material-ignore" name="languages" id="id_languages" multiple="">
            <option value="**">Не зависит </option>
        
        <option value="EN">Английский </option>
        
        <option value="RU">Русский </option>
        
        <option value="DE">Немецкий </option>
        </select>
    </div>
</div>
<div class="row">
    <div id="id_languages_container" class="select-field col s12 required multiselect">
        <label for="id_languages" class="">Язык</label> <select class="material-ignore" name="languages" id="id_languages" multiple="">
            <option value="**">Не зависит </option>
        
        <option value="EN">Английский </option>
        
        <option value="RU">Русский </option>
        
        <option value="DE">Немецкий </option>
        </select>
    </div>
</div>
```

**Comment by kmmbvnr** [comment]
You should check javascript errors in the browser console

**Comment by kmmbvnr** [comment]
** class="material-ignore"** lol, are you about admin part? This is not `MultipleChoiceField`

**Comment by dimka665** [comment]
No. It's my FormView with your example form or my form. Result is the same.
Default multiple select widget if `field = forms.MultipleChoiceField(...,
widget=forms.SelectMultiple)`

2016-02-19 13:54 GMT+03:00 Mikhail Podgurskiy <notifications@github.com>:

**Comment by kmmbvnr** [comment]
I have no idea, what's wrong with you code.

You copy-pasted the code that could be rendered only from `django_filteredselectmultiple.html` That's the admin part.

**Comment by dimka665** [comment]
I don't include `material.admin` to INSTALLED_APPS even.

`templates/material/fields/django_selectmultiple.html` content:
```
{% load material_form material_form_internal %}

{% render bound_field template='fields/django_select.html' %}
    {% part field add_control_attr %}multiple{% endpart %}
    {% part field add_group_class %}multiselect{% endpart %}
    {% part field add_control_class %}material-ignore{% endpart %}
    {% part field options %}
        {% for value, choice in field.widget.choices %}
        <option {% if value in bound_field.value %}selected="selected"{% endif %}
                {% if value == None or value == '' %}style="display:none"{% endif %}
                value="{{ value|default_if_none:"" }}" >{% if value == None or value == '' %}{{ form_select_empty_label|default:choice }}{% else %}{{ choice }}{% endif %} </option>
        {% endfor %}
    {% endpart %}
{% endrender %}
```

**Comment by kmmbvnr** [comment]
That's not true - https://github.com/viewflow/django-material/blob/master/material/templates/material/fields/django_selectmultiple.html

**Comment by dimka665** [comment]
I use last release 0.5.1

2016-02-19 15:02 GMT+03:00 Mikhail Podgurskiy <notifications@github.com>:

**Comment by kmmbvnr** [comment]
You should use git, before posting issue requests

**Comment by dimka665** [comment]
I tried. Master is broken.
```
Invalid filter: 'select_options'
In template /home/dima/.virtualenvs/mathtrade/lib/python3.4/site-packages/material/templates/material/fields/django_select.html, error at line 18
```

**Comment by kmmbvnr** [comment]
So, why you spend my time on a fake error, instead of report the real one?

**Comment by kmmbvnr** [comment]
And how did you get the error? Did you grab the whole code or just html template?

**Comment by dimka665** [comment]
It's `DEBUG=True` output.
I installed master version.

2016-02-19 15:17 GMT+03:00 Mikhail Podgurskiy <notifications@github.com>:

**Comment by kmmbvnr** [comment]
I have no such error.

**Comment by dimka665** [comment]
It's OK now

2016-02-19 15:24 GMT+03:00 Mikhail Podgurskiy <notifications@github.com>:
