### ISSUE TITLE
Django admin change password

### ISSUE THREAD

**Issue by pace-noge** [viewflow/django-material#92]
Change password on admin page
error:
Invalid block tag on line 14: 'form', expected 'endblock'. Did you forget to register or load this tag?

I'm trying to add 
{% load material_form %}

it loaded but it renders with html tag in help block tag

![screen shot 2016-02-15 at 6 18 42 am](https://cloud.githubusercontent.com/assets/3381132/13037119/210fb9ae-d3ac-11e5-9918-bf497a2b18ff.png)

**Comment by kmmbvnr** [comment]
already fixed http://forms.viewflow.io/admin/auth/user/2/password/
