### ISSUE TITLE
Error in change_form.html

### ISSUE THREAD

**Issue by saduqz** [viewflow/django-material#93]
This bug is fixed in master branch.

I download django-material from pip install django-material (Version 0.5.1).

The broken code in change_password.html is:
{% load i18n admin_static admin_urls %}

This is the fix: (Actually in bran master).
{% load i18n admin_static admin_urls  material_form %}

But, why when install django-material from pip (0.5.1) no is fixed?

![screenshot from 2016-02-19 00-26-28](https://cloud.githubusercontent.com/assets/12383552/13167253/8cf71c0c-d69f-11e5-94da-4d08e90a4ef1.png)

![screenshot from 2016-02-19 00-26-40](https://cloud.githubusercontent.com/assets/12383552/13167254/8cf90be8-d69f-11e5-81ff-190549f41e26.png)

![screenshot from 2016-02-19 00-27-15](https://cloud.githubusercontent.com/assets/12383552/13167266/a2bc60ec-d69f-11e5-9645-291775230eae.png)

**Comment by kmmbvnr** [comment]
**This bug is fixed in master branch**

**Comment by saduqz** [comment]
Yes... But no is fixed when it is downloaded from pip.

**Comment by kmmbvnr** [comment]
Isn't this obvious? B/c it's this not released.
