### ISSUE TITLE
Syntax Error: Unexpected Token <

### ISSUE THREAD

**Issue by davidthewatson** [viewflow/django-material#95]
I'm seeing this problem with material admin. I first observed this running on gunicorn in a staging environment, but after further investigation, I was able to duplicate it locally in debug mode:

![screen shot 2016-02-24 at 2 16 09 pm](https://cloud.githubusercontent.com/assets/150892/13297661/65feeed4-db01-11e5-89b8-8ab98212bfe3.png)

I'm running python 3.5.1, Django 1.9.2, on Mac OS X 10.11, and django-material==0.6.0. My code is a verbatim copy of the material admin install instructions. When running gunicorn, the page renders without CSS. The debug webserver seems to find the CSS fine.

**Comment by kmmbvnr** [comment]
Yep, thank. I need to exclude script `jsi18n` from login page.

To temporary solve the issue with font-awesome you can include `material.frontend` in the INSTALLED_APPS  of override `admin/includes/material_css.html` template
