### ISSUE TITLE
Using modules

### ISSUE THREAD

**Issue by lukasgarcya** [viewflow/django-material#99]
When using module with template 'material/frontend/base_module.html' simply pjax loads of content that does not come the head of the html and I have some javascript and css that are not loaded.

**Comment by kmmbvnr** [comment]
That's is how pjax works. No head/css/js are loaded on pjax call, That's why pjax is so fast.

You should override base template {% block extrahead %}{% endblock %}

**Comment by kmmbvnr** [comment]
Btw, is it happens, when you navigated from one module to another?

You can make such links with `no-pjax` class, ex:: 

     <a href='...' class="no-pjax">another module link"></a>

elsewhere the right side menu don't be updated also.

**Comment by lukasgarcya** [comment]
I'll try and tell how it worked.

**Comment by lukasgarcya** [comment]
I used no-pjax and work fine.
